- Stepic/QuizViewController.swift
- StepicAdaptiveCourse/AdaptiveStepPresenter.swift
- StepicAdaptiveCourse/AdaptiveStepsPresenter.swift
Для каждого степа в адаптивном приложении теперь принудительно создаём новый attempt, чтобы не нужно было лишнего действия для повторного решения и не нужно было скипать уже решенные степы (как это происходит сейчас – [APPS-1319](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1319)).
> New attempts in adaptive app

- StepicAdaptiveCourse/CongratulationViewController.swift
Фикс краша на айпадах из-за незаданного popoverPresentationController.sourceView у UIActivityViewController в диалоге о достижении уровня.
> Fix crash on iPad

- Stepic.xcodeproj/project.pbxproj
- Stepic/AnalyticsEvents.swift
- Stepic/ApiDataDownloader.swift
- Stepic/FindCoursesViewController.swift
- Stepic/QueriesAPI.swift
- Stepic/SearchQueriesPersistentManager.swift
- Stepic/SearchQueriesPresenter.swift
- Stepic/SearchQueriesView.swift
- Stepic/SearchQueriesViewController.swift
- Stepic/SearchResultsCoursesViewController.swift
- Stepic/SearchSuggestionTableViewCell.swift
- Stepic/SearchSuggestionTableViewCell.xib
При поиске курсов теперь используется механизм с подсказками для поиска.
Подсказки появляются в следующем порядке:
1. Текущий запрос пользователя
2. До трех подсказок, которые пользователь уже искал, отсортированных по следующим параметрам:  
* Сначала те запросы, которые пользователь делал чаще
* Из запросов с одинаковой встречаемостью выше будет запрос с меньшей длиной
* Если у запросов длина и встречаемость одинаковы, только бог знает, в каком порядке они будут выдаваться пользователю
3. Те подсказки, которые пришли с api/search-queries
Конечно, каждая подсказка должна быть уникальной.
> Course Search Queries

- Stepic/WebStepViewController.swift
В степах раньше не работали аудио блоки.
Теперь работают.
> Steps audio block fix 

- Stepic/AuthInfo.swift
Исправление ситуации, когда токен протухает.
Возможно, будем исследовать дальше баг, но пока так.
> Fixes for bad token refreshes

- StepicAdaptiveCourse/AdaptiveStepsPresenter.swift
- StepicAdaptiveCourse/AdaptiveStepsViewController.swift
Вернул плейсхолдер для состояния "курс пройден" [APPS-1398](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1398)
> Add 'course passed' state

- Stepic/SectionsViewController.swift
**Задача**: [#APPS-1332](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1332)
Обновляем прогресс по секции после решения задания
**Описание**:
Просто делаю `loadProgressesForSections()` по `viewWillAppear`, если список секций уже прогружен
> Section progress update after solved step

- Stepic/SearchQueriesViewController.swift
- Stepic/SearchSuggestionTableViewCell.swift
- Stepic/SearchSuggestionTableViewCell.xib
**Задача**: [#1399](https://vyahhi.myjetbrains.com/youtrack/issue/1399)
Улучшили подсказки при поиске:
* Длинные подсказки теперь влезают в строку
* **Под**свечивается **под**строка с запросом в **под**сказке
**Описание**:
Небольшие изменения в UI: добавил UITableViewAutomaticDimension для вычисления высоты клетки и подсвечиваю подстроку с query в ячейке с помощью attributedString.
> Search Queries enhancements

- Stepic/LessonPresenter.swift
- Stepic/LessonViewController.swift
- Stepic/QuizPresenter.swift
- Stepic/QuizViewController.swift
**Задача**: [#APPS-1405](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1405)
При медленном соединении после обновления урока пользователь не перекидывается на первый таб.
**Описание**:
Добавил немного зависимостей в `LessonPresenter`, а так же исправил эту ошибку. Возможно, мы также этим пофиксим львиную долю крашей, которые приходятся на несвоевременный выбор таба.
> Fixed annoying selection of initial step with bad connection

- Stepic/CodeLanguages.swift
- Stepic/CodeLimit.swift
- Stepic/CodeQuizViewController.swift
- Stepic/CodeReply.swift
- Stepic/CodeTemplate.swift
- Stepic/FullscreenCodeQuizViewController.swift
- Stepic/en.lproj/Localizable.strings
- Stepic/ru.lproj/Localizable.strings
**Задача**: [#1377](https://vyahhi.myjetbrains.com/youtrack/issue/1377) и [#1404](https://vyahhi.myjetbrains.com/youtrack/issue/1404)
Добавили Perl в Code Quiz, а так же неподдерживаемые языки теперь не отображаются (раньше отображался треш)
**Описание**:
Убрал `.unsupported` кейс из `CodeLanguage` и не отображаю неподдерживаемые языки в принципе (их нельзя выбрать в пикере или просмотреть submission). В дальнейшем можно придумать что-нибудь поумнее, но пока выглядит так.
> Perl to Code Quiz & unsupported language enhancements

- Stepic/HTMLBuilder.swift
- Stepic/WebStepViewController.swift
**Задача**: [#APPS-1409](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1409)
Исправлен баг с картинками, которые загружаются по protocol-relative ссылкам
**Описание**:
Фикс из #78 немного изменен (теперь меняем все `src="//`) и перемещен в функцию которую юзают оба приложения.
> Fix protocol-relative URLs

- Stepic/QuizViewController.swift
**Задача**: [#APPS-1406](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1406)
Для шагов с ограничением попыток после рефакторинга текст не всегда влезал в кнопку. Теперь влезает.
**Описание**:
Send button title сбрасывается теперь каждый раз в `update(limit:)`, а не только в случае, если `limit == nil`
> Fixed limited submissions long button text bug

- Stepic/ChoiceQuizTableViewCell.swift
- Stepic/SortingQuizTableViewCell.swift
**Задача**: [#APPS-1415](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1415)
Возможно, пофиксили самый популярный краш из crashlytics 🎉 
**Описание**:
Убрали UILabel во время рендеринга LaTeX для Choice, Sorting и Matching квизов
> Removed setting a label with plain text while LaTeX rendering

- Stepic.xcodeproj/project.pbxproj
- Stepic/AvatarImageView.swift
- Stepic/DiscussionTableViewCell.swift
- Stepic/DiscussionTableViewCell.xib
- Stepic/DiscussionWebTableViewCell.swift
- Stepic/DiscussionWebTableViewCell.xib
- Stepic/ProfileViewController.swift
- Stepic/TeacherCollectionViewCell.swift
- Stepic/TeacherCollectionViewCell.xib
- Stepic/UserPreferences.storyboard
**Задача**: [#APPS-1420](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1420)
Исправлено отображение аватаров
**Описание**:
SVGKit плохо рендерит текст в svg аватаре. Теперь пытаемся сами взять текст из полученного аватара, после чего генерируем новый средствами UIKit.
> Fix avatars

- Stepic/QuizViewController.swift
**Задача**: [#APPS-1447](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1447)
Теперь rate app диалог появляется, как и должен был.
**Описание**:
Из-за аналитики сломалось. У step-ов в адаптивных аппах нет загруженного lesson-а, поэтому алерт не мог понять, какое отношение `step.position / step.lesson.stepsArray.count`
> Adaptive rate dialog

- Stepic/CodeQuizViewController.swift
**Задача**: [#APPS-1450](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1450)
Исправили ошибку, иногда приводящую к вылету приложения в Code Quiz. 
**Описание**:
Там был force unwrapped optional, пришлось его хорошо обрабатывать в `getReply()`
Ссылка на баг в крашлитикс: https://fabric.io/alexander-karpovs-projects3/ios/apps/com.alexkarpov.stepic/issues/59a82718be077a4dcce4c5e1?time=last-seven-days
> Fixed getReply() crash in Code Quiz

- Stepic/HTMLBuilder.swift
**Задача**: [#APPS-1542](https://vyahhi.myjetbrains.com/youtrack/issue/#APPS-1542)
Исправили баг при автокоррекции URL
**Описание**:
Раньше исправляли все вхождения URL-а, начинающегося с `/` на URL с `https://stepik.org`. Это приводило к тому, что исправлялся URL не только в `href=` и прочих тегах, но и в тексте. Теперь исправляем только вхождения, начинающиеся с кавычки.
> Fixed URL autocorrection bug

- Stepic/CodePlaygroundManager.swift
- Stepic/CodeQuizViewController.swift
- Stepic/FullscreenCodeQuizViewController.swift
- Stepic/SocialAuthPresenter.swift
**Задача**: [#APPS-1496](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1496)
Убрали автозамену кавычек и ускорили рендеринг
**Описание**:
Теперь не заменяем текст (и не перерендериваем TextView) когда присваивается тот же текст, который был.
Также UITextView теперь не заменяет кавычки.
> Code Quiz iOS 11 fixes

- Stepic/CellWebViewHelper.swift
- Stepic/HTMLBuilder.swift
После изменения цветов те хинты, для отображения которых требуется UIWebView, перестали правильно работать. Теперь работают хорошо.
**Описание**:
Отрефакторил немного `HTMLBuilder`, проблема была в нем.
Теперь стало на один странный `build()` метод меньше.
> Fix hint text color

- Stepic/VideoStepViewController.swift
**Задача**: [#APPS-1501](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1501)
Теперь можно нажать на кнопку загрузки в видео степе
**Описание**:
Выяснилось, что теперь `UINavigationBar` использует AutoLayout. Добавил констрейнты на ширину и высоту вьюшки и все заработало.
> Fixed download button in video step

- Stepic/RateAppViewController.swift
**Задача**: [#APPS-1510](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1510)
Теперь можно оценить приложение в AppStore по предложению внутри приложения и на iOS 11.
**Описание**:
Теперь используем `StoreKit` для iOS 11, чтобы показывать рейт диалог.
> Fixed iOS 11 AppStore rate bug

- Stepic/AnalyticsEvents.swift
- Stepic/Block+CoreDataProperties.swift
- Stepic/QuizPresenter.swift
**Задача**: [#APPS-1492](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1492)
Событие submission_created для аналитики.
**Описание**:
Шлём submission_created, когда POST /api/submissions создан.
> Send submission_created to analytics

- fastlane/Fastfile
Исправили падающие тесты
**Описание**:
При добавлении новых подов с актуальными версиями, тесты падают из-за того, что fastlane запускает pod install без обновления репов. В fastlane 2.61.0 в экшн *cocoapods* добавили опцию `try_repo_update_on_error` (*true* по дефолту)  – кажется, это то, что нам нужно.
> Bump fastlane version

- Podfile
- Stepic/HTMLParsingUtil.swift
- Stepic/LabelExtension.swift
- Stepic/TagDetectionUtil.swift
**Задача**: [#APPS-1526](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1526)
Отображаем в UILabel html
**Описание**:
До этого html в UILabel не отображался в принципе (при этом, рендерился в NSAttributedString и постоянно крашился). Теперь отображаем некоторое множество тегов для форматирования текста.
Ещё подробнее в [APPS-1482](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1482).
> HTML in UILabel

- Stepic/Notification.swift
- Stepic/NotificationStatusButton.swift
- Stepic/NotificationsAPI.swift
- Stepic/NotificationsPresenter.swift
- Stepic/NotificationsTableViewCell.swift
- Stepic/NotificationsViewController.swift
Оставляем только два состояния для уведомлений: прочитано/непрочитано.
**Описание**:
Удалил состояние 'opened' и всё, что с ним связано. Переделал поведение кнопки "отметить прочитанным всё".
> Remove 'opened' state for notification

- Stepic/HTMLParsingUtil.swift
Хотфикс детекта html тегов
**Описание**:
В TagDetectionUtil неверно детектились html теги: Kanna добавляет тег `<p>` в некоторых случаях. Из-за этого всегда отображалась WebView, а не Label.
> Fix tags detection

- Stepic/TitleContentExpandableMenuBlockTableViewCell.swift
**Задача**: [#APPS-1451](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1451)
Добавили поддержку html в профиле
**Описание**:
Поле с информацией о пользователе в профиле теперь задается с помощью `setTextWithHTMLString`, которая рендерит NSAttributedString с некоторыми поддерживаемыми тегами.
> Support font style tags in profile

- Stepic/FullscreenCodeQuizViewController.swift
**Задача**: [#APPS-1551](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1551)
Исправили скролл полноэкранного редактора Code Quiz
**Описание**:
Неправильно получались размеры клавиатуры (`UIKeyboardFrameBeginUserInfoKey` вместо `UIKeyboardFrameEndUserInfoKey`), из-за этого неверно рассчитывались `contentInsets` у текстовой вьюшки.
> Fix insets when keyboard did show

- PagerController.swift
**Задача**: [#APPS-1590](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1590)
Пофиксили краши в PagerController
**Описание**:
Вылечен PagerController от force unwrapping'ов, должно перестать крашиться в `setActiveContentIndex()` и других местах.
> PagerController refactoring

- Stepic/AnalyticsEvents.swift
- Stepic/AppDelegate.swift
- Stepic/CoursePreviewViewController.swift
**Задача**: [#APPS-1077](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1077), [#APPS-1076](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1076), [#APPS-1560](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1560), [#APPS-1561](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1561)
Пофиксили неотправляющиеся событий в аналитику и добавили события на интро видео в курсе
**Описание**:
* Переименованы события на экране авторизации и регистрации
* События в CourseOverview, связанные с интро видео
* Фикс события при тапе на уведомлении о стрике
> Fix analytics events

- Stepic/QuizPresenter.swift
**Задача**: [#APPS-1592](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1592)
Добавили параметр `language` к событию `submission_created`
**Описание**:
Для сабмишенов с кодом шлём дополнительный параметр `language` как в андроиде.
> Missed 'language' parameter in code quiz analytics

- Stepic/StyledTabBarViewController.swift
Исправлен таб бар в некоторых ориентациях/размерах
**Описание**:
В iOS 11 изменили отображение подписей у иконок таб бара для некоторых размеров экрана. Исходя из этого, настраиваем таб бар по-разному:
* iOS < 11.0: убираем подписи
* iOS 11.0+: оставляем подписи для лендскейпа и для планшетов  
iPad (iOS 9):
iPad (iOS 11):
iPhone (iOS 9, portrait):
iPhone (iOS 11, portrait):
iPhone (iOS 9, landscape):
iPhone (iOS 11, landscape):
> Tab bar titles

- Stepic/ApiRequest.swift
- Stepic/AppDelegate.swift
Исправили race condition в performRequest
**Описание**:
Добавил диспатч в отдельную очередь и семафоры на проверку токена на валидность.
Возникает проблема, если сразу попытаться рефрешнуть контроллер: несколько CourseList-ов на одном экране пытались одновременно асинхронно рефрешнуть токен и чуда не происходило.
> performRequest race condition fix

- Stepic/StepicVideoPlayerViewController.swift
**Задача**: [#APPS-1616](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1616)
Исправили краш при нажатии кнопки play/pause на гарнитуре
**Описание**:
Если нажать на кнопку play/pause на гарнитуре после закрытия полноэкранного плеера в степе с видео, приложение крашилось из-за того, что в `deinit` блоке не удаляли таргет на селектор из MPRemoteCommandCenter.
> Fix play/pause crash

- Stepic/DiscussionTableViewCell.swift
- Stepic/DiscussionWebTableViewCell.swift
**Задача**: [#APPS-1414](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1414)
Исправили время комментариев
**Описание**:
Для комментария отображалось время из `last_time`, из-за этого родительский комментарий имел время последнего комментария в своей ветке.
> Fix comment time

- Stepic/UnitsViewController.swift
**Задача**: [#APPS-1629](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1629), [#APPS-1647](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1647)
Исправили краш при переходе к экзамену и к пустому модулю с кнопки "Следующий урок"
**Описание**:
* При переходе к экзамену: добавили проверку на то, что следующая секция имеет `isExam == true` и показываем алерт (как в силлабусе).
* При переходе к пустому модулю: смотрим на кол-во юнитов в следующей секции
> Fix crash when navigate to prev/next lesson

- Podfile
- Stepic/Base.lproj/Auth.storyboard
- Stepic/EmailAuthViewController.swift
- Stepic/RegistrationViewController.swift
- Stepic/SocialAuthViewController.swift
Мелкие фиксы вёрстки авторизации
**Описание**:
Некоторые мелкие фиксы с которыми, на мой взгляд, всё выглядит лучше:
* Высота кнопки и текстовых полей (пропорционально макету, но чуть меньше)
* Выпилен под `TextFieldEffects`, который юзался в старой авторизации
* Отступ до кнопки "Войти"/"Зарегистрироваться" 
* Логотип не прыгает при появлении клавиатуры – теперь он прибит к лейблу над текстовыми полями
* На маленьких экранах (4 и меньше дюйма) логотип 48x48 кажется слишком большим. Сделать авто-лейаут, который работает **всегда** и не ломается при этом клавиатурой у меня не получилось – из кода выставляем высоту для таких случаев
> Fix auth layout issues

- Stepic/LastStepRouter.swift
Исправили подгрузку секции, когда осуществляется переход к последнему степу
**Описание**:
При переходе к последнему степу у нас может не быть данных о юните/секции (например, первый запуск) – теперь подгружаем их, если нужно.
> Fix section retrieve for last step

- Stepic/NotificationsAPI.swift
- Stepic/NotificationsPresenter.swift
- Stepic/NotificationsViewController.swift
- Stepic/UsersAPI.swift
Фикс мелких багов в нотификациях и рефакторинг с PromiseKit
**Описание**:
* Убраны легаси методы из презентера, теперь там везде промисы (как и планировалось)
* Фикс ситуации, когда после реюза ячейки отмеченные прочитанными уведомлениями снова становились непрочитанными
> Notifications minor fixes & PromiseKit refactoring

- Stepic/CourseListPresenter.swift
- Stepic/CourseListViewController.swift
- Stepic/ExplorePresenter.swift
- Stepic/ExploreViewController.swift
- Stepic/HomeScreenPresenter.swift
- Stepic/en.lproj/Localizable.strings
- Stepic/ru.lproj/Localizable.strings
**Описание**:
- Фиксы для пустых состояний в Explore и для списков курсов (вылезающие артефакты на черном фоне)
- Добавили Popular в Explore
- Убрали лимиты в горизонтальной карусели (работает даже с пагинацией)
- Теперь для popular запрашиваем все курсы, а не только featured
> Explore fixes

- Stepic/AnalyticsEvents.swift
- Stepic/NotificationsPresenter.swift
- Stepic/NotificationsViewController.swift
Добавили аналитику для уведомлений
**Описание**:
События:
* `notifications_mark_all_as_read` – нажатие на кнопку "Отметить прочитанными все", параметр `badge` – значение бейджа (= кол-во непрочитанных)
* `notifications_mark_as_read` – отметка уведомления прочитанным, параметр `action` – в зависимости от того, открыли уведомление (`link`) или нажали на кнопку с конвертом (`button`)
> Notifications analytics

- Stepic/CodeQuizViewController.swift
- Stepic/FullscreenCodeQuizViewController.swift
**Задача**: [#APPS-1711](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1711)
Теперь можно переключить клавиатуру на локальный язык
**Описание**:
Раньше для фикса проблемы с автоматической автокоррекцией для `UITextView` в код квизе был переделан `UIKeyboardType` на `.asciiCapable` [#117](https://github.com/StepicOrg/stepik-ios/pull/117).
Сейчас для iOS 11 просто ставим `smartQuotesType = .no`.
> Fixed Code Quiz smart quotes

- Stepic/NotificationsAPI.swift
- Stepic/StepsControllerDeepLinkRouter.swift
**Задача**: [#APPS-1718](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1718)
Исправлен краш при открытии степа по диплинку
**Описание**:
Вызов `reject(NSError())` приводил к крашу. Исправлено дефолтное значение после миграции (0, а не -1).
> Fix deeplinks crash

- Stepic/AnalyticsEvents.swift
- Stepic/AuthInfo.swift
- Stepic/DevicesAPI.swift
- Stepic/NotificationRegistrator.swift
Исправление проблемы с сохраненным deviceId
**Описание**:
Из-за того, что в версиях до 1.49 не удалялся сохраненный deviceId возможна ситуация, когда после обновления при каждой попытке регистрации устройства получали not found. 
Теперь если получили not found, пробуем зарегистрировать устройство. 
Также добавлен рефреш токена, без него невозможен `retrieve` и `create` в ситуации с протухшим токеном.
> Fix issue with deviceId

- Stepic/WebControllerManager.swift
**Задача**: [#APPS-1707](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1707)
Исправили краш при открытии ссылок с некоторыми схемами
**Описание**:
Открываем с помощью WebViewController/SFSafariViewController только ссылки с протоколами http и https.
> Fix url scheme crash

- Stepic/AnalyticsEvents.swift
- Stepic/AuthInfo.swift
**Задача**: [#APPS-1725](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1725)
Вероятно, исправлен самый популярный краш
**Описание**:
Убрал реквест в init-е для AuthInfo. Надеюсь, это все исправит. Если нет - будем искать дальше. Краш этот воспроизвести так ни разу и не удалось.
> AuthInit crash fix

- Stepic.xcodeproj/xcuserdata/Ostrenkiy.xcuserdatad/xcschemes/xcschememanagement.plist
- Stepic/CurrentBestStreakViewController.swift
- Stepic/NotificationPreferencesContainer.swift
- Stepic/ProfilePresenter.swift
- Stepic/StreaksAlertPresentationManager.swift
**Задача**: [#APPS-1737](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1737)
Исправили краш в пикере времени стрика для отрицательных таймзон
**Описание**:
[Краш](https://fabric.io/alexander-karpovs-projects3/ios/apps/com.alexkarpov.stepic/issues/59a95c6abe077a4dccf38cc9?time=last-twenty-four-hours) возникал, если выбрать время в отрицательной таймзоне. Проверить это можно поменяв таймзону на маке на какое-нибудь американское время, а потом нажав на кнопку выбора времени стрика. 
Также исправлена ошибка, когда неверно для отрицательных таймзон отображалось время обновления стриков внутри локального часового пояса под свитчем в профиле.
> Fixed time picker crash

- Stepic/CardStepViewController.swift
**Задача**: [#APPS-1780](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1780)
Исправили краш при сохранении изображения в адаптивном степе
**Описание**:
Из-за того, что используется WKWebView вместо UIWebView, доступен callout. При попытке сохранения на устройство – краш из-за недостатка прав.
Решение: исполнить js код c ```document.documentElement.style.webkitTouchCallout='none'```
> Fixed crash in adaptive images callout

- Stepic/MatchingQuizViewController.swift
**Задача**: [#APPS-1781](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1781)
Исправлена ошибка с перезагрузкой высоты matching квиза
**Описание**:
Не всегда применялись апдейты высоты. Теперь всегда.
> Fixed matching height reload bug

- Stepic/DiscussionsStoryboard.storyboard
- Stepic/WriteCommentViewController.swift
**Задача**: [#APPS-1776](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1776)
Исправили баг, когда лейаут при написании комментария уезжал наверх и никогда не возвращался
**Описание**:
Добавил `UIScrollView` под текствьюшку, чтобы все работало хорошо. Проблема была в `IQKeyboardManager`, который двигал вверх от клавиатуры всю вьюшку вместе с navigation-ом, а потом забывал ее возвращать.
> Write discussion layout fix

- Stepic/CardsStepsViewController.swift
Фикс поведения статус бара в адаптивном режиме
**Описание**:
В некоторых случаях прогресс бар мог некорректно обновляться из-за того, что к прогрессу прибавляется константа для лучшего отображения.
> Fixed adaptive progress bar update

- Stepic/CardStepViewController.swift
- Stepic/CourseListPresenter.swift
**Задача**: [#APPS-1782](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1782)
Исправили https://fabric.io/alexander-karpovs-projects3/ios/apps/com.alexkarpov.stepic/issues/5a70728d8cb3c2fa63eaee19?time=last-ninety-days
**Описание**:
Воспроизвести баг получилось следующим образом:
* Зарегистрировать новый аккаунт
* Записаться на курс
* Отписаться от него
* Краш
Такое получалось из-за того, что при изменении стейта на `.empty` и, соответственно,  `reloadData()`, мы пытаемся еще раз анимировать изменения, что приводит к ошибке.
> Fixed CourseList crash on deleting the only course

- Stepic/DeepLinkRouter.swift
**Задача**: [#APPS-1765](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1765)
Обновление deeplink для catalog и notifications.
**Описание**:
Обновили диплинки для catalog и notifications. Паша обновит `apple-app-site-association` 1 марта, когда релиз будет у большинства пользователей. Без `delay` не работает, так как контроллеры во время `didFinishLaunching` еще не проинициализированы.
> Deep Links for catalog and notifications

- Stepic/OnboardingViewController.swift
**Задача**: [#APPS-1794](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1794)
**Описание**:
После нажатия на кнопку Next в последнем контроллере онбординга дисмиссим онбординг и презентуем Auth.
> Auth after onboarding

- Stepic.xcodeproj/project.pbxproj
**Описание**:
Исправлены падающие из-за закешированных данных тесты – в таргет `StepicTests` добавлен этап с удалением приложения с BundleId `com.AlexKarpov.Stepic` с запущенного симулятора.
> Remove app from simulator before tests

- Stepic/DiscussionsViewController.swift
- Stepic/VideoStepViewController.swift
**Задача**: [#APPS-1838](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1838)
Исправили краш при написании комментария
**Описание**:
Исправлен краш после отправки комментария в адаптивных степах и степах с видео. Кроме того, в степах с видео теперь обновляется счетчик комментариев по `viewWillAppear`.
> Fix crash in discussions

- .gitignore
- Stepic.xcodeproj/project.pbxproj
- Stepic/CourseListPresenter.swift
- Stepic/CourseListViewData.swift
- Stepic/ExplorePresenter.swift
- Stepic/HomeScreenPresenter.swift
- Stepic/SearchResultsPresenter.swift
- Stepic/StepikTableView.swift
**Задача**: [#APPS-1835](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1835)
**Коротко для Release Notes, в формате «Сделали/Добавили/Исправили N»**:
Исправили отображение курсов в кешированных списках
**Описание**:
Из-за того, что в `CourseListPresenter` обновляем кеш в блоке `didSet`, кеш перезатирался на пустой. Теперь обновляем его вручную и только тогда, когда данные в памяти актуальнее, чем кешированные.
> Fix cached course lists

- Stepic.xcodeproj/project.pbxproj
- Stepic/AppDelegate.swift
- Stepic/Info.plist
- StepicAdaptiveCourse/Content/1838/AdaptiveInfo.plist
- StepicAdaptiveCourse/Content/3124/AdaptiveInfo.plist
- StepicAdaptiveCourse/Content/3149/AdaptiveInfo.plist
- StepicAdaptiveCourse/Content/3150/AdaptiveInfo.plist
- StepicTests/Info.plist
- StepicWatch Extension/Info.plist
- StepicWatch/Info.plist
- StepikTV/Info.plist
- StepikTVTests/Info.plist
- StickerPackExtension/Info.plist
- UITests/Screenshots/Info.plist
- fastlane/Fastfile
- Фикс краша при логине через соцсети
- Апдейт fastlane до 2.93.1
> Fixed crash in AppDelegate & updated fastlane to 2.93.1

- Stepic/CourseListPresenter.swift
- Stepic/CoursePreviewViewController.swift
- Stepic/CourseSubscriber.swift
- Stepic/LastStepRouter.swift
- Stepic/SectionsAPI.swift
**Задача**: [#APPS-1871](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1871)
Добавили переход к последнему пройденному шагу после записи на курс
**Описание**:
Вместо презентации секций используем везде после записи LastStepRouter. На странице "о курсе" теперь используется CourseSubscriber.
> Last step redirect after join a course

- Stepic/NSDateExtensions.swift
- Stepic/Parser.swift
**Задача**: [#APPS-1927](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1927)
Исправили конвертацию в time string и обратно
**Описание**:
Теперь не учитывается пользовательская локаль, в конструктор TimeInterval добавлен формат с AM/PM для обработки неверных существующих дат.
> Fix Date to timeString conversion 

- Stepic/AppDelegate.swift
- Stepic/CardStepPresenter.swift
**Задача**: [#APPS-1947](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1947)
Исправили неправильные события в amplitude
**Описание**:
- Теперь отсылается событие `Step opened` для адаптивных шагов
- Также отправляется `Session start` во время первого запуска
> Amplitude fixes

- Stepic/Scripts.plist
- Stepic/Scripts.swift
- Stepic/SortingQuizViewController.swift
- Stepic/StepikPlaceholderView.swift
- Stepic/WebStepViewController.swift
**Задача**: [#APPS-1952](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1952)
**Описание**:
Добавил скрипт для парсинга Kotlin runnable samples
> Added kotlin runnable samples

- Stepic/FillBlanksQuizViewController.swift
**Задача**: [#APPS-1924](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1924)
**Описание**:
Делаем `tableView.invalidateIntrinsicContentSize()` после `tableView.reloadData()`, чтобы лишний раз пересчиталась высота таблицы. Теперь все работает хорошо.
> Fill blanks bug

- Stepic/Config.plist
**Описание**:
Добавил ключ `appId` в `Stepic`. 
`StepicApplicationsInfo.appId` возвращал пустую строку для схемы Stepic.
> Fix CongratulationViewController share URL

- Podfile
- Stepic.xcodeproj/project.pbxproj
- Stepic/Downloader.swift
- Stepic/DownloaderProtocol.swift
- Stepic/DownloaderTask.swift
- Stepic/DownloaderTaskProtocol.swift
- Stepic/RestorableBackgroundDownloaderProtocol.swift
- StepicTests/DownloaderTests.swift
**Задача**: [#APPS-1958](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1958)
Переписан загрузчик файлов
**Описание**:
`DownloaderTaskProtocol` – обертка, через которую осуществляется работа с загрузками внутри загрузчика, без взаимодействия с сетевым слоем. Базовая реализация `DownloaderTask` (от которой планируется наследовать задачи для загрузки видео и прочего контента) не содержит сложной логики и является прокси для загрузчика.
Задача в загрузчике может находиться в следующих состояниях:
+    attached – для задачи задан загрузчик для исполнения
+    detached – для задачи не задан загрузчик для исполнения. Данное состояние задача имеет, например, сразу после инициализации, либо после отмены загрузки 
+ …
> New file downloader

- Stepic/AmplitudeAnalyticsEvents.swift
- Stepic/DiscussionTableViewCell.swift
- Stepic/DiscussionTableViewCell.xib
**Задача**: [#APPS-1976](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1976)
**Описание**:
Фиксы стилей для дискуссий. Убрали ненужный контейнер вью.
> Fixed discussion styles

- Stepic/DownloaderTask.swift
- Stepic/VideoDownloaderTask.swift
**Задача**: [#APPS-1996](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1996)
**Описание**:
Исправили краш из-за переполнения инта на 32-битных устройствах.
> Fix downloads crash on 32-bit devices

- Stepic/AmplitudeAnalyticsEvents.swift
- Stepic/Modules/ContinueCourse/ContinueCourseViewController.swift
- Stepic/Modules/ContinueCourse/View/ContinueCourseView.swift
**Описание**:
Здесь два фикса:
* Пофиксили название события для нажатия кнопки в истории
* Пофиксили багу, когда при открытии домашней страницы новым пользователем тултип уезжал куда-то в левый верхний угол
> Minor fixes

- Stepic/AppDelegate.swift
**Описание**:
Установка `push_permission` в `not_determined` при первом запуске.
> Report not determined push permission status before launch first time

- Stepic/SectionsViewController.swift
- Stepic/UnitsViewController.swift
**Задача**: [#APPS-2133](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2133)
**Описание**:
Исправили просмотр контента при отсутствии интернет соединения для секций и юнитов.
> Fix sections & units offline viewing

- Stepic.xcodeproj/project.pbxproj
- Stepic/LessonPresenter.swift
- Stepic/LessonViewController.swift
- Stepic/Modules/CourseInfo/CourseInfoDataFlow.swift
- Stepic/Modules/CourseInfo/CourseInfoInteractor.swift
- Stepic/Modules/CourseInfo/CourseInfoPresenter.swift
- Stepic/Modules/CourseInfo/CourseInfoViewController.swift
- Stepic/Modules/CourseInfoTabInfo/Provider/SectionsNetworkService.swift
- Stepic/Modules/CourseInfoTabInfo/Provider/SectionsPersistenceService.swift
- Stepic/Modules/CourseInfoTabInfo/Provider/UnitsNetworkService.swift
- Stepic/Modules/CourseInfoTabInfo/Provider/UnitsPersistenceService.swift
- Stepic/Modules/CourseInfoTabSyllabus/CourseInfoTabSyllabusInteractor.swift
- Stepic/Modules/CourseInfoTabSyllabus/CourseInfoTabSyllabusOutputProtocol.swift
- Stepic/Services/UnitNavigationService.swift
- Stepic/VideoStepViewController.swift
- Stepic/WebStepViewController.swift
**Задача**: [#APPS-2206](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2206)
**Описание**:
Переходить между юнитами можно теперь всегда, когда урок открыт в контексте unit, а не только при переходе из силлабуса.
> Improved unit navigation

- Stepic/Sources/Controllers/StyledNavigationController.swift
- Stepic/Sources/Modules/CourseInfo/CourseInfoViewController.swift
**Описание**:
Во `viewWillAppear` сбрасывались настройки внешнего вида – воспроизводилось, например, при переключении табов.
> Fix navigation bar appearance

- Stepic/Sources/Modules/ExploreSubmodules/ContinueCourse/ContinueCoursePresenter.swift
**Задача**: [#APPS-2312](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2312)
**Описание**:
Прогресс на виджете "Продолжить" округляется так же, как и в виджетах с курсом.
> Fix "continue course" widget progress

- Stepic/DiscussionAlertConstructor.swift
- Stepic/Extensions/URL+AppendQueryParameters.swift
**Задача**: [#2339](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2339)
**Описание**:
Исправили двойную конвертацию URL строки в комментариях к уроку.
> Check for existing percent escapes first to prevent double-escaping

- Stepic/DiscussionsViewController.swift
**Задача**: [#APPS-2346](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2346)
**Описание**:
Добавили сортировку комментариев в дискуссии:
- На первом уровне – от новых к старым
- На втором уровне – от старых к новым
> Sort discussion comments

- Stepic.xcodeproj/project.pbxproj
- Stepic/AuthInfo.swift
- Stepic/Base.lproj/Main.storyboard
- Stepic/CertificateTableViewCell.swift
- Stepic/CertificatesPresenter.swift
- Stepic/CertificatesStoryboard.storyboard
- Stepic/CertificatesView.swift
- Stepic/CertificatesViewController.swift
- Stepic/Config.plist
- Stepic/Model.xcdatamodeld/.xccurrentversion
- Stepic/Model.xcdatamodeld/Model_user_ is_organization.xcdatamodel/contents
- Stepic/Profile.storyboard
- Stepic/ProfileMenuBlock.swift
- Stepic/ProfilePresenter.swift
- Stepic/ProfileViewController.swift
- Stepic/QuizPresenter.swift
- Stepic/StepikPlaceholderStyle+Placeholders.swift
- Stepic/StyledTabBarViewController.swift
- Stepic/User+CoreDataProperties.swift
- Stepic/User.swift
- Stepic/Utils/UIImageView+SVGDownload.swift
- Stepic/VideosInfo.swift
**Задача**: [#APPS-2389](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2389)
**Описание**:
Вынесли сертификаты из таб бара в профиль.
> Show certificates in profile

- Stepic/Sources/Modules/NewLesson/NewLessonDataFlow.swift
- Stepic/Sources/Modules/NewLesson/NewLessonInteractor.swift
- Stepic/Sources/Modules/NewLesson/NewLessonPresenter.swift
- Stepic/Sources/Modules/NewLesson/NewLessonViewController.swift
**Задача**: [#APPS-2424](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2424)
**Описание**:
Исправили краш на экране урока, при навигировании на следующий/предыдущий урок, выполняемый одновременно с скроллом табов, в следствии чего возникало обращение к несуществующему индексу.
> Fix crash on lesson navigation

- Stepic.xcodeproj/project.pbxproj
- Stepic/Info.plist
- Stepic/ModalOrPushStackRouter.swift
- Stepic/Scripts.swift
- Stepic/Sources/Frameworks/ContentProcessor/ContentProcessor.swift
- Stepic/Sources/Modules/Quizzes/NewChoiceQuiz/NewChoiceQuizView.swift
- StepicTests/Info.plist
- StickerPackExtension/Info.plist
**Описание**:
- Откатили использование KaTeX для рендеринга математических формул, т.к. высота веб-вью на iOS 13 считается неверно, это происходит при добавление необходимого для работы KaTeX `<!DOCTYPE html>` тега.
- Пофиксили краш при попытке открыть неподдерживаемый тип URL в веб-контроллер.
- Пофиксили краш в новом choice квизе при несбалансированном входе и выходе из `DispatchGroup`.
> Hotfix web view content height

- Podfile
- Podfile.lock
- Fix the case even when Animated Image View is not visible, user call `startAnimating` can still do animation [#2888](https://github.com/SDWebImage/SDWebImage/pull/2888)
> Update SDWebImage from 5.3.0 to 5.3.1

- Podfile
- Podfile.lock
Update Firebase iOS SDK to v6.13.0. For more details, see the [Firebase iOS SDK release notes.](https://firebase.google.com/support/release-notes/ios#6.13.0)
> Update Firebase from 6.12.0 to 6.13.0

- Podfile
- Podfile.lock
- Fix animated image playback bugs that cause rendering frame is the previous frame index [#2895](https://github.com/SDWebImage/SDWebImage/pull/2895).
- Update all pods.
> Update SDWebImage from 5.3.1 to 5.3.2

- Stepic/Sources/Frameworks/ContentProcessor/ProcessedContentTextView.swift
**Задача**: [#APPS-2546](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2546)
**Описание**:
Включили скроллинг для широкого HTML контента.
> Auto-scrolling for wide HTML content

- Podfile.lock
- Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/Provider/SyllabusDownloadsService.swift
**Задача**: [#APPS-2551](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2551)
**Описание**:
Текстовые шаги считаются как загружаемый контент, т.е. для текстовых уроков/модулей/курсов теперь отображается закэшированный статус, когда они скачаны и их также можно удалять, как и шаги с видео.
> Text steps as downloadable content

- Stepic.xcodeproj/project.pbxproj
- Stepic/Sources/Helpers/FormatterHelper.swift
- Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/CourseInfoTabSyllabusAssembly.swift
- Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/CourseInfoTabSyllabusDataFlow.swift
- Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/CourseInfoTabSyllabusInteractor.swift
- Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/Provider/SyllabusDownloadsService.swift
- Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/Views/Cell/CourseInfoTabSyllabusCellView.swift
- Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/Views/Section/CourseInfoTabSyllabusSectionView.swift
- Stepic/Sources/Modules/Downloads/DownloadsAssembly.swift
- Stepic/Sources/Modules/Downloads/DownloadsDataFlow.swift
- Stepic/Sources/Modules/Downloads/DownloadsInteractor.swift
- Stepic/Sources/Modules/Downloads/DownloadsPresenter.swift
- Stepic/Sources/Modules/Downloads/DownloadsProvider.swift
- Stepic/Sources/Services/StorageUsageService.swift
- StepicTests/NewStepTests/NewStepViewControllerMock.swift
**Задача**: [#APPS-2552](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2552)
**Описание**:
Добавили отображение размера скачанных файлов.
> Display downloaded content size in syllabus

- Podfile
- Podfile.lock
- Fix the crash when using NSCache delegate with SDMemoryCache default implementation on dealloc [#2899](https://github.com/SDWebImage/SDWebImage/pull/2899).
> Update SDWebImage from 5.3.2 to 5.3.3

- Podfile
- Podfile.lock
<h1><a href="https://github.com/SDWebImage/SDWebImage/releases/tag/5.4.0">5.4.0 Extended Cache Metadata</a></h1><p style="font-size:small;-webkit-text-size-adjust:none;">Repository: <a href="https://github.com/SDWebImage/SDWebImage">SDWebImage/SDWebImage</a> &middot; Tag: <a href="https://github.com/SDWebImage/SDWebImage/tree/5.4.0">5.4.0</a> &middot; Commit: <a href="https://github.com/SDWebImage/SDWebImage/commit/7ef9a314b12c1a31edb0d09d41fcba93143fe772">7ef9a31</a> &middot; </p>
> Update SDWebImage from 5.3.3 to 5.4.0

- Stepic/Sources/Views/DownloadControlView.swift
**Задача**: [#APPS-2587](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2587)
**Описание**:
Исправили 'зависание' анимации вращения кнопки скачивания.
> Fix DownloadControlView circle rotation animation freezes

- Stepic/Sources/Modules/Discussions/DiscussionsPresenter.swift
- Stepic/Sources/Modules/Discussions/DiscussionsViewController.swift
- Stepic/Sources/Modules/Discussions/DiscussionsViewModel.swift
**Задача**: [#APPS-2558](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2558)
**Описание**:
Заменили копирование сырого HTML текста на распарсенный.
> Copy stripped text out of HTML in discussions 

- Stepic/Sources/Modules/Quizzes/NewCodeQuiz/Views/CodeEditor/CodeEditorView.swift
- Stepic/Sources/Modules/Quizzes/NewCodeQuizFullscreen/Tabs/Instruction/NewCodeQuizFullscreenInstructionView.swift
- Stepic/Sources/Modules/Quizzes/NewCodeQuizFullscreen/Tabs/NewCodeQuizFullscreenCodeViewController.swift
**Задача**: [#APPS-2585](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2585)
**Описание**:
Исправили отображение названия языка программирования в полноэкранном код квизе.
> Fix code badge not being visible in fullscreen code quiz

- Stepic/RetentionLocalNotificationProvider.swift
**Задача**: [#APPS-2520](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2520)
**Описание**:
Исправили планирование возвращающих уведомлений. Час возникновения теперь находится в промежутке 12.00...19.00.
> Fix retention notifications fire date

- fastlane/Fastfile
Bumps [fastlane](https://github.com/fastlane/fastlane) minimum requirement version from 2.134.0 to 2.137.0.
> Bump fastlane minimum requirement version from 2.134.0 to 2.137.0

- Stepic/Sources/Modules/Quizzes/NewMatchingQuiz/NewMatchingQuizPresenter.swift
- Stepic/Sources/Modules/Quizzes/NewSortingQuiz/NewSortingQuizPresenter.swift
**YouTrack task**: [#APPS-2629](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2629)
- Disable HTML tags escaping for matching and sorting quizzes.
> Disable HTML tags escaping for matching and sorting

- Podfile
- Podfile.lock
Bumps:
- [SDWebImage](https://github.com/SDWebImage/SDWebImage) from 5.5.1 to 5.5.2
- [Agrume](https://github.com/JanGorman/Agrume) from 5.6.0 to 5.6.1
> Update dependencies 1.111

- Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/CourseInfoTabSyllabusInteractor.swift
- Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/Views/CourseInfoTabSyllabusTableViewDataSource.swift
**YouTrack task**: [#APPS-2606](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2606)
Previously when syllabus content displayed from the cache, next it was replaced by placeholders. Now it updates content in the background.
> Fetch sections in syllabus silently

- Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/Views/Section/CourseInfoTabSyllabusSectionView.swift
**YouTrack task**: [#APPS-2607](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2607)
- Displays disabled sections in the syllabus more friendly - dims all views except the requirements label.
> Visualize section enabled appearance

- Stepic/AppDelegate.swift
**YouTrack task**: [#APPS-2716](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2716)
- Fixes an issue when webview opened after successful external auth through VK app.
> Fix VK iOS SDK opens webview after success external auth

- Stepic.xcodeproj/project.pbxproj
- Stepic/Legacy/Model/Managers/WebControllerManager.swift
- Stepic/Sources/Helpers/HTMLToAttributedStringConverter.swift
- Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabInfo/CourseInfoTabInfoViewController.swift
- Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabInfo/Views/Blocks/CourseInfoTabInfoTextBlockView.swift
- Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabInfo/Views/CourseInfoTabInfoView.swift
**YouTrack task**: [#APPS-2858](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2858)
- Links highlighting in the course info tab.
> Course info tab info highlight links

- Stepic/Legacy/Model/Network/Endpoints/CourseListsAPI.swift
- Stepic/Legacy/Model/RemoteConfig/RemoteConfig.swift
- Stepic/Sources/Modules/ExploreSubmodules/CourseListsCollection/CourseListsCollectionAssembly.swift
- Stepic/Sources/Modules/ExploreSubmodules/CourseListsCollection/CourseListsCollectionInteractor.swift
**YouTrack task**: [#APPS-2902](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2902)
- Updates `CourseListsAPI` `platform` query parameter from `mobile` to `mobile,ios`.
- Removes `RemoteConfig.hiddenCourseListsIDs`.
> Support mobile & iOS platform in course-lists API

- Stepic.xcodeproj/project.pbxproj
- Stepic/Legacy/Analytics/Events/AmplitudeAnalyticsEvents.swift
- Stepic/Legacy/Model/Entities/User/User+CoreDataProperties.swift
- Stepic/Legacy/Model/Model.xcdatamodeld/.xccurrentversion
- Stepic/Legacy/Model/Model.xcdatamodeld/Model_new_profile_created_courses_v56.xcdatamodel/contents
- Stepic/Legacy/Model/Network/Endpoints/CoursesAPI.swift
- Stepic/Sources/Modules/CourseList/Provider/CourseListNetworkService.swift
- Stepic/Sources/Modules/CourseList/Provider/CourseListPersistenceStorage.swift
- Stepic/Sources/Modules/CourseList/Provider/CourseListTypes.swift
- Stepic/Sources/Modules/CourseList/Views/CourseListColorMode.swift
- Stepic/Sources/Modules/CourseList/Views/CourseListView.swift
- Stepic/Sources/Modules/CourseList/Views/Layouts/HorizontalCourseListFlowLayout.swift
- Stepic/Sources/Modules/CourseList/Views/Widget/CourseWidgetView.swift
- Stepic/Sources/Modules/NewProfile/NewProfileDataFlow.swift
- Stepic/Sources/Modules/NewProfile/NewProfileInteractor.swift
- Stepic/Sources/Modules/NewProfile/NewProfileViewController.swift
- Stepic/Sources/Modules/NewProfile/Views/Block/NewProfileBlockContainerView.swift
- Stepic/Sources/Modules/NewProfileSubmodules/CreatedCourses/InputOutput/NewProfileCreatedCoursesOutputProtocol.swift
- Stepic/Sources/Modules/NewProfileSubmodules/CreatedCourses/NewProfileCreatedCoursesAssembly.swift
- Stepic/Sources/Modules/NewProfileSubmodules/CreatedCourses/NewProfileCreatedCoursesDataFlow.swift
- Stepic/Sources/Modules/NewProfileSubmodules/CreatedCourses/NewProfileCreatedCoursesInteractor.swift
- Stepic/Sources/Modules/NewProfileSubmodules/CreatedCourses/NewProfileCreatedCoursesPresenter.swift
- Stepic/Sources/Modules/NewProfileSubmodules/CreatedCourses/NewProfileCreatedCoursesProvider.swift
- Stepic/Sources/Modules/NewProfileSubmodules/CreatedCourses/NewProfileCreatedCoursesView.swift
- Stepic/Sources/Modules/NewProfileSubmodules/CreatedCourses/NewProfileCreatedCoursesViewController.swift
- Stepic/en.lproj/Localizable.strings
- Stepic/ru.lproj/Localizable.strings
**YouTrack task**: [#APPS-2779](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2779)
- Adds courses block to the new profile.
> New profile block created courses

- Stepic/Legacy/Model/ExecutionQueue/Executable.swift
- Stepic/Legacy/Model/ExecutionQueue/TasksSerializers/DeleteDevice/DeleteDeviceExecutableTask.swift
- Stepic/Legacy/Model/ExecutionQueue/TasksSerializers/Views/PostViewsExecutableTask.swift
- Stepic/Legacy/Model/Network/Endpoints/DevicesAPI.swift
**YouTrack task**: [#APPS-2954](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2954)
- Fixes crash in `DevicesAPI.delete(,headers:, success:, error:)`.
> Fix delete device catch handler dynamic cast crash

- Stepic.xcodeproj/project.pbxproj
- Stepic/Legacy/Controllers/Placeholders/ControllerWithStepikPlaceholder.swift
- Stepic/Legacy/Controllers/Placeholders/StepikPlaceholderView/StepikPlaceholderView.swift
- Stepic/Legacy/Views/Skeleton/Views/Profile/NewProfileHeaderViewSkeleton.swift
- Stepic/Sources/Extensions/SwiftStdlib/String+Whitespaces.swift
- Stepic/Sources/Frameworks/ContentProcessor/ContentProcessingRule.swift
- Stepic/Sources/Modules/CourseList/Views/CourseListColorMode.swift
- Stepic/Sources/Modules/CourseList/Views/CourseListView.swift
- Stepic/Sources/Modules/CourseList/Views/Widget/CourseWidgetView.swift
- Stepic/Sources/Modules/NewProfile/NewProfileInteractor.swift
- Stepic/Sources/Modules/NewProfile/NewProfileViewController.swift
- Stepic/Sources/Modules/NewProfile/NewProfileViewModel.swift
- Stepic/Sources/Modules/NewProfile/Views/NewProfileView.swift
- Stepic/Sources/Modules/NewProfileSubmodules/Achievements/NewProfileAchievementsInteractor.swift
- Stepic/Sources/Modules/NewProfileSubmodules/CreatedCourses/NewProfileCreatedCoursesViewController.swift
- Stepic/Sources/Modules/NewProfileSubmodules/Details/NewProfileDetailsView.swift
- Stepic/Sources/Modules/NewProfileSubmodules/SocialProfiles/NewProfileSocialProfilesInteractor.swift
- Stepic/Sources/Modules/NewProfileSubmodules/SocialProfiles/NewProfileSocialProfilesViewController.swift
**YouTrack task**: [#APPS-2952](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2952)
- Adds fixes for the new profile module.
> New profile fixes

- Stepic.xcodeproj/project.pbxproj
- Stepic/Legacy/Analytics/Events/StepikAnalyticsEvents.swift
- Stepic/Sources/Frameworks/Analytics/AnalyticsEngine.swift
- Stepic/Sources/Modules/CourseList/Views/CourseListCollectionViewDataSource.swift
- Stepic/Sources/Modules/CourseList/Views/CourseListCollectionViewDelegate.swift
- Stepic/Sources/Modules/Downloads/DownloadsViewController.swift
- Stepic/Sources/Modules/Downloads/Views/DownloadsTableViewDataSource.swift
**YouTrack task**: [#APPS-2972](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2972)
- Sends `CatalogDisplay ` and `CatalogClick` events to metrics.
> Send course cards analytics to metrics

- Stepic.xcodeproj/project.pbxproj
- Stepic/Legacy/Model/Entities/Profile/Profile+CoreDataProperties.swift
- Stepic/Legacy/Model/Entities/Profile/Profile.swift
- Stepic/Legacy/Model/Model.xcdatamodeld/.xccurrentversion
- Stepic/Legacy/Model/Model.xcdatamodeld/Model_is_vote_notifications_enabled_v60.xcdatamodel/contents
**YouTrack task**: [#APPS-2980](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2980)
- Persists and parses`is_vote_notifications_enabled` attribute.
- Sends `is_vote_notifications_enabled` on profile update API request.
> Fix send is_vote_notifications_enabled on profile update

- Stepic.xcodeproj/project.pbxproj
- Stepic/Legacy/Model/Entities/Assignment/Assignment+CoreDataProperties.swift
- Stepic/Legacy/Model/Entities/Assignment/Assignment.swift
- Stepic/Legacy/Model/Entities/Progress/Progress+CoreDataProperties.swift
- Stepic/Legacy/Model/Entities/Progress/Progress.swift
- Stepic/Legacy/Model/Model.xcdatamodeld/.xccurrentversion
- Stepic/Legacy/Model/Model.xcdatamodeld/Model_assignment_progress_id_v64.xcdatamodel/contents
- Stepic/Sources/Helpers/FormatterHelper.swift
- Stepic/Sources/Modules/CourseInfo/CourseInfoPresenter.swift
- Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/CourseInfoTabSyllabusPresenter.swift
- Stepic/Sources/Modules/CourseList/CourseListPresenter.swift
- Stepic/Sources/Modules/ExploreSubmodules/ContinueCourse/ContinueCoursePresenter.swift
- Stepic/Sources/Modules/Lesson/LessonPresenter.swift
**YouTrack task**: [#APPS-2601](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2601)
- Changes `Progress.managedScore` attribute type from `Integer 64` -> `Float`
- Updates `score/cost` formatting.
> Fix an incorrect number of points for steps with discounting policy

- Stepic/Legacy/Analytics/Events/AmplitudeAnalyticsEvents.swift
- Stepic/Legacy/Controllers/Notifications/Helpers/NotificationReactionHandler.swift
- Stepic/Legacy/Services/DeepLinks/DeepLinkRoute.swift
- Stepic/Legacy/Services/DeepLinks/DeepLinkRoutingService.swift
- StepicTests/DeepLinkRouteTests.swift
**YouTrack task**: [#APPS-2453](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2453)
- Adds `DeepLinkRoute.certificates(userID:)` case.
- `DeepLinkRoutingService` supports routing to certificates.
- Route to certificates screen on notification receive.
> Certificates deep link

- Stepic/Legacy/AppDelegate.swift
**YouTrack task**: [#APPS-2831](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2831)
- Clears `applicationIconBadgeNumber` when user unauthorized.
> Fix application icon badge number

- Podfile
- Podfile.lock
- Stepic/Legacy/Controllers/PersonalDeadlines/PersonalDeadlineEditScheduleViewController.swift
**YouTrack task**: [#APPS-3038](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3038)
- Bumps [ActionSheetPicker-3.0](https://github.com/skywinder/ActionSheetPicker-3.0) from 2.4.0 to 2.6.0.
- Uses `UIDatePickerStyle.wheels` for `PersonalDeadlineEditScheduleViewController`'s datePicker.
> iOS 14 support for ActionSheetDatePicker

- Stepic/Legacy/Controllers/VideoPlayer/Player.swift
- Stepic/Legacy/Controllers/VideoPlayer/StepikVideoPlayerViewController/StepikVideoPlayerViewController.swift
- Stepic/Legacy/Model/Entities/Video/Video.swift
- Stepic/Sources/Frameworks/Downloader/DownloadingService/VideoDownloadingService.swift
- Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/Provider/SyllabusDownloadsService.swift
- Stepic/en.lproj/Localizable.strings
- Stepic/ru.lproj/Localizable.strings
**YouTrack task**: [#APPS-3019](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3019)
- Fixes crash in `Video.getUrlForQuality(_:)` that invoked by`VideoDownloadingService.download(video:)` and `StepikVideoPlayerViewController.getInitialVideoQualityURL()`.
> Fix crash when video URLs is empty

- Podfile
- Podfile.lock
Bumps:
- [ActionSheetPicker-3.0](https://github.com/skywinder/ActionSheetPicker-3.0) from 2.6.0 to 2.6.1
- [Nimble](https://github.com/Quick/Nimble) from 9.0.0-rc.3 to 9.0.0
- [Firebase](https://github.com/firebase/firebase-ios-sdk) from 6.33.0 to 6.34.0
- [Kanna](https://github.com/tid-kijyun/Kanna) from 5.2.2 to 5.2.3
> Update dependencies 1.145

- Gemfile
- Gemfile.lock
- Podfile
- Podfile.lock
- Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabInfo/Views/Blocks/CourseInfoTabInfoHeaderBlockView.swift
- Stepic/Sources/Modules/Settings/SettingsViewController.swift
- fastlane/Fastfile
Bumps:
- [YandexMobileMetrica](https://github.com/yandexmobile/metrica-sdk-ios) from 3.11.1 to 3.12.0
- [SwiftLint](https://github.com/realm/SwiftLint) from 0.40.3 to 0.41.0
- [Firebase](https://github.com/firebase/firebase-ios-sdk) from 7.0.0 to 7.1.0
- [SDWebImage](https://github.com/SDWebImage/SDWebImage) from from 5.9.4 to 5.9.5
- [fastlane](https://github.com/fastlane/fastlane) from 2.166.0 to 2.167.0
- [Facebook SDK](https://github.com/facebook/facebook-ios-sdk) from 8.1.0 to 8.2.0
- [SwiftDate](https://github.com/malcommac/SwiftDate) from 6.2.0 to 6.3.0
- [Agrume](https://github.com/JanGorman/Agrume) from 5.6.10 to 5.6.11
- [Nuke](https://github.com/kean/Nuke) from 9.1.2 to 9.1.3
> Update dependencies 1.151

- Stepic/Sources/Modules/CourseList/Views/Widget/CourseWidgetView.swift
**YouTrack task**: [#APPS-3108](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3108)
- Fixes visible HTML tags in the summary label of `CourseWidgetView`.
> Fix HTML tags are visible in course widget summary label

- Gemfile
- Gemfile.lock
- Podfile
- Podfile.lock
- fastlane/Fastfile
Bumps:
- [fastlane](https://github.com/fastlane/fastlane) from 2.167.0 to 2.168.0
- [SwiftDate](https://github.com/malcommac/SwiftDate) from 6.3.0 to 6.3.1
- [SDWebImage](https://github.com/SDWebImage/SDWebImage) from from 5.9.5 to 5.10.0
> Update dependencies 1.152

- Gemfile
- Gemfile.lock
- Podfile
- Podfile.lock
- fastlane/Fastfile
Bumps:
- [Nuke](https://github.com/kean/Nuke) from 9.1.3 to 9.2.0
- [fastlane](https://github.com/fastlane/fastlane) from 2.168.0 to 2.169.0
> Update dependencies 1.153

- Stepic/Sources/Modules/Quizzes/BaseQuiz/BaseQuizViewController.swift
- Stepic/Sources/Modules/Quizzes/BaseQuiz/ChildProtocols/QuizInputProtocol.swift
- Stepic/Sources/Modules/Quizzes/NewChoiceQuiz/NewChoiceQuizInteractor.swift
- Stepic/en.lproj/Localizable.strings
- Stepic/ru.lproj/Localizable.strings
**YouTrack task**: [#APPS-3113](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3113)
- Adds replies validation logic before submitting.
> Fix choice quiz empty reply

- Stepic.xcodeproj/project.pbxproj
- Stepic/Sources/Extensions/Foundation/Collection+SafeSubscript.swift
- Stepic/Sources/Extensions/Foundation/CollectionExtensions.swift
- Stepic/Sources/Modules/CourseList/Provider/CourseListNetworkService.swift
**YouTrack task**: [#APPS-3090](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3090)
- Adds pagination for new catalog blocks & deep link course lists.
> New catalog course list pagination

- Gemfile
- Gemfile.lock
- Podfile
- Podfile.lock
- fastlane/Fastfile
Bumps:
- [Firebase](https://github.com/firebase/firebase-ios-sdk) from 7.1.0 to 7.3.0
- [fastlane](https://github.com/fastlane/fastlane) from 2.169.0 to 2.170.0
> Update dependencies 1.154

- Stepic/Sources/Modules/Quizzes/TableQuiz/TableQuizSelectColumns/TableQuizSelectColumnsViewController.swift
- Stepic/Sources/Modules/Quizzes/TableQuiz/TableQuizSelectColumns/Views/TableQuizSelectColumnsColumnView.swift
- Stepic/Sources/Modules/Quizzes/TableQuiz/TableQuizSelectColumns/Views/TableQuizSelectColumnsHeaderView.swift
- Stepic/Sources/Modules/Quizzes/TableQuiz/TableQuizSelectColumns/Views/TableQuizSelectColumnsView.swift
- Stepic/Sources/Views/ScrollableStackView.swift
**YouTrack task**: [#APPS-3110](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3110)
- Uses `ScrollableStackView` instead of plain `StackView` as a content view.
> Fix table quiz pan modal content size not fitting

- Stepic/Legacy/Services/Notifications/NotificationsService.swift
**YouTrack task**: [#APPS-3028](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3028)
- Fixes routing for local notifications on iOS 10 and above.
> Fix local notifications routing

- Stepic/Legacy/Model/Network/Endpoints/SearchResultsAPI.swift
- Stepic/Legacy/Model/RemoteConfig/RemoteConfig.swift
**YouTrack task**: [#APPS-3155](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3155)
- Adds config value `RemoteConfig.searchResultsQueryParams`.
- Updates SearchResultsAPI query params.
> RemoteConfig value for search-results query parameters

- Podfile
- Podfile.lock
Bumps:
- [Tabman](https://github.com/uias/Tabman) from 2.8.0 to 2.10.0
- [SDWebImage](https://github.com/SDWebImage/SDWebImage) from 5.10.2 to 5.10.3
- [YandexMobileMetrica](https://github.com/yandexmobile/metrica-sdk-ios) from 3.14.0 to 3.14.1
> Update dependencies 1.159

- Stepic/Legacy/TransitionRouters/LastStepRouter.swift
- Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/CourseInfoTabSyllabusInteractor.swift
**YouTrack task**: [#APPS-3026](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3026)
- Fixes an issue with that `CourseInfoTabSyllabus` always firstly display placeholders instead of units when course info opened from the continue learning action.
> Fix syllabus always displays units placeholders on continue learning

- Stepic/Sources/Modules/Quizzes/CodeQuizFullscreen/Tabs/CodeQuizFullscreenRunCode/CodeQuizFullscreenRunCodePresenter.swift
- Stepic/Sources/Modules/Quizzes/CodeQuizFullscreen/Tabs/CodeQuizFullscreenRunCode/CodeQuizFullscreenRunCodeView.swift
- Stepic/Sources/Modules/Quizzes/CodeQuizFullscreen/Tabs/CodeQuizFullscreenRunCode/CodeQuizFullscreenRunCodeViewModel.swift
**YouTrack task**: [#APPS-3163](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3163)
- Not displays success state of the user code run status when test output matches sample output.
> Not display success user code run status

- Stepic/Legacy/Model/Constants/Scripts/Scripts.plist
**YouTrack task**: [#APPS-3164](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3164)
- Fixes `clickableImages` script by preventing nested <a> tags.
> Fix LatexView clickable images script

- Podfile
- Podfile.lock
Bumps:
- [Branch](https://github.com/BranchMetrics/ios-branch-deep-linking-attribution) from 1.38.0 to 1.39.0
- [Amplitude](https://github.com/amplitude/Amplitude-iOS) from 7.3.0 to 8.0.0
- [Firebase](https://github.com/firebase/firebase-ios-sdk) from 7.7.0 to 7.8.0
> Update dependencies 1.165

- Podfile
- Podfile.lock
Bumps:
- [Firebase](https://github.com/firebase/firebase-ios-sdk) from 7.8.0 to 7.8.1
- [SwiftLint](https://github.com/realm/SwiftLint) from 0.43.0 to 0.43.1
- [Amplitude](https://github.com/amplitude/Amplitude-iOS) from 8.0.0 to 8.1.0
> Update dependencies 1.166

- Stepic/Sources/Modules/Settings/SettingsDataFlow.swift
- Stepic/Sources/Modules/Settings/SettingsInteractor.swift
- Stepic/Sources/Modules/Settings/SettingsPresenter.swift
- Stepic/Sources/Modules/Settings/SettingsViewController.swift
- Stepic/Sources/Modules/Settings/SettingsViewModel.swift
**YouTrack task**: [#APPS-3260](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3260)
- Shows `logOut` cell in settings only when the current user is authorized.
> Hide Log Out in settings when current user is unauthorized

- Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/Views/Cell/CourseInfoTabSyllabusCellStatsView.swift
**YouTrack task**: [#APPS-3259](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3259)
- Uses absolute value when formatting likes count text.
> Fix syllabus unit likes count text

- Podfile
- Podfile.lock
Bumps:
- [Amplitude](https://github.com/amplitude/Amplitude-iOS) from 8.1.0 to 8.2.1
- [Nuke](https://github.com/kean/Nuke) from 9.3.0 to 9.5.0
- [Branch](https://github.com/BranchMetrics/ios-branch-deep-linking-attribution) from 1.39.1 to 1.39.2
- [YandexMobileMetrica](https://github.com/yandexmobile/metrica-sdk-ios) from 3.14.1 to 3.15.0
- [SDWebImage](https://github.com/SDWebImage/SDWebImage) from 5.10.4 to 5.11.0
- [Alamofire](https://github.com/Alamofire/Alamofire) from 5.4.1 to 5.4.2
- [Agrume](https://github.com/JanGorman/Agrume) from 5.6.12 to 5.6.13
- [Firebase](https://github.com/firebase/firebase-ios-sdk) from 7.9.0 to 7.10.0
> Update dependencies 1.169

- Podfile
- Podfile.lock
Bumps:
- [YandexMobileMetrica](https://github.com/yandexmobile/metrica-sdk-ios) from 3.15.0 to 3.15.1
- [Firebase](https://github.com/firebase/firebase-ios-sdk) from 7.10.0 to 7.11.0
- [Alamofire](https://github.com/Alamofire/Alamofire) from 5.4.2 to 5.4.3
- [Highlightr](https://github.com/raspu/Highlightr) from 2.1.0 to 2.1.2
> Update dependencies 1.171

- Stepic/Legacy/Controllers/VideoPlayer/StepikVideoPlayerViewController/StepikVideoPlayerViewController.swift
**YouTrack task**: [#APPS-3277](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3277)
- Fixes video player no sound after comes from a background at a double fast rate.
> Fix video player no sound after comes from background at double fast rate

- Stepic.xcodeproj/project.pbxproj
- Stepic/Legacy/Model/Entities/Course/Course+CoreDataProperties.swift
- Stepic/Legacy/Model/Entities/Course/Course.swift
- Stepic/Legacy/Model/Model.xcdatamodeld/.xccurrentversion
- Stepic/Legacy/Model/Model.xcdatamodeld/Model_course_preview_unit_v79.xcdatamodel/contents
**YouTrack task**: [#APPS-3317](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3317)
- Updates `preview_lesson` parsing.
> New preview_lesson API

- Stepic/Sources/Controllers/StyledNavigationController.swift
- Stepic/Sources/Modules/Quizzes/CodeQuizFullscreen/CodeQuizFullscreenViewController.swift
- Stepic/Sources/Modules/Settings/SettingsViewController.swift
**YouTrack task**: [#APPS-3318](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3318)
- On iOS 14 uses `UINavigationItem.BackButtonDisplayMode.minimal` to show the back button indicator instead of the title.
> Fix back button menus with empty titles

- Podfile
- Podfile.lock
Bumps:
- [PromiseKit](https://github.com/mxcl/PromiseKit) from 6.13.1 to 6.15.3
- [Firebase](https://github.com/firebase/firebase-ios-sdk) from 8.0.0 to 8.1.1
> Update dependencies 1.177

- Stepic/Legacy/Analytics/Events/AmplitudeAnalyticsEvents.swift
- Stepic/Sources/Modules/CourseList/Interactor/CourseListDataBackUpdateService.swift
- Stepic/Sources/Modules/CourseList/Provider/CourseListNetworkService.swift
- Stepic/Sources/Modules/CourseList/Provider/CourseListPersistenceService.swift
- Stepic/Sources/Modules/CourseList/Provider/CourseListTypes.swift
- Stepic/Sources/Modules/Downloads/DownloadsProvider.swift
- Stepic/Sources/Modules/HomeSubmodules/UserCourses/UserCoursesAssembly.swift
- Stepic/Sources/Modules/HomeSubmodules/UserCourses/UserCoursesDataFlow.swift
- Stepic/Sources/Modules/HomeSubmodules/UserCourses/UserCoursesViewController.swift
- Stepic/en.lproj/Localizable.strings
- Stepic/ru.lproj/Localizable.strings
**YouTrack task**: [#APPS-3361](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3361)
- Adds `Downloaded` tab to user courses module.
> User courses tab downloaded

- Stepic/Sources/Modules/CourseRevenueSubmodules/CourseRevenueTabPurchases/Views/CourseRevenueTabPurchasesView.swift
**YouTrack task**: [#APPS-3384](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3384)
- Fixes course revenue header view offset on expanding content action.
> Fix course revenue header invalid content offset on expand content

- Stepic/Legacy/Controllers/RegistrationSignIn/AuthNavigationViewController.swift
- Stepic/Legacy/Model/Managers/StreaksAlertPresentationManager.swift
- Stepic/Sources/Modules/NewProfileSubmodules/StreakNotifications/NewProfileStreakNotificationsInteractor.swift
- Stepic/Sources/Modules/Quizzes/BaseQuiz/BaseQuizViewController.swift
**YouTrack task**: [#APPS-3404](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3404)
- Fixes `StreaksAlertPresentationManager` not checking current notification permission status on enabling streaks notifications.
> Fix streak notifications manager not checking notification permission status

- Stepic/Sources/Frameworks/ContentProcessor/Processing/ContentProcessingRule.swift
- Stepic/Sources/Frameworks/ContentProcessor/Processing/ContentProcessor.swift
**YouTrack task**: [#APPS-3424](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3424)
- Makes the contents of the `<details>` tag visible and prevents toggle behavior.
> Fix <details> content not visible

- .swiftlint.yml
- Podfile
- Podfile.lock
- Stepic.xcodeproj/project.pbxproj
- Stepic/Sources/Frameworks/ContentProcessor/View/ProcessedContentView.swift
- Stepic/Sources/Modules/Discussions/Views/Cells/Discussion/DiscussionsTableViewCell.swift
- Stepic/Sources/Modules/Discussions/Views/TableViewDataSource/DiscussionsTableViewDataSource.swift
Bumps:
- [DeviceKit](https://github.com/devicekit/DeviceKit) from 4.4.0 to 4.5.0
- [SwiftLint](https://github.com/realm/SwiftLint) from 0.43.1 to 0.44.0
- [Firebase](https://github.com/firebase/firebase-ios-sdk) from 8.6.0 to 8.7.0
- [Nimble](https://github.com/Quick/Nimble) from 9.2.0 to 9.2.1
- [Amplitude](https://github.com/amplitude/Amplitude-iOS) from 8.3.0 to 8.3.1
- [YandexMobileMetrica](https://github.com/yandexmobile/metrica-sdk-ios) from 3.15.1 to 3.17.0
> Update dependencies 1.191

- Podfile
- Podfile.lock
Bumps:
- [Amplitude](https://github.com/amplitude/Amplitude-iOS) from 8.4.0 to 8.5.0
- [DeviceKit](https://github.com/devicekit/DeviceKit) from 4.5.1 to 4.5.2
- [PromiseKit](https://github.com/mxcl/PromiseKit) from 6.15.3 to 6.16.2
- [Firebase](https://github.com/firebase/firebase-ios-sdk) from 8.8.0 to 8.9.1
- [Branch](https://github.com/BranchMetrics/ios-branch-deep-linking-attribution) from 1.40.1 to 1.40.2
> Update dependencies 1.201

- Podfile
- Podfile.lock
- Stepic.xcodeproj/project.pbxproj
- Stepic/Legacy/AppDelegate.swift
- Stepic/Legacy/Model/Network/SocialSDKProviders/GoogleIDSocialSDKProvider.swift
- Stepic/Sources/Common/ImageDataProvider.swift
Bumps:
- [SDWebImage](https://github.com/SDWebImage/SDWebImage) from 5.12.1 to 5.12.2
- [Amplitude](https://github.com/amplitude/Amplitude-iOS) from 8.5.0 to 8.7.1
- [GoogleSignIn](https://github.com/google/GoogleSignIn-iOS) from 5.0.2 to 6.1.0
- [lottie-ios](https://github.com/airbnb/lottie-ios) from 3.2.3 to 3.3.0
- [Alamofire](https://github.com/Alamofire/Alamofire) from 5.4.4 to 5.5.0
- [Nuke](https://github.com/kean/Nuke) from 9.5.0 to 10.6.1
- [Firebase](https://github.com/firebase/firebase-ios-sdk) from 8.9.1 to 8.10.0
- [SwiftLint](https://github.com/realm/SwiftLint) from 0.45.0 to 0.45.1
> Update dependencies 1.206

- Stepic/Legacy/Views/AvatarImageView.swift
Fixes crash:
```
AvatarImageView.renderImage(with:)
NSInternalInconsistencyException - UIGraphicsBeginImageContext() failed to allocate CGBitampContext: size={0, 0}, scale=3.000000, bitmapInfo=<address>.
```
> Fix crash in AvatarImageView.renderImage(with:)
