StepicOrg/stepik-ios

Stepic.xcodeproj/project.pbxproj, Stepic/AppDelegate.swift, Stepic/Images.xcassets/boundedStepicIcon.imageset/Contents.json, Stepic/Info.plist, Stepic/NotificationReactionHandler.swift, Stepic/NotificationRegistrator.swift
Fixed release 1.6, when pushes did not work in distribution build
=> Distribution notifications fix

Stepic/Info.plist, Stepic/UIImageView+SVGDownload.swift, StepicWatch Extension/Info.plist, StepicWatch/Info.plist
=> Release/1.29 HOTFIX 2

Stepic/AnalyticsEvents.swift, Stepic/AuthInfo.swift
remove requestedNotNilToken from usage, because
we have limited number of events in mixpanel.
squash and merge please
=> Remove spam event

Stepic.xcodeproj/project.pbxproj, Stepic.xcodeproj/xcuserdata/Ostrenkiy.xcuserdatad/xcschemes/xcschememanagement.plist, Stepic/RateAppViewController.swift, StepicAdaptiveCourse/AdaptiveInfo.plist, StepicAdaptiveCourse/AdaptiveStepViewController.swift
* Fixed displaying app name in rate alert
* Fixed image zooming
=> Fixes to adaptive app

PagerController.swift, Stepic.xcodeproj/project.pbxproj, Stepic/Info.plist, StepicAdaptiveCourse/AdaptiveInfo.plist, StepicWatch Extension/Info.plist, StepicWatch/Info.plist, StickerPackExtension/Info.plist
Added autolayout support to PagerController.
=> Hotfix 1.35. Pager Controller layout.

Stepic/CodePlaygroundManager.swift
Добавлена проверка на конец строки (или файла) перед вставкой закрывающей скобки
Больше информации здесь: [APPS-1288](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1288) 
В дальнейшем будем автодополнять с учетом правильности скобочной последовательности в коде (предположительно - в 1.39).
=> Added the end of line check before bracket insertion

StepicAdaptiveCourse/AdaptiveStepPresenter.swift, StepicAdaptiveCourse/AdaptiveStepViewController.swift, StepicAdaptiveCourse/AdaptiveStepsPresenter.swift, StepicAdaptiveCourse/AdaptiveStepsViewController.swift, StepicAdaptiveCourse/RatingHelper.swift
- Фикс утечки памяти в AdaptiveStepViewController - AdaptiveStepPresenter - QuizViewController
- Формулы рейтинга как в Android версии
=> Memory leak fix & some changes

Stepic/FillBlanksDataset.swift, Stepic/FillBlanksTextTableViewCell.swift
В данном PR добавлена поддержка HTML к тексту в Fill Blanks Quiz
[APPS-1300](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1300) и [APPS-1308](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1308)
=> Fill blank text bug fix

StepicAdaptiveCourse/AdaptiveStepsPresenter.swift, StepicAdaptiveCourse/AdaptiveStepsViewController.swift
- Баг с дублирующейся рекомендацией при подгрузке пачек – [APPS-1335](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1335)
- Отсылка факта просмотра шага – [APPS-1336](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1336)
=> Fix recommendations bug

Stepic.xcodeproj/project.pbxproj, StepicAdaptiveCourse/AdaptiveStepsPresenter.swift, StepicAdaptiveCourse/StatsHelper.swift
Сохраняем сейчас статистику по рейтинг/день и максимальное кол-во правильных подряд, чтоб показать пользователю в следующем релизе.
=> Save stats for next release

Stepic/SectionTableViewCell.swift
- К дедлайнам в списке модулей добавлено время (как на сайте) [APPS-1269](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1269)
=> Add time to deadlines

Stepic/FindCoursesViewController.swift
Выделил в мейн тред присвоение sign in вьюшки по загрузке курсов.
Warning пропал.
=> Moved didSetCourses() content to main thread

JSQWebViewController.swift, Stepic/AppDelegate.swift, Stepic/Auth.storyboard, Stepic/AuthAPI.swift, Stepic/AuthManager.swift, Stepic/FBSocialSDKProvider.swift, Stepic/SignInViewController.swift, Stepic/SocialNetworks.swift, Stepic/SocialNetworksViewController.swift, Stepic/SocialSDKProvider.swift, Stepic/VKSocialSDKProvider.swift, Stepic/WebControllerManager.swift, Stepic/en.lproj/Localizable.strings, Stepic/ru.lproj/Localizable.strings
- Перенос email на форму ввода пароля [APPS-1297](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1297)
=> Prefill email field on signup

Stepic.xcodeproj/project.pbxproj, Stepic/ChoiceQuizViewController.swift, Stepic/CodeQuizViewController.swift, Stepic/FillBlanksQuizViewController.swift, Stepic/FreeAnswerQuizViewController.swift, Stepic/MatchingQuizViewController.swift, Stepic/MathQuizViewController.swift, Stepic/NumberQuizViewController.swift, Stepic/QuizPresenter.swift, Stepic/QuizViewController.swift, Stepic/ReplyCache.swift, Stepic/SortingQuizViewController.swift, Stepic/StringQuizViewController.swift
**Задача**: [#APPS-1337](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1337)
Теперь пользователь не теряет свои ответы, даже если закрыл задание.
**Описание**:
Добавил класс `ReplyCache`, который для attempt-а и step-а сохраняет реплай, который пользователь оставил. 
Кеш обновляется каждый раз, когда квиз, решаемый пользователем, пропадает с экрана.
=> Added reply cache

Stepic.xcodeproj/project.pbxproj, Stepic/SocialNetworksViewController.swift, Stepic/VKSocialSDKProvider.swift, StepicAdaptiveCourse/AdaptiveInfo.plist
**Задача**: [#APPS-1375](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1375)
- Исправлена авторизация, когда не установлено приложение ВКонтакте
- Исправлена авторизация через Facebook в основном приложении, когда установлено адаптивное
**Описание**:
- Теперь пробрасываем vkSdkShouldPresent() в SocialNetworksViewController и презентуем контроллер
- Удалена bundle URL схема Facebook из адаптивного приложения (не работает одновременно в двух приложениях)
=> Social auth bugs

Stepic.xcodeproj/project.pbxproj, StepicAdaptiveCourse/AdaptiveStatsPresenter.swift, StepicAdaptiveCourse/AdaptiveStepsPresenter.swift, StepicAdaptiveCourse/AdaptiveStepsViewController.swift
**Описание**:
Фиксы:
- Корректная отправка реакций (сломалось после рефакторинга в #92)
- Пропадающие при сборке ресурсы в новых таргетах
- Корректное обновление ачивки "решать X дней подряд"
- Бесконечная загрузка прогресса по неделям при нулевом рейтинге
=> Adaptive app fixes

Stepic/en.lproj/Localizable.strings, Stepic/ru.lproj/Localizable.strings, StepicAdaptiveCourse/AdaptiveRatingsPresenter.swift, StepicAdaptiveCourse/AdaptiveStatsViewController.swift, StepicAdaptiveCourse/Base.lproj/AdaptiveMain.storyboard, StepicAdaptiveCourse/Content/1838/Config.plist, StepicAdaptiveCourse/Content/1906/Config.plist, StepicAdaptiveCourse/Content/3067/Config.plist, StepicAdaptiveCourse/Content/3124/Config.plist, StepicAdaptiveCourse/Content/3149/Config.plist, StepicAdaptiveCourse/Content/3150/Config.plist, StepicAdaptiveCourse/en.lproj/AdaptiveMain.strings, StepicAdaptiveCourse/ru.lproj/AdaptiveMain.strings
**Описание**:
Мелкие правки:
- Новый url для сервера с рейтингом
- Рейтинг за сегодня
- Пустые состояния для страницы со статистикой
=> Change adaptive rating URL & today rating

Stepic/Info.plist, StepicWatch Extension/Info.plist, StepicWatch/Info.plist, StickerPackExtension/Info.plist
Ничего не пофиксили кроме версий билда.
Новый билд Apple аппрувнули.
=> Release 1.41 hotfix

StepicAdaptiveCourse/LeaderboardTableViewCell.xib, StepicAdaptiveCourse/en.lproj/AdaptiveMain.strings, StepicAdaptiveCourse/ru.lproj/AdaptiveMain.strings
Мелкие UI фиксы.
**Описание**:
- Лейблы с позицией в рейтинге не влезали
- "Последние 7 дней" в segmentedcontrol не влезали
=> Adaptive UI fixes

Stepic/AvatarImageView.swift
**Задача**: [#APPS-1468](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1468)
Фикс рендера аватаров
**Описание**:
Аватары (которые переделываем из SVG) рендерились не UI треде. Из-за неопределённого поведения были краши.
=> Fix avatars render

Stepic/UnitTableViewCell.xib
**Задача**: [#APPS-1507](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1507)
Теперь прогресс в уроках отображается хорошо
**Описание**:
Просто пофиксил relates to margins
=> Fixed units margins

Stepic/ChoiceQuizTableViewCell.xib, Stepic/SortingQuizTableViewCell.xib
**Задача**: [#APPS-1503](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1503)
Теперь квизы ресайзятся хорошо и полностью влезают
**Описание**:
Просто убрал констрейнты до margin-ов. Думал, что все сильно тяжелее и пытался запилить `LaTeXTextView` с автоматическим ресайзом, но все оказалось совсем просто.
=> Fixed margins for quizzes

Stepic/SectionTableViewCell.xib, Stepic/SectionsViewController.swift
**Задача**: [#APPS-1504](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1504)
Исправили неправильный ресайз section-ов
**Описание**:
Добавил поддержку AutoLayout для `SectionTableViewCell` и сайзинг по `UITableViewAutomaticDimension`
=> Added AutoLayout support for section cells

Stepic/CustomSearchBar.swift, Stepic/CustomSearchBar.xib, Stepic/FindCoursesViewController.swift
**Задача**: [#APPS-1518](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1518)
Фикс поведения кнопки Search
**Описание**:
Пофиксил поведение кнопки Search на клавиатуре в поисковой строке. Теперь по клику ищется введенный текст + кнопка неактивна, если в поле ничего не введено.
=> Handle click on Return key

Podfile, StepicAdaptiveCourse/AdaptiveOnboardingViewController.swift, StepicAdaptiveCourse/AdaptiveStepsViewController.swift
Обновили Koloda
**Описание**:
Просто обновлена Koloda до версии, в которой исправлен косметический баг с карточками.
=> Update cards pod in adaptive app

Stepic.xcodeproj/project.pbxproj, Stepic/ChoiceQuizTableViewCell.swift, Stepic/HTMLParsingUtil.swift, Stepic/Notification+FetchMethods.swift, Stepic/NotificationsViewController.swift, Stepic/SortingQuizTableViewCell.swift, Stepic/TagDetectionUtil.swift
Еще исправления для HTML в лейблах. Из-за латеха там нет автосайзинга для ячеек, а вычисление размера не вызывало метод для HTML-а в лейблах.
=> Quiz HTML sizes fix

Stepic/VideoDownloadView.swift, Stepic/VideoDownloadView.xib, Stepic/VideoStepViewController.swift
**Задача**: [#APPS-1517](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1517)
Удалили лейбл с качеством видео
**Описание**:
Просто удалён лейбл с экрана со степом, в который выводилось качество кешированного/воспроизводимого видео.
=> Remove video quality label

Stepic/ApiRequest.swift, Stepic/AuthAPI.swift, Stepic/AuthManager.swift, Stepic/EmailAuthPresenter.swift, Stepic/EmailAuthViewController.swift, Stepic/RegistrationPresenter.swift, Stepic/RegistrationViewController.swift, Stepic/SocialAuthPresenter.swift, Stepic/SocialAuthViewController.swift, Stepic/StepicsAPI.swift, Stepic/en.lproj/Localizable.strings, Stepic/ru.lproj/Localizable.strings
**Задача**: [#APPS-134](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-134)
Добавили сообщение об отсутствии интернет-соединения при авторизации и регистрации
**Описание**:
Пробрасываем `notConnectedToInternet ` в презентер и выводим ошибку при отсутствии соединения в авторизации/регистрации.
=> Message about bad connection

Stepic/Course.swift, Stepic/LessonPresenter.swift, Stepic/Section.swift, Stepic/SectionsViewController.swift, Stepic/UnitsViewController.swift
**Задача**: [#APPS-1559](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1559)
Сделали переход между модулями, если находимся в последнем степе последнего урока (первом степе первого урока)
**Описание**:
Если дошли до последнего (первого) урока, то подгружаем соответствующую "соседнюю" секцию, смотрим доступна ли она, затем подменяем ей текущую секцию в `UnitsViewController` и рефрешим контент.
=> 'Next lesson' in last unit

Podfile, Stepic/APIEndpoint.swift, Stepic/CoreDataHelper.swift, Stepic/CourseListHorizontalViewController.swift, Stepic/CourseListPresenter.swift, Stepic/CourseListVerticalViewController.swift, Stepic/CourseListViewController.swift
Фиксы проблем 1.46
**Описание**:
Исправлены следующие проблемы:
=> Pre-release 1.46 fixes

Stepic/LastStepRouter.swift
**Задача**: [#APPS-1535](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1535)
Исправили бесконечный лоадер при переходе к последнему степу в случае закрытого модуля
**Описание**:
Теперь подгружаем секцию смотрим на `isReachable` у неё и редиректим на расписание.
=> Fix last step transition for unreachable section

Stepic/AppDelegate.swift
**Описание**:
Добавил .clear маску для SVProgressHUD, теперь интерфейс блочится
=> Blocking UI for SVProgressHUD

Stepic/CourseListPresenter.swift
Теперь при смене языка не рефрешится список курсов пользователя
=> Removed refreshing enrolled courses after language change

Stepic/Model.xcdatamodeld/Model_courselists_v21.xcdatamodel/contents, Stepic/Section+CoreDataProperties.swift, Stepic/Section.swift, Stepic/SectionTableViewCell.swift, Stepic/en.lproj/Localizable.strings, Stepic/ru.lproj/Localizable.strings
**Задача**: [#APPS-1671](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1671)
Добавили дату закрытия модуля
**Описание**:
К сущности Section добавлено соответствующее поле, на странице с модулями теперь отображаем дату закрытия.
=> End date in section description

Stepic/UnitsViewController.swift
**Задача**: [#APPS-1666](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1666)
**Коротко для Release Notes, в формате «Сделали/Добавили/Исправили N»**:
Добавили поиск следующей непустой секции в навигацию по кнопке "Следующий урок" 
**Описание**:
Ищем следующую (предыдущую) секцию, которая содержит юниты и используем для перехода её.
=> Find next non-empty unit for 'Next lesson'

Stepic/CourseListViewController.swift, Stepic/Sorter.swift
**Задача**: [#](https://vyahhi.myjetbrains.com/youtrack/issue/)
**Описание**:
Попытки пофиксить краш с апдейтом `HorizontalCourseListViewController`
=> Fix course list crashes

Stepic/CourseTagsView.swift
Fixed collection crash on iOS 10
=> Fix iOS 10 collection crash

Stepic/DeviceInfo.swift, Stepic/OnboardingPageView.swift, Stepic/OnboardingPageView.xib, Stepic/OnboardingViewController.swift, Stepic/ProfilePresenter.swift, Stepic/StyledTabBarViewController.swift
Исправили баги с лейаутом
**Описание**:
* Онбординг:
* Баг с инсетами в скроллвью на iPhone X
* Уменьшенный шрифт для 3.5 экрана
* Используем StepikButton
* Рефакторинг расчета высоты для лейбла с описанием
* Для верстки, зависящей от ориентации используем ориентацию интерфейса, а не девайса
* Код обновления при повороте убран из viewWillTransition
* Баг с анимациями из-за пропущенного `super.viewWillAppear()`
=> Fix layout issues

Stepic/AppDelegate.swift
Исправлено обновление токена при подгрузке числа непрочитанных уведомлений
=> Fix missed checkToken

Stepic.xcodeproj/xcuserdata/Ostrenkiy.xcuserdatad/xcschemes/xcschememanagement.plist, Stepic/UnitTableViewCell.xib, Stepic/VideoDownloadView.xib, Stepic/VideoStepViewController.swift
**Задача**: [#APPS-1702](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1702)
Исправили ошибку, когда кнопка загрузки видео в видеостепе лейаутилась в неправильном месте
**Описание**:
Проблема была в лишних констрейнтах на высоту. Убрал их и все стало хорошо.
=> Fixed video download view layout problems

Stepic.xcodeproj/project.pbxproj, Stepic.xcodeproj/xcuserdata/Ostrenkiy.xcuserdatad/xcschemes/xcschememanagement.plist, Stepic/HeaderMenuBlockTableViewCell.xib, Stepic/HomeScreenViewController.swift, Stepic/SectionsViewController.swift
**Задача**: [#APPS-1741](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1741)
**Описание**:
Фиксы для тултипов, описанных в задаче
=> Tooltip fixes

Stepic/Adaptive.storyboard, Stepic/AdaptiveRatingsViewController.swift, Stepic/AdaptiveStatsPagerViewController.swift, Stepic/AdaptiveStatsViewController.swift, Stepic/Base.lproj/LaunchScreen.xib, Stepic/CardStepPresenter.swift, Stepic/CardStepViewController.swift, Stepic/CardsStepsPresenter.swift, Stepic/CardsStepsViewController.swift, Stepic/CourseListPresenter.swift, Stepic/ExplorePresenter.swift, Stepic/HomeScreenPresenter.swift, Stepic/SearchResultsPresenter.swift, Stepic/StepCardView.swift, Stepic/StepCardView.xib, Stepic/en.lproj/Localizable.strings, Stepic/ru.lproj/Localizable.strings
**Задача**: [#APPS-1754](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1754), [#APPS-1755](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1755), [#APPS-1763](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1763)
Фиксы багов в адаптивных курсах
**Описание**:
* Краш статистики на iOS 9-10
* Неверное отображение прогресса на iOS 9-10
* Кнопка перехода к комментариям для онбординга
* Открытие карточек после записи на курс (вместо силлабуса)
* Фикс автоскролла
* Фикс тени после возврата из курса
=> Adaptive courses bug fixes

Stepic/AuthInfo.swift, Stepic/CardStepPresenter.swift, Stepic/CardStepViewController.swift, Stepic/CardsStepsViewController.swift, Stepic/DiscussionsStoryboard.storyboard, Stepic/NotificationsPresenter.swift, Stepic/VideoStepViewController.swift, Stepic/WriteCommentViewController.swift
**Задача**: [#APPS-1760](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1760) [#APPS-1756](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1756)[#APPS-1761](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1761)
**Описание**:
Исправлены баги:
- сдвиг приложения при написании комментария
- растягивающаяся кнопка загрузки на iOS 11
- не сбрасываются уведомления при логауте
=> Release 1.51 fix

Stepic/CardsStepsPresenter.swift
**Описание**:
Обновление адаптивного рейтинга после каждого успешного сабмишена.
=> Fix adaptive rating update

Stepic/StepOptions.swift
**Задача**: [#APPS-1734](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1734)
Добавили поддержку многострочных сэмплов в код квиз
**Описание**:
Для сэмплов изменил все `\n` на `<br>` с помощью `.replacingOccurenciesOf()`.
=> Added multiline code samples support

Stepic/CourseListHorizontalViewController.swift, Stepic/CourseListPresenter.swift, Stepic/CourseListVerticalViewController.swift
**Задача**: [#APPS-1777](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1777)
Сделали виджеты кликабельными
**Описание**:
Для неадаптивного курса:
* Открываем инфо о курсе, если не подписаны
* Открываем расписание, если подписаны
Для адаптивного курса:
* Учиться, если подписаны
* Подписываемся и учимся, если не подписаны
Для адаптивных такое поведение связано с тем, что страницы курсов ужасные и ни один человек в здравом уме добровольно на это не подпишется. Значит будем его форсить.
=> Added selection on widgets

Stepic/RateAppViewController.xib
**Задача**: [#APPS-1686](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1686)
Исправили ширину окна с оценкой
**Описание**:
Добавлены leading и trailing констрейнты, чтобы ширина задавалась с учётом звезд.
=> Fix rate alert in adaptive app

Stepic/AnalyticsEvents.swift, Stepic/PinsMapExpandableMenuBlockTableViewCell.swift, Stepic/PinsMapView.swift, Stepic/ProfilePresenter.swift
**Описание**:
Небольшие фиксы для вью с активностью:
* Разделен процесс построения, шаг с генерацией месяцев не повторяется
* Лэйаут не обновляется, если размеры не изменились
* Протестировано на всех экранах и ориентациях
* Блок в профиле подвинут выше (над био)
* Анимация появления
* Аналитика на взаимодействие (отправляется 1 раз, по скроллу на соседнюю страницу)
=> Fix user activity view layout

Stepic/PinsMapExpandableMenuBlockTableViewCell.xib, Stepic/PinsMapView.swift
**Задача**: [#APPS-1818](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1818)
Исправили отображение некоторых месяцев и добавили индикатор страниц
**Описание**:
Фикс раскладки месяцев + page control под scroll view для индикации страниц.
=> Fixes for user activity

Stepic/Adaptive.storyboard, Stepic/BaseCardsStepsViewController.swift, Stepic/CardStepViewController.swift
**Задача**: [#APPS-1816](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1816)
Исправлен краш при переходе к следующей карточке на iOS 9
**Описание**:
Вместе с фиксом краша исправлено обновление прогресса + отцентрирован label с уровнем и рейтингом.
=> Fix crash on iOS 9 devices

Podfile, Stepic.xcodeproj/project.pbxproj, fastlane/Fastfile
**Описание**:
Фикс падающих на тимсити билдов.
=> Fix TeamCity builds

Stepic/CardStepViewController.swift
**Задача**: [#APPS-1441](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1441), [#APPS-1446](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1446)
Исправление багов WebView в адаптивных шагах
**Описание**:
Исправлено поведение при поворотах для WKWebView в контроллере с адаптивными шагами. При повороте вызывается `reload` у вебвью и заново выполняется центрирование изображения и ресайз по высоте.
=> Fix webview bugs in adaptive steps

Stepic/ProfileViewController.swift
**Задача**: [#APPS-1840](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1840)
Выпилили кнопку "поделиться" для анонимного пользователя
=> Share button in profile for anonymous

Stepic/SectionsViewController.swift, Stepic/StepikTableView.swift, Stepic/UnitsViewController.swift
**Описание**:
Фикс состояния загрузки для модулей и уроков.
=> Fix loading placeholder for sections & units

Podfile
**Описание**:
IQKeyboardManager обновился до 6 версии и требует миграции, зафиксировал 5.x.
=> Fix IQKeyboardManager version

Stepic/CourseListViewController.swift, Stepic/StepikTableView.swift, Stepic/en.lproj/Localizable.strings, Stepic/ru.lproj/Localizable.strings
**Задача**: [#APPS-1841](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1841)
Исправили отображение описания ошибки на плейсхолдере в тегах
=> Fix placeholder localization for tags

Stepic/CardStepPresenter.swift
**Задача**: [#APPS-1863](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1863)
Добавили поддержку number и string квизов в адаптивные степы
=> Add number and string quizzes to adaptive steps

Podfile, Stepic.xcodeproj/project.pbxproj, Stepic/CodeEditorPreferencesContainer.swift, Stepic/CodeEditorPreviewView.swift, Stepic/CodeEditorPreviewView.xib, Stepic/CodeEditorSettingsPresenter.swift, Stepic/CodeEditorSettingsViewController.swift, Stepic/CodeElementsSize.swift, Stepic/CodeLanguages.swift, Stepic/CodeQuizViewController.swift, Stepic/FullscreenCodeQuizViewController.swift, Stepic/HeaderMenuBlockTableViewCell.xib, Stepic/MenuBlocks.swift, Stepic/MenuUIManager.swift, Stepic/PreferencesContainer.swift, Stepic/Profile.storyboard, Stepic/RemoteConfig.swift, Stepic/SettingsPresenter.swift, Stepic/SettingsViewController.swift, Stepic/en.lproj/Localizable.strings, Stepic/ru.lproj/Localizable.strings
**Задача**: [#APPS-1849](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1849)
Добавили возможность менять цветовую тему и размер шрифта в редакторе кода
**Описание**:
В настройках добавлен раздел, в котором можно изменить тему оформления (из доступных для highlightr) и размер шрифта.
=> Code quiz settings

Podfile, Stepic.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, Stepic/AnalyticsHelper.swift, Stepic/Info.plist
**Задача**: [#APPS-1855](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1855)
Добавили Appsee SDK
**Описание**:
=> Appsee SDK integration

Stepic/CourseListPresenter.swift, Stepic/CourseListViewData.swift, Stepic/CourseWidgetTableViewCell.swift, Stepic/CourseWidgetView.swift, Stepic/CourseWidgetView.xib, Stepic/en.lproj/Localizable.strings, Stepic/ru.lproj/Localizable.strings
**Задача**: [#APPS-1793](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1793)
Помечаем адаптивные курсы отдельной меткой
=> Label for adaptive courses

Stepic/StyledTabBarViewController.swift
Изменили цвет для айтемов в таббаре
=> New color for unselected items in tab bar

Stepic/CourseListViewController.swift
**Задача**: [#APPS-1619](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1619)
Исправили 3D Touch в списках курсов
**Описание**:
Регистрация делегата для превью теперь в `viewDidAppear`.
=> Fix 3D touch in course list

Podfile, Stepic/RemoteConfig.swift
Обновили Firebase и зафиксировали новую версию в Podfile, чтобы сборки больше неожиданно не ломались
=> Updated firebase & fixed firebase pods versions

DefaultsContainer.swift, Stepic.xcodeproj/project.pbxproj, Stepic/ContentLanguage.swift, Stepic/ContentLanguagePreferenceTableViewCell.swift, Stepic/ContentLanguagePreferenceTableViewCell.xib, Stepic/ContentLanguagesView.swift, Stepic/ContentLanguagesView.xib, Stepic/ExploreDefaultsContainer.swift, Stepic/ExplorePresenter.swift, Stepic/ExploreViewController.swift, Stepic/Info.plist, Stepic/LanguageSettingsViewController.swift, Stepic/Profile.storyboard, Stepic/SettingsMenuBlock.swift, Stepic/SettingsPresenter.swift, Stepic/SettingsViewController.swift, Stepic/en.lproj/Localizable.strings, Stepic/ru.lproj/Localizable.strings, StepicAdaptiveCourse/Content/1838/AdaptiveInfo.plist, StepicAdaptiveCourse/Content/3124/AdaptiveInfo.plist, StepicAdaptiveCourse/Content/3149/AdaptiveInfo.plist, StepicAdaptiveCourse/Content/3150/AdaptiveInfo.plist, StepicAdaptiveCourse/DefaultsStorageManager.swift, StepicTests/Info.plist, StepicWatch Extension/Info.plist, StepicWatch/Info.plist, StepikTV/Info.plist, StepikTVTests/Info.plist, StickerPackExtension/Info.plist, UITests/Screenshots/Info.plist
* Hide language widget [#302](https://github.com/StepicOrg/stepik-ios/pull/302)
=> Release 1.61

Stepic/AdaptiveRatingsPresenter.swift, Stepic/AuthAPI.swift, Stepic/CardsStepsPresenter.swift, Stepic/CertificatesPresenter.swift, Stepic/Comment.swift, Stepic/CourseListType.swift, Stepic/CourseListViewController.swift, Stepic/DiscussionProxy.swift, Stepic/ExplorePresenter.swift, Stepic/HTMLParsingUtil.swift, Stepic/RecommendationsAPI.swift, Stepic/RemoteConfig.swift, Stepic/RetrieveRequestMaker.swift, Stepic/SortingQuizViewController.swift, Stepic/StepOptions.swift, Stepic/StepikPlaceholderView.swift, Stepic/StyledTabBarViewController.swift, StepicAdaptiveCourse/LocalNotificationsHelper.swift
**Задача**: [#APPS-1954](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1954)
Замена `flatMap` на `compactMap`.
**Описание**:
[Replacing flatMap With compactMap](https://useyourloaf.com/blog/replacing-flatmap-with-compactmap/)
=> Replace flatMap with compactMap

.github/pull_request_template.txt
```
**Задача**: [#](https://vyahhi.myjetbrains.com/youtrack/issue/)
**Описание**:
```
Вот так теперь будет выглядеть темплейт для PR-ов. Если есть другие предложения - комментите.
=> Removed short description from PR template

Stepic/SectionsViewController.swift
**Задача**: [#APPS-1930](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1930)
**Описание**:
Добавлены несколько условий для появления виджета, предлагающего подписаться на персональный дедлайн
=> Fix personal deadline bugs

ExamEGERussian/Sources/ApplicationLayer/AppDelegate/AppDelegate.swift, ExamEGERussian/Sources/ApplicationLayer/RootNavigationManager/RootNavigationManager.swift, ExamEGERussian/Sources/BusinessLogicLayer/Assemblies/ServiceComponentsAssembly/ServiceComponents.swift, ExamEGERussian/Sources/BusinessLogicLayer/Assemblies/ServiceComponentsAssembly/ServiceComponentsAssembly.swift, ExamEGERussian/Sources/BusinessLogicLayer/Services/UserRegistrationService/UserRegistrationService.swift, ExamEGERussian/Sources/BusinessLogicLayer/Services/UserRegistrationService/UserRegistrationServiceImplementation.swift, ExamEGERussian/Sources/Helpers/RandomCredentialsGenerator/RandomCredentialsGenerator.swift, ExamEGERussian/Sources/Helpers/RandomCredentialsGenerator/RandomCredentialsGeneratorImplementation.swift, ExamEGERussian/Sources/PresentationLayer/UserStories/Main/MainViewController.swift, ExamEGERussianTests/AssembliesTests/ServiceComponentsAssemblyTests/ServiceComponentsAssemblyTests.swift, ExamEGERussianTests/AssembliesTests/ServiceComponentsAssemblyTests/ServiceComponentsAssemblyTestsHelper.swift, ExamEGERussianTests/LogicTests/UserRegistrationServiceTests/UserRegistrationServiceMock.swift, ExamEGERussianTests/LogicTests/UserRegistrationServiceTests/UserRegistrationServiceTests.swift, ExamEGERussianTests/PresentationTests/ModulesTests/MainModuleTests/MainViewControllerTests.swift, ExamEGERussianUITests/ExamEGERussianUITests.swift, Stepic.xcodeproj/project.pbxproj
**Описание**:
Забыл изначально добавить `Swift Lint` скрипт в `ExamEGERussian` таргет, каюсь.
=> Integrate SwiftLint into ExamEGERussian target

.codebeatignore, README.md
**Описание**:
Выпилил codebeat. 
@Ostrenkiy видимо, нужно ещё в аккаунте там удалить интеграцию. Хуки в репозитории удалил.
=> Remove codebeat

Podfile
**Описание**:
Исправили проблему с версией метрики, из-за которой приложение реджектили.
=> Changed AppMetrica version 3.0.0 -> 3.1.2

Stepic/CourseListHorizontalViewController.swift, Stepic/CourseListVerticalViewController.swift
**Задача**: [#APPS-1973](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1973)
**Описание**:
Поправил анимации в CourseList-ах, заменив все анимированные апдейты на `reloadData()`, чтобы ничего не крашилось.
=> Fixed CourseList animations crashes (probably)

Stepic/AchievementsListViewController.swift, Stepic/AdaptiveRatingsPresenter.swift, Stepic/AdaptiveStatsPresenter.swift, Stepic/CertificatesPresenter.swift, Stepic/ChoiceQuizLabelTableViewCell.swift, Stepic/CodePlaygroundManager.swift, Stepic/LastStepRouter.swift, Stepic/LessonPresenter.swift, Stepic/NotificationPermissionManager.swift, Stepic/PinsMapView.swift, Stepic/PlaceholderTableViewCell.swift, Stepic/Presentr/PresentrController.swift, Stepic/ProfileAchievementsContentView.swift, Stepic/QuizViewController.swift, Stepic/Skeletonable.swift, Stepic/StandardsExtensions.swift, Stepic/UnitsViewController.swift, Stepic/Video.swift, StepicAdaptiveCourse/AchievementManager+Data.swift, StepicTests/DownloaderTests.swift, StepikTV/Controllers/CourseInfo/CourseInfoPresenter.swift
**Описание**:
`swiftlint` обновился и автокоррекция поумнела.
Выполненна команда: `swiftlint autocorrect & swiftlint`.
Думаю тут нет ничего страшного, рано или поздно кто-нибудь бы это закомитил, можно мерджить :trollface:
=> Run swiftlint autocorrect

ExamEGERussian/Sources/CoreLayer/Graph/Base/Vertex.swift, ExamEGERussian/Sources/CoreLayer/Graph/ConcreteClasses/AdjacencyListGraph.swift, ExamEGERussian/Sources/CoreLayer/Graph/ConcreteClasses/KnowledgeGraph/KnowledgeGraph.swift, ExamEGERussianTests/CoreLayerTests/Graph/TopologicalSortTests.swift, Stepic.xcodeproj/project.pbxproj
**Задача**: [#APPS-2002](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2002)
**Описание**:
Реализовали [алгоритм](http://rain.ifmo.ru/cat/view.php/vis/graph-general/topological-sort-2007/algorithm) топологической сортировки графа с помощью обхода в глубину
=> Topological sort

Stepic.xcodeproj/project.pbxproj, Stepic/Model.xcdatamodeld/.xccurrentversion, Stepic/Model.xcdatamodeld/Model_profile_staff_v24.xcdatamodel/contents, Stepic/Profile+CoreDataProperties.swift, Stepic/Profile.swift, Stepic/StepicsAPI.swift, Stepic/StoriesPresenter.swift, Stepic/StoryTemplatesAPI.swift, Stepic/User+CoreDataProperties.swift
**Задача**: [#APPS-2028](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2028)
**Описание**:
Добавили новую версию модели и теперь при запросе на `api/stepics/1` вместе с пользователем подгружаем и его профиль с галочкой is_staff, по которой решаем, отображать неопубликованные истории или нет.
=> Show unpublished stories for staff

Stepic/DeepLinkRoutingService.swift
**Задача**: [#APPS-2068](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2068)
**Описание**:
Добавили возможные символы в конце регулярного выражения
=> fixed syllabus regex

ExamEGERussian/Sources/BusinessLogicLayer/Services/LessonsService/LessonsService.swift, ExamEGERussian/Sources/BusinessLogicLayer/Services/LessonsService/LessonsServiceImpl.swift, ExamEGERussian/Sources/BusinessLogicLayer/Services/StepsService/StepsServiceImpl.swift, ExamEGERussian/Sources/PresentationLayer/Learning/Assembly/LearningAssembly.swift, ExamEGERussian/Sources/PresentationLayer/Learning/Presenter/LearningPresenter.swift, ExamEGERussian/Sources/PresentationLayer/Learning/Presenter/LearningPresenterProtocol.swift, ExamEGERussian/Sources/PresentationLayer/Learning/View/LearningTableViewController.swift, ExamEGERussianTests/BusinessLogicLayerTests/ServicesTests/RecommendationsServiceTests.swift, ExamEGERussianTests/Common/Mock/Services/LessonsServiceMock.swift, Stepic/en.lproj/Localizable.strings, Stepic/ru.lproj/Localizable.strings
**Задача**: [#APPS-2047](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2047)
**Описание**:
Добавили отображение прохождения топика в процентном отношении.
=> Show complete percentage

ExamEGERussian/Sources/CoreLayer/Graph/ConcreteClasses/KnowledgeGraph/KnowledgeGraphVertex.swift, ExamEGERussian/Sources/Model/Builders/Graph/KnowledgeGraphBuilder.swift, ExamEGERussian/Sources/Model/PlainObjects/KnowledgeGraph/KnowledgeGraphTopicPlainObject.swift, ExamEGERussian/Sources/PresentationLayer/Learning/Presenter/LearningPresenter.swift, ExamEGERussianTests/Common/FactoryMethods/PlainObjects/KnowledgeGraph/KnowledgeGraphPlainObject+Make.swift, ExamEGERussianTests/ModelTests/PlainObjectsTests/KnowledgeGraphTests/KnowledgeGraphPlainObjectTests.swift, ExamEGERussianTests/ModelTests/PlainObjectsTests/KnowledgeGraphTests/KnowledgeGraphTopicPlainObjectTests.swift, ExamEGERussianTests/SupportingFiles/knowledge-graph.json
**Задача**: [#APPS-2048](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2048)
**Описание**:
Добавили новое поле `description` в JSON файл графа знананий, парсинг данного значения и его отображение.
=> Add topic description

ExamEGERussian/Sources/Common/Extensions/UIViewController/UIViewController+Alert.swift, ExamEGERussian/Sources/PresentationLayer/Steps/Standart/Pager/Presenter/StepsPagerPresenterImpl.swift, ExamEGERussian/Sources/PresentationLayer/Steps/Standart/Pager/View/StepsPagerView.swift, ExamEGERussian/Sources/PresentationLayer/Steps/Standart/Pager/View/StepsPagerViewController.swift, Stepic/en.lproj/Localizable.strings, Stepic/ru.lproj/Localizable.strings
**Задача**: [#APPS-2069](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2069)
**Описание**:
Добавили возможность прохождения теоретических уроков в офлайн режиме.
=> Improve steps offline viewing 

Stepic/Scripts.plist
**Задача**: [#APPS-2084](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2084)
**Описание**:
Зафиксировали версию плейграунда для kotlin, которая не делает приложению больно
=> Fix kotlin playground version

ExamEGERussian/Resources/Config/Info.plist
**Описание**:
- bundle display name
- version
=> Update config info

Stepic/Modules/BaseExplore/BaseExploreViewController.swift, Stepic/Modules/Explore/ExploreViewController.swift, Stepic/Modules/Explore/View/BaseExploreView.swift, Stepic/Modules/FullscreenCourseList/View/FullscreenCourseListView.swift, Stepic/Modules/Tags/View/ExploreSearchBar.swift, Stepic/StyledNavigationViewController.swift, Stepic/StyledTabBarViewController.swift
**Задача**: [#APPS-2093](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2093)
**Описание**:
Рабочий лэндскейп для Explore & Home.
=> Fix Explore landscape

Stepic/Notification.swift, Stepic/NotificationReactionHandler.swift, Stepic/Services/Notifications/NotificationsService.swift
**Задача**: [#APPS-2013 (Продолжение)](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2013)
**Описание**:
Добавили поддержку пуша о том, что получен сертификат по курсу.
Реакция - открыть приложение на вкладке "Сертификаты".
=> Handle issued certificate notifications

Stepic/CoursesAPI.swift, Stepic/Modules/CourseList/Provider/CourseListNetworkService.swift, Stepic/SearchResultsAPI.swift
**Задача**: [#APPS-2104](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2104)
**Описание**:
Добавил флажок `is_popular` в популярные курсы, а также `is_popular` и `is_public` в поиск.
=> New Search and Popular Course List query parameters

Stepic/AutocompleteWords.swift, Stepic/CodeLanguages.swift, Stepic/CodePlaygroundManager.swift, Stepic/CodeSnippetSymbols.swift
**Задача**: [#APPS-2137](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2137)
**Описание**:
Добавили Java 9 и 11 в код квиз.
=> Add Java 9 and Java 11 support

Stepic/UnitsViewController.swift
**Задача**: [#APPS-2133](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2133)
**Описание**:
Исправили отображение оглавления курса в офлайн-режиме.
=> Fix units content offline viewing

Stepic.xcodeproj/project.pbxproj, Stepic/Modules/CourseInfo/CourseInfoView.swift, Stepic/Modules/CourseInfo/Other views/TabSegmentedControlView.swift, Stepic/Modules/Explore/View/ScrollableStackView.swift
**Описание**:
Простой переключатель табов как в PagerController.
=> Course info: segmented control

Stepic.xcodeproj/project.pbxproj, Stepic/Analytics/AmplitudeAnalyticsEvents.swift, Stepic/AppDelegate.swift, Stepic/Info.plist, Stepic/RetentionLocalNotificationProvider.swift, Stepic/Services/Notifications/NotificationsService.swift, StepicAdaptiveCourse/Content/1838/AdaptiveInfo.plist, StepicAdaptiveCourse/Content/3124/AdaptiveInfo.plist, StepicAdaptiveCourse/Content/3149/AdaptiveInfo.plist, StepicAdaptiveCourse/Content/3150/AdaptiveInfo.plist, StepicTests/Info.plist, StepicWatch Extension/Info.plist, StepicWatch/Info.plist, StepikTV/Info.plist, StepikTVTests/Info.plist, StickerPackExtension/Info.plist, UITests/Screenshots/Info.plist
=> Hotfix 1.74

Stepic.xcodeproj/project.pbxproj, Stepic/CourseSubscriptionManager.swift, Stepic/LessonPresenter.swift, Stepic/Modules/ContinueCourse/ContinueCourseAssembly.swift, Stepic/Modules/ContinueCourse/ContinueCourseInteractor.swift, Stepic/Modules/CourseList/CourseListAssembly.swift, Stepic/Modules/CourseList/CourseListInteractor.swift, Stepic/Services/DataBackUpdateService.swift
**Задача**: [#APPS-2096](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2096)
**Описание**:
Сервис, который умеет рассылать обновления о различных действиях и с помощью которого эти обновления можно получать. 
В данной задачи обновляем прогресс в курслистах и в виджете "продолжить".
=> Update progress & enrollment state in active modules

Stepic.xcodeproj/project.pbxproj, Stepic/DownloadTableViewCell.swift, Stepic/DownloadTableViewCell.xib, Stepic/DownloadsViewController.swift, Stepic/Modules/CourseInfo/CourseInfoInteractor.swift, Stepic/Modules/CourseInfo/CourseInfoPresenter.swift, Stepic/Modules/CourseInfo/CourseInfoViewController.swift, Stepic/Modules/CourseInfoTabSyllabus/CourseInfoTabSyllabusInteractor.swift, Stepic/SettingsMenuBlock.swift, Stepic/SettingsPresenter.swift, Stepic/SettingsViewController.swift, Stepic/Video.swift, Stepic/VideoDownloadingService.swift
**Задача**: [#APPS-2213](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2213)
**Описание**:
Фиксы, связанные с экраном "О курсе".
=> Course info fixes

Stepic/OpenedStoriesPageViewController.swift, Stepic/StoryPresenter.swift, Stepic/StoryViewController.xib
**Задача**: [#APPS-2228](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2228), [#APPS-2230](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2230)
**Описание**:
Мелкие баги в историях.
=> Fix bugs in Stories

Stepic.xcodeproj/project.pbxproj, Stepic/HTMLProcessor.swift, Stepic/Scripts.plist, Stepic/Scripts.swift, Stepic/Utils/TagDetectionUtil.swift, Stepic/highlight.js, Stepic/stepikcontent.css, Stepic/wysiwyg.css
**Задача**: [#APPS-2226](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2226)
**Описание**:
Стили от нового визивига, добавлен highlight.js
=> New WYSIWYG support

Stepic/Modules/CourseInfoTabSyllabus/CourseInfoTabSyllabusInteractor.swift, Stepic/Modules/CourseInfoTabSyllabus/CourseInfoTabSyllabusPresenter.swift
**Описание**:
Фиксы багов в силлабусе ("Загрузить всё" и закрытые секции).
=> Syllabus bug fixes

Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabInfo/CourseInfoTabInfoViewController.swift
**Задача**: [#APPS-1966](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1966)
**Описание**:
Исправлен баг с воспроизведением интро-видео на неактивном контроллере.
=> Fix bug with intro video playing on disappeared controller

Stepic/LessonPresenter.swift, Stepic/Sources/Controllers/StyledNavigationController.swift
**Задача**: [#APPS-2274](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2274)
**Описание**:
Фикс лишних запросов на прогресс.
=> Fix progress fetching bug

Stepic.xcodeproj/project.pbxproj, Stepic/AdaptiveRatingsPresenter.swift, Stepic/AdaptiveRatingsViewController.swift, Stepic/Analytics/AmplitudeAnalyticsEvents.swift, Stepic/Info.plist, Stepic/LessonPresenter.swift, Stepic/Sources/Controllers/StyledNavigationController.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabInfo/CourseInfoTabInfoViewController.swift, StepicAdaptiveCourse/Content/1838/AdaptiveInfo.plist, StepicAdaptiveCourse/Content/3124/AdaptiveInfo.plist, StepicAdaptiveCourse/Content/3149/AdaptiveInfo.plist, StepicAdaptiveCourse/Content/3150/AdaptiveInfo.plist, StepicTests/Info.plist, StepicWatch Extension/Info.plist, StepicWatch/Info.plist, StepikTV/Info.plist, StepikTVTests/Info.plist, StickerPackExtension/Info.plist, UITests/Screenshots/Info.plist
* Fixed progress fetching bug [#466](https://github.com/StepicOrg/stepik-ios/pull/466)
* Fixed bug with intro video playing on disappeared controller [#465](https://github.com/StepicOrg/stepik-ios/pull/465)
=> Release 1.81

Stepic/Modules/SearchResultsLegacy.swift, Stepic/SearchQueriesPresenter.swift, Stepic/SearchQueriesViewController.swift, Stepic/SearchResultsPresenter.swift, Stepic/Sources/Modules/Explore/ExploreViewController.swift, Stepic/Sources/Modules/FullscreenCourseList/FullscreenCourseListViewController.swift, Stepic/StepikPlaceholderStyle+Placeholders.swift, Stepic/en.lproj/Localizable.strings, Stepic/ru.lproj/Localizable.strings
**Задача**: [#APPS-2279](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2279), [#APPS-2276](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2276), [#APPS-2275](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2275)
**Описание**:
Улучшения поиска.
=> Search improvements

Stepic.xcodeproj/project.pbxproj, Stepic/Course+CoreDataProperties.swift, Stepic/Course.swift, Stepic/Model.xcdatamodeld/.xccurrentversion, Stepic/Model.xcdatamodeld/Model_course_is_certificate_auto_issued.xcdatamodel/contents, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabInfo/CourseInfoTabInfoPresenter.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabInfo/CourseInfoTabInfoViewModel.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabInfo/Views/CourseInfoTabInfoView.swift
**Задача**: [#APPS-1691](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1691)
**Описание**:
Отображаем сертификаты только в курсах с `is_certificate_auto_issued == true`.
=> Fix certificates blocks in course info module

Podfile, Podfile.lock, Stepic.xcodeproj/project.pbxproj, Stepic/Info.plist, StepicAdaptiveCourse/Content/1838/AdaptiveInfo.plist, StepicAdaptiveCourse/Content/3124/AdaptiveInfo.plist, StepicAdaptiveCourse/Content/3149/AdaptiveInfo.plist, StepicAdaptiveCourse/Content/3150/AdaptiveInfo.plist, StepicTests/Info.plist, StepicWatch Extension/Info.plist, StepicWatch/Info.plist, StepikTV/Info.plist, StepikTVTests/Info.plist, StickerPackExtension/Info.plist, UITests/Screenshots/Info.plist
**Описание**:
Фикс сборки из-за устаревших зависимостей.
=> Fix dependencies

Stepic/HTMLProcessor.swift
**Задача**: [#APPS-2233](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2233)
**Описание**:
Правильный порядок инжекта js кода в текст степа.
=> Fix custom audio control

Stepic.xcodeproj/project.pbxproj, Stepic/Course+CoreDataProperties.swift, Stepic/Course.swift, Stepic/Model.xcdatamodeld/.xccurrentversion, Stepic/Model.xcdatamodeld/Model_course_paid.xcdatamodel/contents, Stepic/Sources/Modules/BaseExplore/BaseExploreDataFlow.swift, Stepic/Sources/Modules/BaseExplore/BaseExploreInteractor.swift, Stepic/Sources/Modules/BaseExplore/BaseExplorePresenter.swift, Stepic/Sources/Modules/BaseExplore/BaseExploreViewController.swift, Stepic/Sources/Modules/CourseInfo/CourseInfoDataFlow.swift, Stepic/Sources/Modules/CourseInfo/CourseInfoHeaderViewModel.swift, Stepic/Sources/Modules/CourseInfo/CourseInfoInteractor.swift, Stepic/Sources/Modules/CourseInfo/CourseInfoPresenter.swift, Stepic/Sources/Modules/CourseInfo/CourseInfoViewController.swift, Stepic/Sources/Modules/CourseInfo/Views/CourseInfoHeaderView.swift, Stepic/Sources/Modules/CourseList/CourseListInteractor.swift, Stepic/Sources/Modules/CourseList/CourseListPresenter.swift, Stepic/Sources/Modules/CourseList/InputOutput/CourseListOutputProtocol.swift, Stepic/Sources/Modules/ExploreSubmodules/CourseListsCollection/CourseListsCollectionDataFlow.swift, Stepic/Sources/Modules/ExploreSubmodules/CourseListsCollection/CourseListsCollectionInteractor.swift, Stepic/Sources/Modules/FullscreenCourseList/FullscreenCourseListDataFlow.swift, Stepic/Sources/Modules/FullscreenCourseList/FullscreenCourseListInteractor.swift, Stepic/Sources/Modules/FullscreenCourseList/FullscreenCourseListPresenter.swift, Stepic/Sources/Modules/FullscreenCourseList/FullscreenCourseListViewController.swift, Stepic/en.lproj/Localizable.strings, Stepic/ru.lproj/Localizable.strings
**Задача**: [#APPS-2303](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2303)
**Описание**:
Для платных курсов все кнопки, которые ведут на энролл для обычных курсов, ведут в веб.
=> Open paid courses in web view

Stepic/Sources/Frameworks/ContentProcessor/ContentProcessingRule.swift, Stepic/Sources/Frameworks/ContentProcessor/ContentProcessor.swift, Stepic/Sources/Frameworks/ContentProcessor/HTMLExtractor.swift
**Задача**: [#APPS-2314](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2314)
**Описание**:
У изображений в степах удаляется принудительно заданная высота.
=> Fix images aspect ratio

Stepic/Sources/Modules/Quizzes/BaseQuiz/BaseQuizViewController.swift
**Задача**: [#APPS-2359](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2359)
**Описание**:
Добавили обновление текущего ответа пользователя на задачу после ее правильного решения.
=> Update current reply on data state change

Stepic.xcodeproj/project.pbxproj, Stepic/MatchingQuizViewController.swift, Stepic/SortingQuizViewController.swift, Stepic/Sources/Extensions/String+HTMLEscape.swift
**Задача**: [#APPS-2164](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2164)
**Описание**:
Добавили HTML-escaping для matching & sorting квизов.
=> HTML escape matching & sorting quizzes

Stepic/Sources/Modules/NewStep/NewStepViewController.swift, Stepic/WebStepViewController.swift
**Задача**: [#APPS-2365](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2365)
**Описание**:
Выпилили использование fill blanks квиза.
=> Remove fill blanks quiz

Stepic/Sources/Frameworks/ContentProcessor/ProcessedContentTextView.swift, Stepic/Sources/Modules/Quizzes/BaseQuiz/BaseQuizView.swift, Stepic/Sources/Modules/Quizzes/BaseQuiz/BaseQuizViewController.swift, Stepic/Sources/Modules/Quizzes/BaseQuiz/Views/QuizFeedbackView.swift
**Задача**: [#APPS-2368](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2368)
**Описание**:
Добавили поддержку детектирования и открытия ссылок в фидбеке квиза. Пока начиная от iOS 10.
=> Detect links inside of the quiz feedback

Podfile, Podfile.lock, Stepic.xcodeproj/project.pbxproj, Stepic/AlamofireRequestsLogger.swift, Stepic/AppDelegate.swift, Stepic/ProgressesAPI.swift, Stepic/Sources/Services/Models/Network/ProgressesNetworkService.swift, Stepic/Unit.swift
**Задача**: [#APPS-47](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-47)
**Описание**:
- Исправили запрос отсутствующих прогрессов вида:
* https://stepic.org/api/progresses?ids[]=&ids[]=&ids[]=&ids[]=&ids[]=&ids[]=
* https://stepic.org/api/progresses?
- Обновили Alamofire до версии 4.8.2
- Добавили логирование API запрос
=> Fix request progresses with empty ids

Stepic/StepicVideoPlayerViewController.swift
**Задача**: [#APPS-100](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-100)
**Описание**:
Добавили автоматическое скрытие контролов через 4500 мс.
=> Hide video player controls automatically

Stepic/Sources/Modules/Quizzes/NewCodeQuiz/Views/CodeEditor/CodeEditorView.swift, Stepic/Sources/Modules/Quizzes/NewCodeQuizFullscreen/Tabs/NewCodeQuizFullscreenCodeViewController.swift
**Описание**:
Добавили отображение текущего языка программирования в полноэкранном режиме.
=> Show language name for fullscreen code quiz

Stepic/CertificatesPresenter.swift, Stepic/CertificatesViewController.swift, Stepic/DeepLinkRouter.swift
**Задача**: [#APPS-2395](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2395)
**Описание**:
Добавили поддержку deep linka сертификатов.
=> Handle certificates deep link

Stepic.xcodeproj/project.pbxproj, Stepic/Sources/Modules/Quizzes/BaseQuiz/BaseQuizPresenter.swift, Stepic/Sources/Modules/Quizzes/NewCodeQuiz/NewCodeQuizView.swift, Stepic/Sources/Modules/Quizzes/NewCodeQuizFullscreen/NewCodeQuizFullscreenDataFlow.swift, Stepic/Sources/Modules/Quizzes/NewCodeQuizFullscreen/NewCodeQuizFullscreenInteractor.swift, Stepic/Sources/Modules/Quizzes/NewCodeQuizFullscreen/NewCodeQuizFullscreenPresenter.swift, Stepic/Sources/Modules/Quizzes/NewCodeQuizFullscreen/NewCodeQuizFullscreenViewController.swift, Stepic/Sources/Modules/Quizzes/NewCodeQuizFullscreen/Tabs/Instruction/NewCodeQuizFullscreenInstructionViewController.swift, Stepic/Sources/Modules/Quizzes/NewCodeQuizFullscreen/Tabs/NewCodeQuizFullscreenCodeViewController.swift, Stepic/Sources/Modules/Quizzes/NewCodeQuizFullscreen/Tabs/NewCodeQuizFullscreenSubmoduleProtocol.swift
**Задача**: [#APPS-2399](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2399), [#APPS-2400](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2400)
**Описание**:
- В полноэкранном режиме кода пропадает введенный код при переключении на экран с инструкциями
- После отправки неправильного ответа приходится перезапускать весь квиз заново
=> New code quiz fixes

Stepic/SocialAuthViewController.swift, Stepic/en.lproj/Localizable.strings, Stepic/ru.lproj/Localizable.strings
**Задача**: [#APPS-1943](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1943)
**Описание**:
Добавили кастомное сообщение об ошибке при отсутствии почты при авторизации через соц. сети.
=> Social signup without email message

Stepic/NotificationReactionHandler.swift, Stepic/TabBarRouter.swift
**Задача**: [#APPS-2418](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2418)
**Описание**:
Пофиксили краш при попытке перехода по баннеру уведомления.
=> Fix deep link routing

Stepic.xcodeproj/project.pbxproj, Stepic/ContinueActionButton.swift, Stepic/Course+CoreDataProperties.swift, Stepic/Course.swift, Stepic/LastStepRouter.swift, Stepic/Model.xcdatamodeld/.xccurrentversion, Stepic/Model.xcdatamodeld/Model_course_can_continue.xcdatamodel/contents, Stepic/Sources/Modules/CourseInfo/CourseInfoHeaderViewModel.swift, Stepic/Sources/Modules/CourseInfo/CourseInfoPresenter.swift, Stepic/Sources/Modules/CourseInfo/Views/CourseInfoHeaderView.swift
**Задача**: [#APPS-2425](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2425)
**Описание**:
Улучшили обработку действия "продолжить учиться" для недоступных курсов.
=> Improve course continue learning

Stepic/Sources/Modules/Quizzes/NewCodeQuiz/Views/CodeEditor/CodeTextViewLayoutManager.swift
**Задача**: [#APPS-2423](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2423)
**Описание**:
=> Add init() initializer for CodeTextViewLayoutManager

Stepic.xcodeproj/project.pbxproj, Stepic/ContinueActionButton.swift, Stepic/Course+CoreDataProperties.swift, Stepic/Course.swift, Stepic/Info.plist, Stepic/LastStepRouter.swift, Stepic/Model.xcdatamodeld/.xccurrentversion, Stepic/Model.xcdatamodeld/Model_course_can_continue.xcdatamodel/contents, Stepic/Sources/Modules/CourseInfo/CourseInfoHeaderViewModel.swift, Stepic/Sources/Modules/CourseInfo/CourseInfoPresenter.swift, Stepic/Sources/Modules/CourseInfo/Views/CourseInfoHeaderView.swift, Stepic/Sources/Modules/NewLesson/NewLessonDataFlow.swift, Stepic/Sources/Modules/NewLesson/NewLessonInteractor.swift, Stepic/Sources/Modules/NewLesson/NewLessonPresenter.swift, Stepic/Sources/Modules/NewLesson/NewLessonViewController.swift, Stepic/Sources/Modules/Quizzes/NewCodeQuiz/Views/CodeEditor/CodeTextViewLayoutManager.swift, StepicTests/Info.plist, StickerPackExtension/Info.plist
- Fix code quiz crash on copy and paste [#515](https://github.com/StepicOrg/stepik-ios/pull/515)
- Fix crash on lesson navigation [#516](https://github.com/StepicOrg/stepik-ios/pull/516)
- Improve course continue learning [#517](https://github.com/StepicOrg/stepik-ios/pull/517)
=> Release 1.91

Stepic.xcodeproj/project.pbxproj, Stepic/Block+CoreDataProperties.swift, Stepic/Block.swift, Stepic/Model.xcdatamodeld/.xccurrentversion, Stepic/Model.xcdatamodeld/Model_block_remove_animation.xcdatamodel/contents
**Задача**: [#APPS-2429](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2429)
**Описание**:
Убрали использование аттрибута `animation` в steps.block.
=> Remove animation attribute

Stepic.xcodeproj/xcshareddata/xcschemes/Stepic.xcscheme
**Задача**: [#APPS-2440](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2440)
**Описание**:
Добавили отображение покрытия кода тестами.
=> Generate code coverage

Stepic/Sources/Modules/CourseInfo/CourseInfoPresenter.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/CourseInfoTabSyllabusPresenter.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/CourseInfoTabSyllabusViewModel.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/Views/Section/CourseInfoTabSyllabusSectionView.swift, Stepic/Sources/Modules/CourseList/CourseListPresenter.swift, Stepic/Sources/Modules/ExploreSubmodules/ContinueCourse/ContinueCoursePresenter.swift
**Задача**: [#APPS-2433](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2433)
**Описание**:
Заменили числовые индикации прогресса на score / cost.
=> Course score cost progress

Stepic.xcodeproj/project.pbxproj, Stepic/CodeLanguages.swift, Stepic/Course+CoreDataProperties.swift, Stepic/LastCodeLanguage+CoreDataProperties.swift, Stepic/LastCodeLanguage.swift, Stepic/Model.xcdatamodeld/.xccurrentversion, Stepic/Model.xcdatamodeld/Model_last_code_language.xcdatamodel/contents, Stepic/Sources/Modules/Quizzes/NewCodeQuiz/NewCodeQuizAssembly.swift, Stepic/Sources/Modules/Quizzes/NewCodeQuiz/NewCodeQuizInteractor.swift, Stepic/Sources/Modules/Quizzes/NewCodeQuiz/NewCodeQuizProvider.swift, Stepic/Sources/Services/CodeLanguageSuggestionsService.swift
**Задача**: [#APPS-2401](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2401)
**Описание**:
Добавили автоматический выбор языка программирования.
=> Code quiz autoselect language

Stepic/PaginationView.swift, Stepic/Sources/Modules/CourseList/CourseListDataFlow.swift, Stepic/Sources/Modules/CourseList/CourseListInteractor.swift, Stepic/Sources/Modules/CourseList/CourseListPresenter.swift, Stepic/Sources/Modules/CourseList/CourseListViewController.swift, Stepic/Sources/Modules/CourseList/Provider/CourseListProvider.swift
**Задача**: [#APPS-2411](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2411)
**Описание**:
Добавили подгрузку следующих страниц в курс-листах.
=> Course list pagination

Stepic/Analytics/AmplitudeAnalyticsEvents.swift, Stepic/Analytics/AnalyticsEvents.swift, Stepic/Sources/Modules/SettingsSubmodules/SettingsStepFontSize/SettingsStepFontSizeInteractor.swift
**Задача**: [#APPS-2443](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2443)
**Описание**:
Добавили аналитику выбора размера текста.
=> Font size analytics

Stepic.xcodeproj/project.pbxproj, Stepic/StepicVideoPlayerViewController.swift
**Задача**: [#APPS-534](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-534)
**Описание**:
Изменили глобальное сохранение настройки качества видео при просмотре - настройка изменяется только если пользователь изменил ее явно.
=> Change watching video quality only on user-initiated action

Podfile, Podfile.lock, Stepic/PersonalDeadlinesService.swift, Stepic/Sources/Modules/CourseList/CourseListInteractor.swift, Stepic/StorageData.swift, Stepic/StorageRecord.swift, Stepic/StorageRecordsAPI.swift
**Задача**: [#APPS-2456](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2456)
**Описание**:
Перешли на оптимизированный запрос на StorageRecords.
=> Use optimized storage records query

Podfile, Podfile.lock, Stepic/Sources/Modules/NewStep/NewStepViewController.swift, Stepic/StepicVideoPlayerViewController.swift, Stepic/en.lproj/Localizable.strings, Stepic/ru.lproj/Localizable.strings
**Задача**: [#APPS-1843](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-1843)
**Описание**:
Добавили предупреждения об отсутствии интернета в видео-шагах и при возникновении ошибки воспроизведения видеоплеера.
=> Video player alerts

Stepic/DownloadTableViewCell.swift
**Задача**: [#APPS-2519](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2519)
**Описание**:
Установили минимальное значение индикации размера скачанного видеофайла в 1Мб.
=> Set min value of downloaded video file size to 1 megabyte

Stepic/Sources/Modules/Discussions/DiscussionsInteractor.swift
**Задача**: [#APPS-2525](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2525)
**Описание**:
Пофиксили краш при клике ссылки на дискуссию в уведомлениях.
=> Fix crash on discussion deep link

Stepic/CodePlaygroundManager.swift
**Задача**: [#APPS-2544](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2544)
**Описание**:
Исправили проблему с автокомплитом скобок в редакторе кода.
=> Fix code editor autocomplete

Stepic/Analytics/AmplitudeAnalyticsEvents.swift, Stepic/Sources/Modules/EditStep/EditStepAssembly.swift, Stepic/Sources/Modules/EditStep/EditStepInteractor.swift, Stepic/Sources/Modules/EditStep/EditStepProvider.swift
**Описание**:
Добавили аналитику на редактирование шагов.
=> Edit step analytics

Stepic/Sources/Modules/Discussions/DiscussionsViewController.swift, Stepic/Sources/Modules/Discussions/Views/Cell/DiscussionsCellView.swift, Stepic/Sources/Modules/Discussions/Views/Cell/DiscussionsTableViewCell.swift, Stepic/Sources/Modules/Discussions/Views/DiscussionsTableViewDataSource.swift
**Задача**: [#APPS-2545](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2545)
**Описание**:
- Кликабельность комментариев с LaTeX.
- Открытие изображений в полноэкранном режиме.
=> Discussions handle click on LaTeX

Stepic/Sources/Modules/Discussions/DiscussionsInteractor.swift, Stepic/Sources/Modules/Discussions/DiscussionsViewController.swift
**Задача**: [#APPS-2559](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2559)
**Описание**:
Исправили краш при изменении режима сортировки комментариев, если discussion proxy не был получен.
=> Fix crash on discussions sort type update

Stepic.xcodeproj/project.pbxproj, Stepic/Block+CoreDataProperties.swift, Stepic/Info.plist, StepicTests/BlockTypeSpec.swift, StepicTests/Info.plist, StepicTests/NewStepTests/NewStepViewControllerMock.swift, StickerPackExtension/Info.plist
**Задача**: [#APPS-2560](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2560)
**Описание**:
Исправили проблему, когда не отображались квизы freeAnswer/math/sorting/matching.
=> Hotfix 1.103.1

Stepic.xcodeproj/project.pbxproj, Stepic/Block+CoreDataProperties.swift, Stepic/CardsStepsPresenter.swift, Stepic/Lesson.swift, Stepic/Model.xcdatamodeld/.xccurrentversion, Stepic/Model.xcdatamodeld/Model_step_passed_by_correct_ratio.xcdatamodel/contents, Stepic/QuizPresenter.swift, Stepic/Services/DeepLinks/DeepLinkRouter.swift, Stepic/Sources/Modules/NewLesson/NewLessonInteractor.swift, Stepic/Sources/Modules/NewStep/NewStepPresenter.swift, Stepic/Sources/Modules/NewStep/NewStepView.swift, Stepic/Sources/Modules/NewStep/NewStepViewModel.swift, Stepic/Sources/Modules/NewStep/Views/StepControlsView.swift, Stepic/Sources/Modules/NewStep/Views/StepStatisticsView.swift, Stepic/Sources/Modules/Quizzes/BaseQuiz/BaseQuizPresenter.swift, Stepic/Sources/Modules/Quizzes/NewCodeQuiz/NewCodeQuizProvider.swift, Stepic/Step+CoreDataProperties.swift, Stepic/Step.swift, Stepic/en.lproj/Localizable.strings, Stepic/ru.lproj/Localizable.strings
**Задача**: [#APPS-2556](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2556)
**Описание**:
Добавили отображение статистики задачи:
- количество решивших
- процент успеха
=> Display step statistics

Podfile.lock, Stepic.xcodeproj/project.pbxproj, Stepic/Analytics/Events/AnalyticsEvents.swift, Stepic/Sources/Helpers/FormatterHelper.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/CourseInfoTabSyllabusAssembly.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/CourseInfoTabSyllabusDataFlow.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/CourseInfoTabSyllabusInteractor.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/CourseInfoTabSyllabusPresenter.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/CourseInfoTabSyllabusViewModel.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/Provider/SyllabusDownloadsService.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/Views/Cell/CourseInfoTabSyllabusCellView.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/Views/CourseInfoTabSyllabusView.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/Views/Header/CourseInfoTabSyllabusHeaderView.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/Views/Section/CourseInfoTabSyllabusSectionView.swift, Stepic/Sources/Modules/Downloads/DownloadsAssembly.swift, Stepic/Sources/Modules/Downloads/DownloadsDataFlow.swift, Stepic/Sources/Modules/Downloads/DownloadsInteractor.swift, Stepic/Sources/Modules/Downloads/DownloadsPresenter.swift, Stepic/Sources/Modules/Downloads/DownloadsProvider.swift, Stepic/Sources/Services/StorageUsageService.swift, Stepic/Sources/Views/DownloadControlView.swift, Stepic/en.lproj/Localizable.strings, Stepic/ru.lproj/Localizable.strings, StepicTests/NewStepTests/NewStepViewControllerMock.swift
**Задача**: [#APPS-2537](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2537)
**Описание**:
Всё, что ещё осталось пофиксить в загрузках курсов.
=> Course syllabus downloads improvements

Podfile, Podfile.lock
[Release notes](https://github.com/realm/SwiftLint/releases/tag/0.38.0).
=> Update SwiftLint from 0.37.0 to 0.38.0

Stepic/Sources/Modules/CourseInfo/CourseInfoViewController.swift
**Задача**: [#APPS-2304](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2304)
**Описание**:
"Продолжить учиться" после авторизации на экране курса.
=> Continue learning after authorization from course info

Stepic.xcodeproj/project.pbxproj, Stepic/Model.xcdatamodeld/.xccurrentversion, Stepic/Model.xcdatamodeld/Model_discount_policy.xcdatamodel/contents, Stepic/Section+CoreDataProperties.swift, Stepic/Section.swift, Stepic/Sources/Common/DiscountingPolicy.swift, Stepic/Sources/Modules/NewLesson/NewLessonInteractor.swift, Stepic/Sources/Modules/Quizzes/BaseQuiz/BaseQuizInteractor.swift, Stepic/Sources/Modules/Quizzes/BaseQuiz/BaseQuizPresenter.swift, Stepic/Sources/Modules/Quizzes/BaseQuiz/BaseQuizView.swift, Stepic/Sources/Modules/Quizzes/BaseQuiz/BaseQuizViewController.swift, Stepic/Sources/Modules/Quizzes/BaseQuiz/BaseQuizViewModel.swift, Stepic/Sources/Modules/Quizzes/NewChoiceQuiz/Views/NewChoiceQuizView.swift, Stepic/Sources/Modules/Quizzes/NewCodeQuiz/NewCodeQuizView.swift, Stepic/Sources/Modules/Quizzes/NewFreeAnswerQuiz/NewFreeAnswerQuizView.swift, Stepic/Sources/Modules/Quizzes/NewMatchingQuiz/Views/NewMatchingQuizView.swift, Stepic/Sources/Modules/Quizzes/NewSortingQuiz/Views/NewSortingQuizView.swift, Stepic/Sources/Modules/Quizzes/NewStringQuiz/NewStringQuizView.swift, Stepic/en.lproj/Localizable.strings, Stepic/ru.lproj/Localizable.strings
**Задача**: [#APPS-2360](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2360)
**Описание**:
Добавили отображение дисконтирования на экраше шага.
=> Discount policy

Podfile, Podfile.lock, Stepic.xcodeproj/project.pbxproj, Stepic/Info.plist, Stepic/Model.xcdatamodeld/.xccurrentversion, Stepic/Model.xcdatamodeld/Model_discount_policy.xcdatamodel/contents, Stepic/Section+CoreDataProperties.swift, Stepic/Section.swift, Stepic/Sources/Common/DiscountingPolicy.swift, Stepic/Sources/Modules/CourseInfo/CourseInfoViewController.swift, Stepic/Sources/Modules/NewLesson/NewLessonInteractor.swift, Stepic/Sources/Modules/Quizzes/BaseQuiz/BaseQuizInteractor.swift, Stepic/Sources/Modules/Quizzes/BaseQuiz/BaseQuizPresenter.swift, Stepic/Sources/Modules/Quizzes/BaseQuiz/BaseQuizView.swift, Stepic/Sources/Modules/Quizzes/BaseQuiz/BaseQuizViewController.swift, Stepic/Sources/Modules/Quizzes/BaseQuiz/BaseQuizViewModel.swift, Stepic/Sources/Modules/Quizzes/NewChoiceQuiz/Views/NewChoiceQuizView.swift, Stepic/Sources/Modules/Quizzes/NewCodeQuiz/NewCodeQuizView.swift, Stepic/Sources/Modules/Quizzes/NewFreeAnswerQuiz/NewFreeAnswerQuizView.swift, Stepic/Sources/Modules/Quizzes/NewMatchingQuiz/Views/NewMatchingQuizView.swift, Stepic/Sources/Modules/Quizzes/NewSortingQuiz/Views/NewSortingQuizView.swift, Stepic/Sources/Modules/Quizzes/NewStringQuiz/NewStringQuizView.swift, Stepic/Unit.swift, Stepic/en.lproj/Localizable.strings, Stepic/ru.lproj/Localizable.strings, StepicTests/Info.plist, StickerPackExtension/Info.plist
- Display discounting policy [#589](https://github.com/StepicOrg/stepik-ios/pull/589)
- Update SwiftLint from 0.37.0 to 0.38.0 [#585](https://github.com/StepicOrg/stepik-ios/pull/585)
- Update SDWebImage from 5.3.3 to 5.4.0 [#587](https://github.com/StepicOrg/stepik-ios/pull/587)
- Continue learning after authorization from course info [#588](https://github.com/StepicOrg/stepik-ios/pull/588)
- None
=> Release 1.105

Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/CourseInfoTabSyllabusDataFlow.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/CourseInfoTabSyllabusInteractor.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/CourseInfoTabSyllabusPresenter.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/CourseInfoTabSyllabusViewModel.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/Views/CourseInfoTabSyllabusView.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/Views/Header/CourseInfoTabSyllabusHeaderView.swift
**Задача**: [#APPS-2305](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2305)
**Описание**:
Блокирование кнопки создания персонального распиания, когда не записан на курс.
=> Fix personal deadlines enabled state

Stepic/Sources/Frameworks/SettingsTable/SettingsTableView.swift, Stepic/Sources/Frameworks/SettingsTable/Views/SettingsTableSectionFooterView.swift
**Задача**: [#APPS-2586](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2586)
**Описание**:
Исправили проблему с тем, что текст в нижних сносках секций обрезался.
=> Fix profile edit section footer height

Stepic.xcodeproj/project.pbxproj, Stepic/Model.xcdatamodeld/.xccurrentversion, Stepic/Model.xcdatamodeld/Model_required_section.xcdatamodel/contents, Stepic/Section+CoreDataProperties.swift, Stepic/Section.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/CourseInfoTabSyllabusPresenter.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/CourseInfoTabSyllabusViewModel.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/Views/Section/CourseInfoTabSyllabusSectionView.swift, Stepic/en.lproj/Localizable.strings, Stepic/ru.lproj/Localizable.strings
**Задача**: [#APPS-2430](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2430)
**Описание**:
Добавили отображение информации про открытие по условию в секциях.
=> Display section requirements

Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/CourseInfoTabSyllabusInteractor.swift
**YouTrack task**: [#APPS-2605](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2605)
Hides personal deadlines tooltip when the corresponding button disabled.
=> Fix personal deadlines tooltip visibility

.github/pull_request_template.txt
Updates pull request template.
=> Update pull request template

Stepic/Analytics/Events/AnalyticsEvents.swift, Stepic/Block+CoreDataProperties.swift, Stepic/Sources/Controllers/StyledNavigationController.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/Provider/SyllabusDownloadsService.swift, Stepic/Sources/Modules/Discussions/DiscussionsInteractor.swift, Stepic/Sources/Modules/Discussions/Views/DiscussionsTableViewDataSource.swift, Stepic/Sources/Modules/EditStep/EditStepInteractor.swift, Stepic/Sources/Modules/NewLesson/NewLessonPresenter.swift, Stepic/Sources/Modules/NewLesson/NewLessonViewController.swift, Stepic/Sources/Modules/NewLesson/NewLessonViewModel.swift, Stepic/Sources/Modules/NewStep/NewStepDataFlow.swift, Stepic/Sources/Modules/NewStep/NewStepPresenter.swift, StepicTests/NewStepTests/NewStepViewControllerMock.swift
**YouTrack task**: [#APPS-2591](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2591)
- Fix an issue when not parsed `BlockType`s being presented like theory.
- Hide step statistics for unsupported quizzes.
=> Fix table quiz presented like theory

Stepic/SettingsMenuBlock.swift, Stepic/SettingsPresenter.swift, Stepic/SettingsViewController.swift, Stepic/en.lproj/Localizable.strings, Stepic/ru.lproj/Localizable.strings
**YouTrack task**: [#APPS-2600](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2600)
- Rearrange settings categories.
- Ability to delete all content.
=> Delete all content via settings

Stepic.xcodeproj/project.pbxproj, Stepic/Images.xcassets/video player/play-next.imageset/Contents.json, Stepic/Images.xcassets/video player/play-next.imageset/play-next.pdf, Stepic/Player.swift, Stepic/SettingsMenuBlock.swift, Stepic/SettingsPresenter.swift, Stepic/SettingsViewController.swift, Stepic/Sources/Modules/NewLesson/NewLessonDataFlow.swift, Stepic/Sources/Modules/NewLesson/NewLessonInteractor.swift, Stepic/Sources/Modules/NewLesson/NewLessonPresenter.swift, Stepic/Sources/Modules/NewLesson/NewLessonViewController.swift, Stepic/Sources/Modules/NewStep/InputOutput/NewStepInputProtocol.swift, Stepic/Sources/Modules/NewStep/InputOutput/NewStepOutputProtocol.swift, Stepic/Sources/Modules/NewStep/NewStepDataFlow.swift, Stepic/Sources/Modules/NewStep/NewStepInteractor.swift, Stepic/Sources/Modules/NewStep/NewStepPresenter.swift, Stepic/Sources/Modules/NewStep/NewStepViewController.swift, Stepic/Sources/Services/Managers/AutoplayStorageManager.swift, Stepic/Sources/Views/PlayNextCircleControlView.swift, Stepic/StepicVideoPlayerViewController.swift, Stepic/StepikVideoPlayerViewController.swift, Stepic/StepikVideoPlayerViewController.xib, Stepic/SwitchMenuBlockTableViewCell.xib, Stepic/VideoRate.swift, Stepic/en.lproj/Localizable.strings, Stepic/ru.lproj/Localizable.strings, StepicTests/NewStepTests/NewStepViewControllerMock.swift
**YouTrack task**: [#APPS-2588](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2588)
- Auto-transition to the next step on video end.
=> Autoplay next step

Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabInfo/CourseInfoTabInfoInteractor.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabInfo/Views/Blocks/CourseInfoTabInfoHeaderBlockView.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabInfo/Views/CourseInfoTabInfoView.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabReviews/CourseInfoTabReviewsInteractor.swift, Stepic/Sources/Modules/NewStep/NewStepView.swift, Stepic/Sources/Views/ScrollableStackView.swift, Stepic/StepikURLSessionConfiguration.swift
**YouTrack task**: [#APPS-2427](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2427)
- Reduce `timeoutIntervalForRequest` from 15 sec to 10 sec.
- Present existing course info cache data firstly.
- Firstly present cached course reviews.
=> Course info bad network enhancements

Stepic/FullHeightTableView.swift
**YouTrack task**: [#APPS-2637](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2637)
- Fix an issue with not visible choices in adaptive mode on iOS 13.*.
=> Fix not visible choices in adaptive mode

Stepic/PinsMapView.swift
**YouTrack task**: [#APPS-2639](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2639)
- Display the same number of the months for X series devices like for Plus devices.
=> Support X series devices in pins map view

Stepic/Analytics/AnalyticsUserProperties.swift, Stepic/AppDelegate.swift, Stepic/Info.plist
**YouTrack task**: [#APPS-2654](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2654)
- Add dark mode analytics
=> Dark mode analytics

README.md
- Add download on the App Store badge.
=> Add download on the App Store badge

Stepic/Sources/Modules/Discussions/Views/DiscussionsSolutionControl.swift
Updates constraints to make the solution icon smaller.
=> Fix discussions solution control constraints

Stepic/Sources/Modules/Lesson/LessonInteractor.swift
**YouTrack task**: [#APPS-2668](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2668)
-  Shows error placeholder on empty steps.
=> Show error placeholder on empty steps

Stepic/Sources/Frameworks/Downloader/Downloader.swift, StepicTests/DownloaderTests.swift
**YouTrack task**: [#APPS-2669](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2669)
- Adds synchronization for Downloader's public API.
=> Downloader public API synchronization

Stepic.xcodeproj/project.pbxproj, Stepic/CommentsAPI.swift, Stepic/Discussions/Comment.swift, Stepic/Sources/Modules/Discussions/DiscussionsDataFlow.swift, Stepic/Sources/Modules/Discussions/DiscussionsInteractor.swift, Stepic/Sources/Modules/Discussions/DiscussionsPresenter.swift, Stepic/Sources/Modules/Discussions/DiscussionsViewController.swift, Stepic/Sources/Modules/Discussions/Views/Cell/DiscussionsCellView.swift, Stepic/Sources/Modules/Discussions/Views/Cell/DiscussionsTableViewCell.swift, Stepic/Sources/Modules/Discussions/Views/DiscussionsSolutionControl.swift, Stepic/Sources/Modules/Step/StepViewController.swift, Stepic/Sources/Modules/Submissions/InputOutput/SubmissionsOutputProtocol.swift, Stepic/Sources/Modules/Submissions/SubmissionsInteractor.swift, Stepic/Sources/Modules/WriteComment/Views/WriteCommentSolutionControl.swift, Stepic/Sources/Modules/WriteComment/WriteCommentAssembly.swift, Stepic/Sources/Modules/WriteComment/WriteCommentDataFlow.swift, Stepic/Sources/Modules/WriteComment/WriteCommentInteractor.swift, Stepic/Sources/Modules/WriteComment/WriteCommentPresenter.swift, Stepic/Sources/Modules/WriteComment/WriteCommentProvider.swift, Stepic/Sources/Modules/WriteComment/WriteCommentView.swift, Stepic/Sources/Modules/WriteComment/WriteCommentViewController.swift, Stepic/Sources/Modules/WriteComment/WriteCommentViewModel.swift, Stepic/Sources/Services/Models/Network/CommentsNetworkService.swift, Stepic/en.lproj/Localizable.strings, Stepic/ru.lproj/Localizable.strings
**YouTrack task**: [#APPS-2615](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2615)
- Post solutions to the solutions forum.
=> Post solution

Stepic.xcodeproj/project.pbxproj, Stepic/Analytics/Events/AmplitudeAnalyticsEvents.swift, Stepic/Analytics/SplitTests/ActiveTests/ActiveSplitTestsContainer.swift, Stepic/Analytics/SplitTests/ActiveTests/CourseListSeeAllTextSplitTest.swift, Stepic/Sources/Modules/Explore/View/CourseListContainerViewFactory.swift, Stepic/Sources/Modules/Explore/View/ExploreBlockHeaderView.swift, Stepic/Sources/Modules/ExploreSubmodules/ContentLanguageSwitch/Views/ContentLanguageSwitchView.swift, Stepic/Sources/Modules/ExploreSubmodules/CourseListsCollection/Views/CourseListsCollectionView.swift, Stepic/Sources/Modules/ExploreSubmodules/Tags/TagsView.swift, Stepic/Sources/Modules/Home/HomeViewController.swift, Stepic/en.lproj/Localizable.strings, Stepic/ru.lproj/Localizable.strings
**YouTrack task**: [#APPS-2695](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2695)
- Adds `course_list_see_all_text` A/B test.
=> Add A/B `course_list_see_all_text`

Stepic/AppDelegate.swift, Stepic/Discussions/Comment.swift, Stepic/Sources/Modules/Discussions/DiscussionsInteractor.swift, Stepic/Sources/Modules/Discussions/DiscussionsViewController.swift, Stepic/Sources/Modules/Discussions/Views/Cell/DiscussionsCellView.swift, Stepic/Sources/Modules/WriteComment/WriteCommentDataFlow.swift, Stepic/Sources/Modules/WriteComment/WriteCommentInteractor.swift, Stepic/Sources/Modules/WriteComment/WriteCommentPresenter.swift
**YouTrack task**: [#APPS-2691](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2691)
- Adds ability to reply for solutions.
=> Reply to solutions

Stepic/Sources/Modules/Quizzes/CodeQuiz/CodeQuizInteractor.swift, Stepic/Sources/Modules/Solution/SolutionViewController.swift
**YouTrack task**: [#APPS-2715](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2715)
- Fixes an issue with overwrites of the current user code after viewed solution.
=> Fix viewing solution overwrites current user code

README.md
- Removes outdated project setup instructions.
=> Remove project setup instructions in readme

Stepic/Sources/Modules/Step/Views/StepVideoPreviewView.swift, Stepic/StepikVideoPlayerViewController.swift, Stepic/en.lproj/Localizable.strings, Stepic/ru.lproj/Localizable.strings
**YouTrack task**: [#APPS-2735](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2735)
- Adds VoiceOver support for `StepVideoPreviewView` and `StepikVideoPlayerViewController`.
- Persists video player controls onscreen for VoiceOver users.
=> VoiceOver support for video steps

Stepic/CellWebViewHelper.swift, Stepic/ChoiceQuizTableViewCell.swift, Stepic/FullHeightWebView.swift, Stepic/QuizViewController.swift
**YouTrack task**: [#APPS-2732](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2732)
- Resolves [ITMS-90809: UIWebView API Deprecation](https://developer.apple.com/news/?id=12232019b).
=> Migrate UIWebView to WKWebView

Stepic/Base.lproj/LaunchScreen.xib
**YouTrack task**: [#APPS-2812](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2812)
- Removes text from the launch screen.
=> Remove text from launch screen

Stepic/stepikcontent.css
**YouTrack task**: [#APPS-2813](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2813)
- Updates link color in dark mode.
=> Dark mode link color

Stepic/stepikcontent.css
**YouTrack task**: [#APPS-2821](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2821)
- Add styles for tables in the dark mode environment.
=> Dark mode tables

Stepic.xcodeproj/project.pbxproj, Stepic/Legacy/Model/Entities/Profile/Profile+CoreDataProperties.swift, Stepic/Legacy/Model/Entities/User/User+CoreDataProperties.swift, Stepic/Legacy/Model/Entities/UserActivity/UserActivityEntity+CoreDataProperties.swift, Stepic/Legacy/Model/Entities/UserActivity/UserActivityEntity.swift, Stepic/Legacy/Model/Model.xcdatamodeld/.xccurrentversion, Stepic/Legacy/Model/Model.xcdatamodeld/Model_user_activity_v50.xcdatamodel/contents, Stepic/Legacy/Model/Network/Endpoints/ProfilesAPI.swift, Stepic/Legacy/Model/UserActivity.swift, Stepic/Sources/Services/Models/Network/ProfilesNetworkService.swift, Stepic/Sources/Services/Models/Persistence/ProfilesPersistenceService.swift, Stepic/Sources/Services/Models/Persistence/UserActivitiesPersistenceService.swift, Stepic/Sources/Services/Models/Persistence/UsersPersistenceService.swift
**YouTrack task**: [#APPS-2774](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2774)
- Adds persistence support for `user-activities` & services.
- Adds `users` persistence service.
- Adds `profiles` persistence service & fetch remote.
=> New profile services

Stepic/Legacy/Analytics/Events/AmplitudeAnalyticsEvents.swift, Stepic/Sources/Modules/CourseInfo/CourseInfoInteractor.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabInfo/CourseInfoTabInfoInteractor.swift, Stepic/Sources/Modules/CourseList/CourseListInteractor.swift
**YouTrack task**: [#APPS-2825](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2825)
- Adds `is_paid ` parameter for `Course preview screen opened` event.
- Adds `Buy course pressed` event.
=> Course buying analytics

Stepic.xcodeproj/project.pbxproj, Stepic/Legacy/Model/Entities/Course/Course+CoreDataProperties.swift, Stepic/Legacy/Model/Entities/Course/Course.swift, Stepic/Legacy/Model/Model.xcdatamodeld/.xccurrentversion, Stepic/Legacy/Model/Model.xcdatamodeld/Model_user_courses_actions_v51.xcdatamodel/contents, Stepic/Legacy/Model/Network/Endpoints/UserCoursesAPI.swift, Stepic/Legacy/Model/UserCourse.swift, Stepic/Sources/Modules/CourseInfo/CourseInfoAssembly.swift, Stepic/Sources/Modules/CourseInfo/CourseInfoDataFlow.swift, Stepic/Sources/Modules/CourseInfo/CourseInfoHeaderViewModel.swift, Stepic/Sources/Modules/CourseInfo/CourseInfoInteractor.swift, Stepic/Sources/Modules/CourseInfo/CourseInfoPresenter.swift, Stepic/Sources/Modules/CourseInfo/CourseInfoProvider.swift, Stepic/Sources/Modules/CourseInfo/CourseInfoViewController.swift, Stepic/Sources/Modules/CourseList/Provider/CourseListNetworkService.swift, Stepic/Sources/Modules/ExploreSubmodules/ContinueCourse/ContinueCourseProvider.swift, Stepic/Sources/Services/DataBackUpdateService.swift, Stepic/Sources/Services/Models/Network/UserCoursesNetworkService.swift, Stepic/en.lproj/Localizable.strings, Stepic/ru.lproj/Localizable.strings
**YouTrack task**: [#APPS-2759](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2759)
- Updates course `is_favorite` and `is_archived` states from the course screen.
=> Course info user courses actions

Podfile, Podfile.lock, Stepic.xcodeproj/project.pbxproj, Stepic/Legacy/Controllers/Profile/Profile/ProfilePresenter.swift, Stepic/Legacy/Model/Network/Endpoints/UserCoursesAPI.swift, Stepic/Sources/Modules/CourseList/CourseListAssembly.swift, Stepic/Sources/Modules/CourseList/CourseListInteractor.swift, Stepic/Sources/Modules/CourseList/Interactor/CourseListDataBackUpdateService.swift, Stepic/Sources/Modules/CourseList/Interactor/CourseListInteractor.swift, Stepic/Sources/Modules/CourseList/Provider/CourseListNetworkService.swift, Stepic/Sources/Modules/CourseList/Provider/CourseListTypes.swift, Stepic/Sources/Modules/ExploreSubmodules/ContinueCourse/ContinueCourseInteractor.swift, Stepic/Sources/Modules/Home/HomeViewController.swift, Stepic/Sources/Modules/HomeSubmodules/UserCourses/UserCoursesAssembly.swift, Stepic/Sources/Modules/HomeSubmodules/UserCourses/UserCoursesDataFlow.swift, Stepic/Sources/Modules/HomeSubmodules/UserCourses/UserCoursesInteractor.swift, Stepic/Sources/Modules/HomeSubmodules/UserCourses/UserCoursesPresenter.swift, Stepic/Sources/Modules/HomeSubmodules/UserCourses/UserCoursesProvider.swift, Stepic/Sources/Modules/HomeSubmodules/UserCourses/UserCoursesView.swift, Stepic/Sources/Modules/HomeSubmodules/UserCourses/UserCoursesViewController.swift, Stepic/Sources/Modules/Quizzes/NewSortingQuiz/Views/NewSortingQuizElementView.swift, Stepic/Sources/Services/DataBackUpdateService.swift, Stepic/en.lproj/Localizable.strings, Stepic/ru.lproj/Localizable.strings
**YouTrack task**: [#APPS-2771](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2771)
Show user courses with 3 tabs:
- All
- Favorite
- Archive
Fixes:
- `OptionSet` conformances
- `DataBackUpdateServiceDelegate` conformances
=> User courses

Stepic/Legacy/Analytics/AnalyticsUserProperties.swift
**YouTrack task**: [#APPS-2853](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2853)
Sets user profile id to AppMetrica & FirebaseAnalytics events.
=> Report user profile id to AppMetrica & FirebaseAnalytics

Stepic/Legacy/Analytics/Events/AmplitudeAnalyticsEvents.swift, Stepic/Legacy/Controllers/AdaptiveSteps/Helpers/AdaptiveStorageManager.swift, Stepic/Legacy/Controllers/Quizzes/BaseQuiz/QuizPresenter.swift, Stepic/Sources/Modules/Quizzes/BaseQuiz/BaseQuizAssembly.swift, Stepic/Sources/Modules/Quizzes/BaseQuiz/BaseQuizInteractor.swift
**YouTrack task**: [#APPS-2866](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2866)
Extends params for `Submission made` event:
- `submission`
- `is_adaptive`
=> Submission made analytics event with extended params

Stepic/Legacy/Model/Entities/User/User.swift
**YouTrack task**: [#APPS-2867](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2867)
Fixes JSON parsing for `User` model.
=> Fix profile description

Stepic.xcodeproj/project.pbxproj, Stepic/Legacy/Model/Network/Endpoints/CoursePaymentsAPI.swift, Stepic/Legacy/Model/PlainObjects/CoursePayment/CoursePayment.swift, Stepic/Sources/Services/Models/Network/CoursePaymentsNetworkService.swift
**YouTrack task**: [#APPS-2870](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2870)
- Adds `course-payments` API support.
=> Course payments API

Stepic.xcodeproj/project.pbxproj, Stepic/Legacy/Controllers/Certificates/CertificatesViewController.swift, Stepic/Legacy/Controllers/Quizzes/BaseQuiz/QuizViewController/QuizViewController.swift, Stepic/Legacy/Controllers/RegistrationSignIn/AuthEmail/EmailAuthViewController.swift, Stepic/Legacy/Controllers/RegistrationSignIn/AuthSocial/SocialAuthViewController.swift, Stepic/Legacy/Controllers/RegistrationSignIn/Registration/RegistrationViewController.swift, Stepic/Legacy/Model/Managers/WebControllerManager.swift, Stepic/Legacy/Model/Network/ApiRequest.swift, Stepic/Legacy/Model/Network/Endpoints/MagicLinksAPI.swift, Stepic/Legacy/Model/PlainObjects/MagicLink.swift, Stepic/Legacy/Model/StepikSession/StepikSession.swift, Stepic/Legacy/Services/DeepLinks/DeepLinkRouter.swift, Stepic/Legacy/TransitionRouters/LastStepRouter.swift, Stepic/Sources/Modules/BaseExplore/BaseExploreViewController.swift, Stepic/Sources/Modules/CourseInfo/CourseInfoViewController.swift, Stepic/Sources/Modules/Discussions/DiscussionsViewController.swift, Stepic/Sources/Modules/FullscreenCourseList/FullscreenCourseListViewController.swift, Stepic/Sources/Modules/Quizzes/BaseQuiz/BaseQuizViewController.swift, Stepic/Sources/Modules/Quizzes/CodeQuizFullscreen/Tabs/CodeQuizFullscreenInstruction/CodeQuizFullscreenInstructionViewController.swift, Stepic/Sources/Modules/Quizzes/NewMatchingQuiz/NewMatchingQuizViewController.swift, Stepic/Sources/Modules/Quizzes/NewSortingQuiz/NewSortingQuizViewController.swift, Stepic/Sources/Modules/Quizzes/UnsupportedQuiz/UnsupportedQuizDataFlow.swift, Stepic/Sources/Modules/Quizzes/UnsupportedQuiz/UnsupportedQuizInteractor.swift, Stepic/Sources/Modules/Quizzes/UnsupportedQuiz/UnsupportedQuizPresenter.swift, Stepic/Sources/Modules/Quizzes/UnsupportedQuiz/UnsupportedQuizViewController.swift, Stepic/Sources/Modules/Solution/SolutionViewController.swift, Stepic/Sources/Modules/Step/StepViewController.swift, Stepic/Sources/Services/Models/Network/MagicLinksNetworkService.swift
**YouTrack task**: [#APPS-2856](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2856)
Creates magic links for target URLs if needed when opening a URL on the web browser.
=> Magic links

Stepic/Sources/Modules/CourseList/CourseListViewController.swift, Stepic/Sources/Modules/CourseList/Views/CourseListView.swift, Stepic/Sources/Modules/CourseList/Views/Layouts/VerticalCourseListFlowLayout.swift
**YouTrack task**: [#APPS-2878](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2878)
Adds an adaptive number of columns for `VerticalCourseListView`.
=> Adaptive number of columns for VerticalCourseListView

Stepic/Sources/Modules/CourseList/CourseListViewController.swift, Stepic/Sources/Modules/CourseList/Views/CourseListView.swift, Stepic/Sources/Modules/CourseList/Views/Layouts/HorizontalCourseListFlowLayout.swift
**YouTrack task**: [#APPS-2877](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2877)
Adds an adaptive number of columns for `HorizontalCourseListView`.
=> Adaptive number of columns for HorizontalCourseListView

Stepic.xcodeproj/project.pbxproj, Stepic/Images.xcassets/chevron.right.imageset/Contents.json, Stepic/Images.xcassets/chevron.right.imageset/chevron.right.pdf, Stepic/Legacy/Extensions/UILabelExtensions.swift, Stepic/Legacy/Model/Entities/User/User+CoreDataProperties.swift, Stepic/Sources/Helpers/HTMLToAttributedStringConverter.swift, Stepic/Sources/Modules/NewProfile/NewProfileAssembly.swift, Stepic/Sources/Modules/NewProfile/NewProfileDataFlow.swift, Stepic/Sources/Modules/NewProfile/NewProfileInteractor.swift, Stepic/Sources/Modules/NewProfile/NewProfilePresenter.swift, Stepic/Sources/Modules/NewProfile/NewProfileSubmoduleProtocol.swift, Stepic/Sources/Modules/NewProfile/NewProfileView.swift, Stepic/Sources/Modules/NewProfile/NewProfileViewController.swift, Stepic/Sources/Modules/NewProfile/NewProfileViewModel.swift, Stepic/Sources/Modules/NewProfile/Views/Block/NewProfileBlockContainerView.swift, Stepic/Sources/Modules/NewProfile/Views/Block/NewProfileBlockHeaderView.swift, Stepic/Sources/Modules/NewProfileSubmodules/Details/NewProfileDetailsView.swift, Stepic/Sources/Modules/NewProfileSubmodules/Details/NewProfileDetailsViewController.swift, Stepic/Sources/Views/ShowAllButton.swift, Stepic/en.lproj/Localizable.strings, Stepic/ru.lproj/Localizable.strings
**YouTrack task**: [#APPS-2776](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2776)
- Adds `details` block
- Ability to detect links in HTML text and handle clicks
=> New profile details block

Stepic/Sources/Modules/CourseList/Interactor/CourseListDataBackUpdateService.swift
**YouTrack task**: [#APPS-2891](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2891)
- Handles course enrollment updates.
=> Handle course enrollment updates in user courses

Stepic.xcodeproj/project.pbxproj, Stepic/Info.plist, Stepic/Legacy/Model/Managers/WebControllerManager.swift, Stepic/Sources/Helpers/HTMLToAttributedStringConverter.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabInfo/CourseInfoTabInfoViewController.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabInfo/Views/Blocks/CourseInfoTabInfoTextBlockView.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabInfo/Views/CourseInfoTabInfoView.swift, StepicTests/Info.plist, StickerPackExtension/Info.plist
- Links highlighting in the course info tab [#730](https://github.com/StepicOrg/stepik-ios/pull/730)
- None
- None
=> Release 1.128

Stepic.xcodeproj/project.pbxproj, Stepic/Legacy/Helpers/Containers/Preferences/NotificationPreferencesContainer.swift, Stepic/Sources/Modules/NewProfile/NewProfileDataFlow.swift, Stepic/Sources/Modules/NewProfile/NewProfileViewController.swift, Stepic/Sources/Modules/NewProfileSubmodules/StreakNotifications/NewProfileStreakNotificationsAssembly.swift, Stepic/Sources/Modules/NewProfileSubmodules/StreakNotifications/NewProfileStreakNotificationsDataFlow.swift, Stepic/Sources/Modules/NewProfileSubmodules/StreakNotifications/NewProfileStreakNotificationsInteractor.swift, Stepic/Sources/Modules/NewProfileSubmodules/StreakNotifications/NewProfileStreakNotificationsPresenter.swift, Stepic/Sources/Modules/NewProfileSubmodules/StreakNotifications/NewProfileStreakNotificationsProvider.swift, Stepic/Sources/Modules/NewProfileSubmodules/StreakNotifications/NewProfileStreakNotificationsView.swift, Stepic/Sources/Modules/NewProfileSubmodules/StreakNotifications/NewProfileStreakNotificationsViewController.swift, Stepic/Sources/Modules/NewProfileSubmodules/StreakNotifications/NewProfileStreakNotificationsViewModel.swift, Stepic/Sources/Modules/NewProfileSubmodules/StreakNotifications/Views/NewProfileStreakNotificationsFooterView.swift, Stepic/Sources/Modules/NewProfileSubmodules/StreakNotifications/Views/NewProfileStreakNotificationsSwitchView.swift, Stepic/Sources/Modules/NewProfileSubmodules/StreakNotifications/Views/NewProfileStreakNotificationsTimeSelectionView.swift, Stepic/Sources/Services/Managers/StreakNotificationsStorageManager.swift, Stepic/en.lproj/Localizable.strings, Stepic/ru.lproj/Localizable.strings
**YouTrack task**: [#APPS-2782](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2782)
Adds streak notifications block.
=> New profile block streak notifications

Stepic/Sources/Modules/NewProfile/NewProfileInteractor.swift, Stepic/Sources/Modules/NewProfile/NewProfileSubmoduleProtocol.swift, Stepic/Sources/Modules/NewProfileSubmodules/Details/NewProfileDetailsViewController.swift, Stepic/Sources/Modules/NewProfileSubmodules/StreakNotifications/NewProfileStreakNotificationsInteractor.swift, Stepic/Sources/Modules/NewProfileSubmodules/UserActivity/NewProfileUserActivityDataFlow.swift, Stepic/Sources/Modules/NewProfileSubmodules/UserActivity/NewProfileUserActivityInteractor.swift, Stepic/Sources/Modules/NewProfileSubmodules/UserActivity/NewProfileUserActivityPresenter.swift, Stepic/Sources/Modules/NewProfileSubmodules/UserActivity/NewProfileUserActivityView.swift, Stepic/Sources/Modules/NewProfileSubmodules/UserActivity/Views/NewProfileUserActivityCurrentStreakView.swift
**YouTrack task**: [#APPS-2930](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2930)
- Hides solve today message when no streak for other user profiles.
=> Hide solve today for other user profile

Stepic/Legacy/Model/Network/Endpoints/CoursesAPI.swift, Stepic/Sources/Modules/CourseList/Provider/CourseListNetworkService.swift
**YouTrack task**: [#APPS-2919](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2919)
- Adds `is_cataloged` param for `CoursesAPI`.
- Updates `PopularCourseListNetworkService` fetch params.
=> Update popular course list filter

Stepic.xcodeproj/project.pbxproj, Stepic/Legacy/Model/Constants/Scripts/Scripts.plist, Stepic/Legacy/Model/Constants/Scripts/Scripts.swift, Stepic/Legacy/Services/DeepLinks/DeepLinkRoute.swift, Stepic/Sources/Frameworks/ContentProcessor/ContentProcessingInjection.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabInfo/CourseInfoTabInfoInteractor.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabInfo/CourseInfoTabInfoPresenter.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabInfo/CourseInfoTabInfoViewController.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabInfo/CourseInfoTabInfoViewModel.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabInfo/Views/Blocks/CourseInfoTabInfoAboutBlockView.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabInfo/Views/Blocks/CourseInfoTabInfoHeaderBlockView.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabInfo/Views/Blocks/CourseInfoTabInfoInstructorView.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabInfo/Views/Blocks/CourseInfoTabInfoTextBlockView.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabInfo/Views/CourseInfoTabInfoView.swift, Stepic/Sources/Services/Models/Repository/AchievementsRepository.swift, Stepic/course-info.css, StepicTests/DeepLinkRouteTests.swift
**YouTrack task**: [#APPS-2929](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2929)
- Makes `authors` block user interactable.
- Uses `ProcessedContentTextView` in `about` block if WebView support needed.
=> Course info tab info cosmetics

Stepic/Sources/Modules/Lesson/LessonPresenter.swift
**YouTrack task**: [#APPS-2932](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2932)
- Formats lesson's screen title with section & unit positions.
=> Lesson title with section & unit positions

Podfile, Podfile.lock, Stepic.xcodeproj/project.pbxproj, Stepic/Config.plist, Stepic/Info.plist, Stepic/Legacy/AppDelegate.swift, Stepic/Legacy/Controllers/RegistrationSignIn/AuthSocial/SocialAuthPresenter.swift, Stepic/Legacy/Controllers/RegistrationSignIn/AuthSocial/SocialAuthProviders.swift, Stepic/Legacy/Controllers/RegistrationSignIn/AuthSocial/SocialAuthViewController.swift, Stepic/Legacy/Model/Constants/ApplicationInfo/ApplicationInfo.swift, Stepic/Legacy/Model/Constants/ApplicationInfo/StepikApplicationsInfo.swift, Stepic/Legacy/Model/Network/SocialSDKProviders/GoogleIDSocialSDKProvider.swift
**YouTrack task**: [#APPS-2944](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2944)
- Fixes Sign in with Google.
- Installs `GoogleSignIn` library.
=> Fix Sign in with Google

Stepic.xcodeproj/project.pbxproj, Stepic/Legacy/Model/Entities/User/User+CoreDataProperties.swift, Stepic/Legacy/Model/Entities/User/User.swift, Stepic/Legacy/Model/Model.xcdatamodeld/.xccurrentversion, Stepic/Legacy/Model/Model.xcdatamodeld/Model_new_profile_organization_v57.xcdatamodel/contents, Stepic/Sources/Modules/CourseInfo/CourseInfoViewController.swift, Stepic/Sources/Modules/NewProfile/NewProfilePresenter.swift, Stepic/Sources/Modules/NewProfile/NewProfileViewController.swift, Stepic/Sources/Modules/NewProfile/NewProfileViewModel.swift, Stepic/Sources/Modules/NewProfile/Views/NewProfileCoverView.swift, Stepic/Sources/Modules/NewProfile/Views/NewProfileHeaderView.swift, Stepic/Sources/Modules/NewProfile/Views/NewProfileView.swift, Stepic/Sources/Modules/NewProfileSubmodules/Details/NewProfileDetailsView.swift, Stepic/Sources/Modules/NewProfileSubmodules/Details/NewProfileDetailsViewController.swift, Stepic/Sources/Modules/NewProfileSubmodules/Details/NewProfileDetailsViewModel.swift, Stepic/en.lproj/Localizable.strings, Stepic/ru.lproj/Localizable.strings
**YouTrack task**: [#APPS-2780](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2780)
- Adds stretchy header for organization profiles.
- Updates details block.
=> New profile organization container

Stepic.xcodeproj/project.pbxproj, Stepic/Legacy/Model/Entities/Lesson/Lesson+CoreDataProperties.swift, Stepic/Legacy/Model/Entities/Lesson/Lesson.swift, Stepic/Legacy/Model/Model.xcdatamodeld/.xccurrentversion, Stepic/Legacy/Model/Model.xcdatamodeld/Model_lessons_demo_access_v58.xcdatamodel/contents, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/CourseInfoTabSyllabusDataFlow.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/CourseInfoTabSyllabusInteractor.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/CourseInfoTabSyllabusPresenter.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/CourseInfoTabSyllabusViewModel.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/Views/Cell/CourseInfoTabSyllabusCellView.swift, Stepic/en.lproj/Localizable.strings, Stepic/ru.lproj/Localizable.strings
**YouTrack task**: [#APPS-2880](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2880)
- Adds demo access for lessons in paid courses.
=> Demo access for lessons in paid courses

Stepic/Sources/Modules/Lesson/LessonPresenter.swift, Stepic/Sources/Modules/Lesson/LessonViewController.swift, Stepic/Sources/Modules/Lesson/LessonViewModel.swift
**YouTrack task**: [#APPS-2727](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2727)
- Shows submissions alert action only for quizzes.
=> Fix show submissions alert action

Stepic/Sources/Services/Models/Persistence/AttemptsPersistenceService.swift, Stepic/Sources/Services/Models/Persistence/SubmissionsPersistenceService.swift
**YouTrack task**: [#APPS-2955](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2955)
- Fixes establish a relationship between submission and attempt.
=> Fix establish relationship between submission and attempt

Stepic/Legacy/Controllers/Certificates/CertificatesPresenter.swift, Stepic/Legacy/Model/DatabaseFetchService.swift, Stepic/Legacy/Model/Entities/Course/Course.swift, Stepic/Legacy/Model/Entities/CourseReview/CourseReview.swift, Stepic/Legacy/Model/Entities/Step/Step.swift, Stepic/Legacy/Model/Entities/Unit/Unit.swift, Stepic/Legacy/Model/Network/Endpoints/CoursesAPI.swift, Stepic/Legacy/Model/Network/Endpoints/StepsAPI.swift, Stepic/Legacy/Model/Network/Endpoints/UnitsAPI.swift, Stepic/Legacy/Services/DeepLinks/StepsControllerDeepLinkRouter.swift, Stepic/Sources/Extensions/Dispatch/DispatchQueue+Promise.swift
**YouTrack task**: [#APPS-2526](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2526)
- Synchronously performs Core Data's critical fetch requests on the main queue.
=> Fix Core Data crashes on fetch request

Stepic/Legacy/Analytics/AnalyticsUserProperties.swift
**YouTrack task**: [#APPS-2912](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2912)
- Reports current user profile active split test group to AppMetrica via a custom attribute.
=> AppMetrica split test group attribute

Stepic.xcodeproj/project.pbxproj, Stepic/Legacy/Controllers/AdaptiveSteps/CardStep/CardStepViewController.swift, Stepic/Sources/Helpers/FullscreenImageViewer.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabInfo/CourseInfoTabInfoViewController.swift, Stepic/Sources/Modules/Discussions/DiscussionsViewController.swift, Stepic/Sources/Modules/Quizzes/BaseQuiz/BaseQuizViewController.swift, Stepic/Sources/Modules/Quizzes/CodeQuizFullscreen/Tabs/CodeQuizFullscreenInstruction/CodeQuizFullscreenInstructionViewController.swift, Stepic/Sources/Modules/Quizzes/NewMatchingQuiz/NewMatchingQuizViewController.swift, Stepic/Sources/Modules/Quizzes/NewSortingQuiz/NewSortingQuizViewController.swift, Stepic/Sources/Modules/Step/StepViewController.swift, Stepic/en.lproj/Localizable.strings, Stepic/ru.lproj/Localizable.strings
**YouTrack task**: [#APPS-2730](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2730)
- Adds `FullscreenImageViewer` with the ability to show image via `URL` or `UIImage`.
- On error has ability to retry the request or close the current screen.
=> Fullscreen image viewer

Stepic.xcodeproj/project.pbxproj, Stepic/Legacy/Model/Entities/Course/Course+CoreDataProperties.swift, Stepic/Legacy/Model/Entities/Course/Course.swift, Stepic/Legacy/Model/Model.xcdatamodeld/.xccurrentversion, Stepic/Legacy/Model/Model.xcdatamodeld/Model_course_preview_lesson_id_v63.xcdatamodel/contents, Stepic/Sources/Modules/CourseInfo/CourseInfoDataFlow.swift, Stepic/Sources/Modules/CourseInfo/CourseInfoHeaderViewModel.swift, Stepic/Sources/Modules/CourseInfo/CourseInfoInteractor.swift, Stepic/Sources/Modules/CourseInfo/CourseInfoPresenter.swift, Stepic/Sources/Modules/CourseInfo/CourseInfoViewController.swift, Stepic/Sources/Modules/CourseInfo/Views/CourseInfoHeaderView.swift, Stepic/Sources/Modules/CourseInfo/Views/CourseInfoTryForFreeButton.swift, Stepic/Sources/Modules/CourseInfo/Views/CourseInfoView.swift, Stepic/en.lproj/Localizable.strings, Stepic/ru.lproj/Localizable.strings
**YouTrack task**: [#APPS-2938](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2938)
- Adds `CourseInfoTryForFreeButton`.
- Presents preview lesson on button click.
=> Button try paid course for free

Stepic/Legacy/Services/DeepLinks/DeepLinkRoute.swift, Stepic/Sources/Modules/Discussions/Views/Cell/DiscussionsCellView.swift, StepicTests/DeepLinkRouteTests.swift
**YouTrack task**: [#APPS-2592](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2592)
- Fixes `nameLabel` constraints.
- Fix lesson regular expression with query components.
=> Fix discussions name label constraints

Stepic/Sources/Modules/Discussions/Views/Cell/DiscussionsCellView.swift, Stepic/Sources/Modules/Discussions/Views/Cell/DiscussionsTableViewCell.swift, Stepic/Sources/Modules/Discussions/Views/DiscussionsTableViewDataSource.swift
**YouTrack task**: [#APPS-2898](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2898)
- Fixes links click handling in discussions by removing WebView touch gesture recognizer.
=> Fix links clicks in discussions

.swiftlint.yml, Gemfile, Gemfile.lock, Podfile, Podfile.lock, Stepic/Sources/Frameworks/Downloader/Downloader.swift, Stepic/Sources/Modules/CourseList/CourseListViewController.swift, Stepic/Sources/Services/ContentLanguage/ContentLanguageService.swift, fastlane/Fastfile
Bumps:
- [Firebase](https://github.com/firebase/firebase-ios-sdk) from 6.28.1 to 6.30.0
- [fastlane](https://github.com/fastlane/fastlane) from 2.156.0 to 2.156.1
- [SwiftLint](https://github.com/realm/SwiftLint) from 0.39.2 to 0.40.0
=> Update dependencies 1.137

Stepic/Legacy/TransitionRouters/LastStepRouter.swift
**YouTrack task**: [#APPS-2612](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2612)
- `LastStepRouter` fallbacks to the syllabus on any error.
=> Fallback to syllabus on continue learning error

Stepic/Legacy/Controllers/Notifications/NotificationsMarkAsReadButton/NotificationsMarkAsReadButton.swift, Stepic/Legacy/Controllers/Notifications/NotificationsViewController.swift
**YouTrack task**: [#APPS-2957](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2957)
=> Disable mark all as read button when data is empty

Stepic/Sources/Modules/NewProfile/NewProfileDataFlow.swift, Stepic/Sources/Modules/NewProfile/NewProfileInteractor.swift, Stepic/Sources/Modules/NewProfile/NewProfileViewController.swift, Stepic/Sources/Modules/NewProfile/Views/NewProfileView.swift, Stepic/Sources/Modules/NewProfileSubmodules/CreatedCourses/NewProfileCreatedCoursesInteractor.swift
**YouTrack task**: [#APPS-2967](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2967)
- Adds pull-to-refresh support for non-organization profiles.
=> New profile pull to refresh

Stepic.xcodeproj/project.pbxproj, Stepic/Legacy/Model/Entities/User/User+CoreDataProperties.swift, Stepic/Legacy/Model/Entities/User/User.swift, Stepic/Legacy/Model/Model.xcdatamodeld/.xccurrentversion, Stepic/Legacy/Model/Model.xcdatamodeld/Model_user_remove_level_v65.xcdatamodel/contents, Stepic/Legacy/Model/StepikSession/AuthInfo.swift, Stepic/Legacy/Model/StepikSession/StepikToken.swift
**YouTrack task**: [#APPS-3000](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3000)
- Removes `level` attribute from the `User` entity and adds `isGuest` attribute.
=> Fix current user isGuest attribute

Stepic/Legacy/Controllers/VideoPlayer/StepikVideoPlayerViewController/StepikVideoPlayerViewController.swift, Stepic/Sources/Modules/Step/StepViewController.swift
**YouTrack task**: [#APPS-2815](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2815)
=> Manually stop video playback on autoplay & dismiss

Stepic/Legacy/Controllers/Placeholders/StepikPlaceholderStyle+Placeholders.swift, Stepic/Sources/Modules/Quizzes/BaseQuiz/BaseQuizDataFlow.swift, Stepic/Sources/Modules/Quizzes/BaseQuiz/BaseQuizInteractor.swift, Stepic/Sources/Modules/Quizzes/BaseQuiz/BaseQuizPresenter.swift, Stepic/Sources/Modules/Quizzes/BaseQuiz/BaseQuizViewController.swift, Stepic/en.lproj/Localizable.strings, Stepic/ru.lproj/Localizable.strings
**YouTrack task**: [#APPS-2726](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2726)
- Handles error on submission polling and adds logic to retry the request.
=> Retry poll submission

Stepic/Sources/Modules/CourseList/CourseListAssembly.swift, Stepic/Sources/Modules/CourseList/CourseListViewController.swift, Stepic/Sources/Modules/CourseList/Views/CourseListView.swift, Stepic/Sources/Modules/CourseList/Views/Layouts/HorizontalCourseListFlowLayout.swift
**YouTrack task**: [#APPS-2613](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2613)
- Adds pagination in horizontal course lists.
=> Horizontal course list pagination

Stepic/Sources/Modules/CourseList/Views/CourseListCardStyle.swift, Stepic/Sources/Modules/CourseList/Views/Widget/SmallCourseWidgetView.swift, Stepic/Sources/Modules/Explore/ExploreViewController.swift, Stepic/Sources/Modules/ExploreSubmodules/CourseListsCollection/Views/GradientCoursesPlaceholderViewFactory.swift, Stepic/Sources/Modules/Home/HomeViewController.swift, Stepic/en.lproj/Localizable.strings, Stepic/ru.lproj/Localizable.strings
**YouTrack task**: [#APPS-3020](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3020)
- Replaces course summary with title.
- Replaces empty state with hidden.
=> Fix visited course list appearance

Podfile, Podfile.lock, Stepic.xcodeproj/project.pbxproj, Stepic.xcodeproj/xcshareddata/xcschemes/Stepic Develop.xcscheme, Stepic.xcodeproj/xcshareddata/xcschemes/Stepic Production.xcscheme, Stepic.xcodeproj/xcshareddata/xcschemes/Stepic Release.xcscheme, Stepic/Legacy/Controllers/Onboarding/Onboarding.storyboard, Stepic/Legacy/Controllers/Placeholders/ControllerWithStepikPlaceholder.swift, Stepic/Legacy/Controllers/Stories/StoryPartViews/TextStoryView.swift, Stepic/Legacy/Model/ExecutionQueue/ExecutionQueue.swift, Stepic/Legacy/Model/Notifications/NotificationPermissionStatus.swift, Stepic/Sources/Frameworks/Analytics/AnalyticsEngine.swift, Stepic/Sources/Model/LaunchArguments.swift, Stepic/Sources/Services/Spotlight/SpotlightIndexingService.swift, StepicTests/DownloaderTests.swift, StepicTests/PinsMapSpec.swift
**YouTrack task**: [#APPS-3006](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3006)
- Adds support for iOS 14.
=> iOS 14 support

Stepic.xcodeproj/project.pbxproj, Stepic/Info-Develop.plist, Stepic/Info-Production.plist, Stepic/Info-Release.plist, StepicTests/Info-Develop.plist, StepicTests/Info-Production.plist, StepicTests/Info-Release.plist, StickerPackExtension/Info-Develop.plist, StickerPackExtension/Info-Production.plist, StickerPackExtension/Info-Release.plist
- Sets version to 1.142 & bump build.
=> Release 1.142

fastlane/metadata/Stepic/en-GB/support_url.txt, fastlane/metadata/Stepic/en-US/support_url.txt, fastlane/metadata/Stepic/ru/support_url.txt
- Updates support URL in App Store.
=> Fix unreachable support URL in app metadata

Stepic/Sources/Modules/NewProfile/NewProfileDataFlow.swift, Stepic/Sources/Modules/NewProfile/NewProfileInteractor.swift, Stepic/Sources/Modules/NewProfile/NewProfileViewController.swift, Stepic/Sources/Modules/NewProfileSubmodules/Certificates/Views/NewProfileCertificatesHorizontalFlowLayout.swift, Stepic/Sources/Modules/NewProfileSubmodules/Certificates/Views/NewProfileCertificatesView.swift
**YouTrack task**: [#APPS-2959](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2959)
- Fetches current user profile updates on appear.
- Replace container margins with insets for the certificates module.
=> New profile fetch current user profile updates

Stepic.xcodeproj/project.pbxproj, Stepic/Legacy/Model/Network/Endpoints/VisitedCoursesAPI.swift, Stepic/Legacy/Model/PlainObjects/VisitedCourse.swift, Stepic/Sources/Modules/CourseList/Provider/CourseListNetworkService.swift, Stepic/Sources/Modules/CourseList/Provider/CourseListTypes.swift, Stepic/Sources/Services/Models/Network/VisitedCoursesNetworkService.swift
**YouTrack task**: [#APPS-3031](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3031)
- Adds synchronization of the visited courses list with API endpoint.
=> Visited courses list sync with API

.swiftlint.yml, Stepic/Legacy/Model/Entities/CodeLimit/CodeLimit.swift, Stepic/Legacy/Model/Entities/CodeSample/CodeSample.swift, Stepic/Legacy/Model/Entities/CodeTemplates/CodeTemplate.swift, Stepic/Legacy/Model/Entities/Lesson/Lesson.swift, Stepic/Legacy/Model/Entities/Progress/Progress.swift, Stepic/Legacy/Model/Entities/Step/Step+CoreDataProperties.swift, Stepic/Legacy/Model/Entities/Step/Step.swift, Stepic/Legacy/Model/Entities/StepOptions/StepOptions.swift, Stepic/Sources/Modules/Lesson/LessonDataFlow.swift, Stepic/Sources/Modules/Lesson/LessonInteractor.swift, Stepic/Sources/Modules/Lesson/LessonProvider.swift
**YouTrack task**: [#APPS-3008](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3008)
- Adds load data policy `cache -> remote`.
- Conditional reload of the lesson module on remote data received.
=> Lesson container load data improvements

Stepic/Legacy/Model/AttemptsSumbissions/Attempt.swift, Stepic/Legacy/Model/AttemptsSumbissions/Datasets/Dataset.swift, Stepic/Legacy/Model/AttemptsSumbissions/Submission.swift, Stepic/Sources/Modules/Quizzes/BaseQuiz/BaseQuizAssembly.swift, Stepic/Sources/Modules/Quizzes/BaseQuiz/BaseQuizInteractor.swift, Stepic/Sources/Modules/Quizzes/BaseQuiz/BaseQuizProvider.swift, Stepic/Sources/Modules/Quizzes/BaseQuiz/BaseQuizViewController.swift
**YouTrack task**: [#APPS-3010](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3010)
- Adds load data policy `cache -> remote`.
- Conditional reload of the quiz module on remote data received.
=> Quiz container load data improvements

Stepic/Legacy/Model/Network/Endpoints/StoryTemplatesAPI.swift
**YouTrack task**: [#APPS-3073](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3073)
- Adds `platform` query param to `StoryTemplatesAPI.retrieve(isPublished:language:maxVersion:page:)`
=> Platform filter for StoryTemplatesAPI

Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabReviews/CourseInfoTabReviewsInteractor.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabReviews/CourseInfoTabReviewsViewController.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabReviews/Views/CourseInfoTabReviewsView.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/CourseInfoTabSyllabusViewController.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/Views/CourseInfoTabSyllabusView.swift
**YouTrack task**: [#APPS-3022](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3022)
- Adds show/hide loading state support for Syllabus and Reviews tabs.
=> Course info tabs display loading state

Stepic/Legacy/Controllers/Stories/SegmentedProgressView.swift, Stepic/Legacy/Controllers/Stories/Story/StoryViewController/StoryViewController.swift
**YouTrack task**: [#APPS-2832](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2832)
- Persists animation info of the `SegmentAnimatedProgressView`.
- Starts animation from the current position if needed, e. g. when view re-appears.
=> Start story progress animation from current position if needed

Stepic/Legacy/Model/Managers/WebControllerManager.swift
**YouTrack task**: [#APPS-3097](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3097)
- Adds `embedded=true` query param for specific web keys.
=> Embedded mode support for WebView

Stepic.xcodeproj/project.pbxproj, Stepic/Sources/Extensions/ThirdParty/PanModal/UIViewController+PresentPadPanModal.swift, Stepic/Sources/Modules/Quizzes/TableQuiz/TableQuizViewController.swift
**YouTrack task**: [#APPS-3101](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3101)
- Forces use of custom modal presentation style on iPad for pan modal.
=> Fix table quiz pan modal presentation on iPad

Stepic.xcodeproj/project.pbxproj, Stepic/Sources/Modules/Quizzes/TableQuiz/TableQuizSelectColumns/TableQuizSelectColumnsViewController.swift, Stepic/Sources/Modules/Quizzes/TableQuiz/TableQuizSelectColumns/Views/TableQuizSelectColumnsHeaderView.swift, Stepic/Sources/Modules/Quizzes/TableQuiz/TableQuizSelectColumns/Views/TableQuizSelectColumnsView.swift, Stepic/Sources/Views/SystemCloseButton.swift
**YouTrack task**: [#APPS-3105](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3105)
- Adds a close button in table quiz pan modal.
=> Add close button in table quiz pad modal

Stepic.xcodeproj/project.pbxproj, Stepic/Legacy/Analytics/Events/AmplitudeAnalyticsEvents.swift, Stepic/Legacy/Model/Network/Endpoints/CourseListsAPI.swift, Stepic/Legacy/Views/Skeleton/Views/CourseList/CatalogBlocksSkeletonView.swift, Stepic/Sources/Helpers/FormatterHelper.swift, Stepic/Sources/Modules/CourseList/Provider/CourseListNetworkService.swift, Stepic/Sources/Modules/CourseList/Provider/CourseListTypes.swift, Stepic/Sources/Modules/CourseList/Views/CourseListColorMode.swift, Stepic/Sources/Modules/Explore/ExploreDataFlow.swift, Stepic/Sources/Modules/Explore/ExploreInteractor.swift, Stepic/Sources/Modules/Explore/ExploreViewController.swift, Stepic/Sources/Modules/Explore/View/CourseListContainerViewFactory.swift, Stepic/Sources/Modules/ExploreSubmodules/CatalogBlocks/CatalogBlocksAssembly.swift, Stepic/Sources/Modules/ExploreSubmodules/CatalogBlocks/CatalogBlocksDataFlow.swift, Stepic/Sources/Modules/ExploreSubmodules/CatalogBlocks/CatalogBlocksInteractor.swift, Stepic/Sources/Modules/ExploreSubmodules/CatalogBlocks/CatalogBlocksPresenter.swift, Stepic/Sources/Modules/ExploreSubmodules/CatalogBlocks/CatalogBlocksProvider.swift, Stepic/Sources/Modules/ExploreSubmodules/CatalogBlocks/CatalogBlocksView.swift, Stepic/Sources/Modules/ExploreSubmodules/CatalogBlocks/CatalogBlocksViewController.swift, Stepic/Sources/Modules/ExploreSubmodules/CatalogBlocks/InputOutput/CatalogBlocksInputProtocol.swift, Stepic/Sources/Modules/ExploreSubmodules/CatalogBlocks/InputOutput/CatalogBlocksOutputProtocol.swift, Stepic/Sources/Services/Models/Persistence/CatalogBlocksPersistenceService.swift
**YouTrack task**: [#APPS-3079](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3079)
- Adds support for catalog block with the type of `full_course_lists`.
- Displays only the first content item.
=> New catalog full course lists

Stepic.xcodeproj/project.pbxproj, Stepic/Legacy/Model/Network/ApiDataDownloader.swift, Stepic/Legacy/Model/Network/Endpoints/CourseListsAPI.swift, Stepic/Legacy/Services/DeepLinks/DeepLinkRoute.swift, Stepic/Legacy/Services/DeepLinks/DeepLinkRouter.swift, Stepic/Legacy/Services/DeepLinks/DeepLinkRoutingService.swift, Stepic/Sources/Model/StepikURLFactory.swift, Stepic/Sources/Modules/CourseList/Provider/CourseListNetworkService.swift, Stepic/Sources/Modules/CourseList/Provider/CourseListTypes.swift, Stepic/Sources/Modules/ExploreSubmodules/CourseListsCollection/Views/GradientCoursesPlaceholderView.swift, Stepic/Sources/Services/Models/Network/CourseListsNetworkService.swift, Stepic/Sources/Services/Models/Persistence/CourseListsPersistenceService.swift, StepicTests/DeepLinkRouteTests.swift, StepicTests/Model/StepikURLFactoryTests.swift
**YouTrack task**: [#APPS-3099](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3099)
- Adds support for catalog deep link with or without course list id.
=> Catalog deep link

Stepic/Sources/Modules/ProfileEdit/ProfileEditInteractor.swift, Stepic/Sources/Modules/ProfileEdit/ProfileEditProvider.swift, Stepic/Sources/Modules/ProfileEdit/ProfileEditViewController.swift
**YouTrack task**: [#APPS-3046](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3046)
- Fixes edit profile remote action - retrieves the latest profile settings before the update.
=> Fix profile update remote action

Stepic.xcodeproj/project.pbxproj, Stepic/Config-Develop.plist, Stepic/Config-Production.plist, Stepic/Config-Release.plist, Stepic/Legacy/Controllers/AdaptiveSteps/CardsSteps/BaseCardsStepsViewController.swift, Stepic/Legacy/Controllers/AdaptiveSteps/CardsSteps/CardsStepsPresenter.swift, Stepic/Legacy/Model/Network/Endpoints/AdaptiveRatingsAPI.swift, Stepic/Legacy/Model/Network/Endpoints/AdaptiveRatingsRestoreAPI.swift, Stepic/Sources/Services/Models/Network/AdaptiveRatingsNetworkService.swift, Stepic/Sources/Services/Models/Network/AdaptiveRatingsRestoreNetworkService.swift
**YouTrack task**: [#APPS-3061](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3061)
- Updates `adaptiveBackendURL`.
- Adds model network services.
=> Update adaptive rating URL

Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabReviews/CourseInfoTabReviewsDataFlow.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabReviews/CourseInfoTabReviewsInteractor.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabReviews/CourseInfoTabReviewsPresenter.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabReviews/CourseInfoTabReviewsViewController.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabReviews/Views/CourseInfoTabReviewsView.swift
**YouTrack task**: [#APPS-2634](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2634)
- Handles remote fetch error and presents error placeholder if needed.
=> Course info tab reviews error placeholder

Stepic/Legacy/Model/Constants/Scripts/Scripts.plist
**YouTrack task**: [#APPS-3117](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3117)
- Defines missing TeX macros.
=> Fix MathJax undefined control sequence \N \Z \R

Stepic/Legacy/Analytics/Events/AmplitudeAnalyticsEvents.swift, Stepic/Sources/Frameworks/InAppPurchases/IAPPaymentsService.swift, Stepic/Sources/Frameworks/InAppPurchases/IAPReceiptValidationService.swift
**YouTrack task**: [#APPS-3048](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3048)
- Refreshes receipt on retry validate course payment.
=> IAP refresh receipt

Stepic/Sources/Modules/Home/HomeViewController.swift
**YouTrack task**: [#APPS-3126](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3126)
- Refreshes enrolled course list on the empty state on the home screen.
=> Refresh home enrolled course list on empty state

Stepic/Sources/Modules/CourseInfo/CourseInfoDataFlow.swift, Stepic/Sources/Modules/CourseInfo/CourseInfoInteractor.swift, Stepic/Sources/Modules/CourseInfo/CourseInfoPresenter.swift
**YouTrack task**: [#APPS-3116](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3116)
- Adds additional course query parameters on buy-in Web and share actions.
=> Course query params

Podfile, Podfile.lock
Bumps:
- [SwiftLint](https://github.com/realm/SwiftLint) from 0.41.0 to 0.42.0
- [Agrume](https://github.com/JanGorman/Agrume) from 5.6.11 to 5.6.12
=> Update dependencies 1.155

Stepic/Legacy/Model/Network/Endpoints/SearchResultsAPI.swift
**YouTrack task**: [#APPS-3138](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3138)
- Updates search course request params.
=> Update search course params

Stepic.xcodeproj/project.pbxproj, Stepic/Sources/Modules/CourseList/Views/CourseListCollectionViewCell.swift, Stepic/Sources/Modules/CourseList/Views/CourseListColorMode.swift, Stepic/Sources/Modules/CourseList/Views/Widget/CourseWidgetCoverView.swift, Stepic/Sources/Modules/CourseList/Views/Widget/CourseWidgetLabel.swift, Stepic/Sources/Modules/CourseList/Views/Widget/CourseWidgetView.swift, Stepic/Sources/Modules/CourseList/Views/Widget/SmallCourseWidgetView.swift, Stepic/Sources/Modules/Explore/View/CourseListContainerViewFactory.swift, Stepic/Sources/Modules/Explore/View/ExploreBlockContainerView/ExploreBlockContainerView.swift, Stepic/Sources/Modules/Explore/View/ExploreBlockContainerView/ExploreCatalogBlockContainerView.swift, Stepic/Sources/Modules/Explore/View/ExploreBlockHeaderView/ExploreBlockHeaderView.swift, Stepic/Sources/Modules/Explore/View/ExploreBlockHeaderView/ExploreCatalogBlockHeaderView.swift, Stepic/Sources/Modules/ExploreSubmodules/CatalogBlocks/CatalogBlocksViewController.swift, Stepic/Sources/Modules/ExploreSubmodules/CatalogBlocksSubmodules/AuthorsCourseList/Views/AuthorsCourseListCollectionViewCell.swift, Stepic/Sources/Modules/ExploreSubmodules/CatalogBlocksSubmodules/AuthorsCourseList/Views/AuthorsCourseListHorizontalFlowLayout.swift, Stepic/Sources/Modules/ExploreSubmodules/CatalogBlocksSubmodules/AuthorsCourseList/Views/AuthorsCourseListView.swift, Stepic/Sources/Modules/ExploreSubmodules/CatalogBlocksSubmodules/SimpleCourseList/Views/Default/DefaultSimpleCourseListHorizontalFlowLayout.swift, Stepic/Sources/Modules/ExploreSubmodules/CatalogBlocksSubmodules/SimpleCourseList/Views/Grid/GridSimpleCourseListView.swift, Stepic/Sources/Modules/ExploreSubmodules/CatalogBlocksSubmodules/SimpleCourseList/Views/Grid/SectionHeader/GridSimpleCourseListCollectionHeaderView.swift, Stepic/Sources/Modules/ExploreSubmodules/ContentLanguageSwitch/Views/ContentLanguageSwitchButton.swift, Stepic/Sources/Modules/ExploreSubmodules/ContentLanguageSwitch/Views/ContentLanguageSwitchView.swift, Stepic/Sources/Modules/ExploreSubmodules/Tags/TagsView.swift, Stepic/Sources/Modules/Home/HomeViewController.swift, Stepic/Sources/Views/Layouts/LeftAlignedCollectionViewFlowLayout.swift
**YouTrack task**: [#APPS-3142](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3142)
- New catalog fixes.
=> New catalog prepare

Stepic.xcodeproj/project.pbxproj, Stepic/Legacy/Model/Entities/Step/Step+CoreDataProperties.swift, Stepic/Legacy/Model/Entities/Step/Step.swift, Stepic/Legacy/Model/Model.xcdatamodeld/.xccurrentversion, Stepic/Legacy/Model/Model.xcdatamodeld/Model_steps_is_enabled_v70.xcdatamodel/contents, Stepic/Legacy/Model/PlainObjects/StepPlainObject.swift, Stepic/Legacy/Model/RemoteConfig/RemoteConfig.swift, Stepic/Sources/Modules/Step/StepAssembly.swift, Stepic/Sources/Modules/Step/StepDataFlow.swift, Stepic/Sources/Modules/Step/StepInteractor.swift, Stepic/Sources/Modules/Step/StepPresenter.swift, Stepic/Sources/Modules/Step/StepView.swift, Stepic/Sources/Modules/Step/StepViewController.swift, Stepic/Sources/Modules/Step/Views/StepDisabledView.swift, Stepic/en.lproj/Localizable.strings, Stepic/ru.lproj/Localizable.strings, StepicTests/ModulesTests/NewStepViewControllerTests.swift
**YouTrack task**: [#APPS-3136](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3136)
- Supports disabled steps.
=> Steps is_enabled

Stepic/Sources/Modules/Quizzes/TableQuiz/TableQuizSelectColumns/TableQuizSelectColumnsViewController.swift, Stepic/Sources/Modules/Quizzes/TableQuiz/TableQuizSelectColumns/Views/TableQuizSelectColumnsView.swift
**YouTrack task**: [#APPS-3109](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3109)
- Positions PanModal content relative to the Safe Area.
=> Position table quiz modal content relative to the Safe Area

Stepic/Legacy/Controllers/Stories/Stories/StoriesPresenter.swift, Stepic/Legacy/Model/Network/Endpoints/StoryTemplatesAPI.swift, Stepic/Legacy/Model/Network/RequestMakers/RetrieveRequestMaker.swift
**YouTrack task**: [#APPS-3149](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3149)
- Adds `requestWithCollectAllPages(requestEndpoint:paramName:params:withManager:)`.
- Collects all available pages for `story-templates` retrieve request.
=> Collect all stories pages

Stepic/Legacy/Controllers/PersonalDeadlines/PersonalDeadlinesModeSelectionViewController.swift, Stepic/Legacy/Controllers/PersonalDeadlines/Service/PersonalDeadlinesTimeService.swift, Stepic/Legacy/Model/ErrorEnums.swift, Stepic/Sources/Modules/CourseInfo/CourseInfoViewController.swift, Stepic/en.lproj/Localizable.strings, Stepic/ru.lproj/Localizable.strings
**YouTrack task**: [#APPS-2765](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2765)
- Fixes infinite progress hud on creating personal deadlines without an internet connection.
=> Fix infinite progress hud on creating personal deadlines

Stepic/Legacy/Controllers/PersonalDeadlines/Service/NotificationService+PersonalDeadline.swift, Stepic/Legacy/Controllers/PersonalDeadlines/Service/PersonalDeadlinesService.swift
**YouTrack task**: [#APPS-3027](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3027)
- Removes local personal deadlines notifications on delete schedule.
=> Fix remove local notifications personal deadlines on delete schedule

Stepic/Sources/Modules/NewProfile/NewProfileViewController.swift
**YouTrack task**: [#APPS-3039](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3039)
- Updates `contentInsets` in profile on device rotation.
=> Fix profile contentInsets

Stepic/Sources/Modules/Explore/ExploreDataFlow.swift, Stepic/Sources/Modules/Explore/ExploreInteractor.swift, Stepic/Sources/Modules/Explore/ExplorePresenter.swift, Stepic/Sources/Modules/Explore/ExploreViewController.swift, Stepic/Sources/Modules/Home/HomeDataFlow.swift, Stepic/Sources/Modules/Home/HomeInteractor.swift, Stepic/Sources/Modules/Home/HomePresenter.swift, Stepic/Sources/Modules/Home/HomeViewController.swift
**YouTrack task**: [#APPS-3145](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3145)
- Moves stories submodule from the catalog to the home screen.
=> Move stories from catalog to home

Stepic/Sources/Modules/Quizzes/NewFreeAnswerQuiz/NewFreeAnswerQuizPresenter.swift, Stepic/en.lproj/Localizable.strings, Stepic/ru.lproj/Localizable.strings
**YouTrack task**: [#APPS-3171](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3171)
- Updates free answer quiz title and placeholder.
=> Update free answer quiz title

Stepic.xcodeproj/project.pbxproj, Stepic/Legacy/Analytics/Events/AmplitudeAnalyticsEvents.swift, Stepic/Legacy/Controllers/Stories/OpenedStories/OpenedStoriesAssembly.swift, Stepic/Legacy/Controllers/Stories/OpenedStories/OpenedStoriesPresenter.swift, Stepic/Legacy/Controllers/Stories/Stories/StoriesPresenter.swift, Stepic/Legacy/Controllers/Stories/Stories/StoriesViewController/StoriesViewController.swift, Stepic/Legacy/Controllers/Stories/Story.swift, Stepic/Legacy/Controllers/Stories/Story/StoryAssembly.swift, Stepic/Legacy/Controllers/Stories/Story/StoryPresenter.swift, Stepic/Legacy/Controllers/Stories/StoryOpenSource.swift, Stepic/Legacy/Model/Network/Endpoints/StoryTemplatesAPI.swift, Stepic/Legacy/Model/Network/RequestMakers/RetrieveRequestMaker.swift, Stepic/Legacy/Services/DeepLinks/DeepLinkRoute.swift, Stepic/Legacy/Services/DeepLinks/DeepLinkRouter.swift, Stepic/Legacy/Services/DeepLinks/DeepLinkRoutingService.swift, Stepic/Legacy/Services/Notifications/NotificationsService.swift, Stepic/Sources/Services/Models/Network/StoryTemplatesNetworkService.swift, Stepic/en.lproj/Localizable.strings, Stepic/ru.lproj/Localizable.strings, StepicTests/Sources/Tests/DeepLinkRouteTests.swift
**YouTrack task**: [#APPS-3168](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3168)
- Adds deep linking to stories
=> Deep link to story

Stepic/Legacy/Controllers/VideoPlayer/Player.swift
**YouTrack task**: [#APPS-3037](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3037)
- Fixes not playing media while in the background on iOS 14, by disabling the video tracks in the player item.
=> Fix playing media while in the background on iOS 14

Stepic.xcodeproj/project.pbxproj, Stepic/Sources/Modules/Quizzes/BaseQuiz/BaseQuizView.swift, Stepic/Sources/Modules/Step/StepView.swift, Stepic/Sources/Modules/Step/StepViewController.swift, Stepic/Sources/Modules/Step/Views/StepControlsView.swift, Stepic/Sources/Views/NextStepButton.swift
**YouTrack task**: [#APPS-3157](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3157)
- Adds next step button for theory steps (text and video content).
=> Next step button for theory steps

Stepic/Sources/Frameworks/ContentProcessor/Processing/ContentProcessingInjection.swift
**YouTrack task**: [#APPS-3198](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3198)
- Detects HTML entities.
=> Fix HTML content detection

Stepic/Sources/Modules/ExploreSubmodules/CatalogBlocksSubmodules/SimpleCourseList/Views/Default/DefaultSimpleCourseListView.swift
**YouTrack task**: [#APPS-3192](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3192)
- Fixes course title is not fit in the card on a small screen.
=> Fix course title not fit in the card on small screen

Stepic.xcodeproj/project.pbxproj, Stepic/Info-Develop.plist, Stepic/Info-Production.plist, Stepic/Info-Release.plist, Stepic/Sources/Modules/Lesson/LessonViewController.swift, StepicTests/Info-Develop.plist, StepicTests/Info-Production.plist, StepicTests/Info-Release.plist, StepicWidget/Info-Develop.plist, StepicWidget/Info-Production.plist, StepicWidget/Info-Release.plist, StickerPackExtension/Info-Develop.plist, StickerPackExtension/Info-Production.plist, StickerPackExtension/Info-Release.plist
- Fixes crash on next/previous unit navigation for iOS 13 devices [#APPS-3208](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3208).
=> Hotfix 1.159

Stepic/Sources/Modules/Quizzes/NewChoiceQuiz/NewChoiceQuizPresenter.swift
**YouTrack task**: [#APPS-3211](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3211)
- Hides empty hints for choice items.
=> Hide empty feedback for choice quiz

Stepic/Sources/Frameworks/ContentProcessor/Processing/ContentProcessingInjection.swift, Stepic/Sources/Modules/Quizzes/BaseQuiz/BaseQuizPresenter.swift, Stepic/Sources/Modules/Quizzes/CodeQuizFullscreen/Tabs/CodeQuizFullscreenRunCode/CodeQuizFullscreenRunCodeView.swift, Stepic/Sources/Modules/Quizzes/NewChoiceQuiz/Views/ChoiceElementView.swift, Stepic/Sources/Modules/Quizzes/NewMatchingQuiz/Views/NewMatchingQuizTitleView.swift, Stepic/Sources/Modules/Quizzes/NewSortingQuiz/Views/NewSortingQuizElementView.swift, Stepic/Theme/Typography.swift, Stepic/stepikcontent.css
**YouTrack task**: [#APPS-3213](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3213)
- Injects font family for web-based content.
- Updates font for feedback views.
=> Use monospace font for feedbacks

Stepic/stepikcontent.css, Stepic/wysiwyg.css
**YouTrack task**: [#APPS-3212](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3212)
- Updates `stepikcontent.css` and `wysiwyg.css`.
=> Update steps CSS

Stepic.xcodeproj/project.pbxproj, Stepic/Legacy/Model/AttemptsSumbissions/Attempt.swift, Stepic/Legacy/Model/AttemptsSumbissions/Submission.swift, Stepic/Legacy/Model/Entities/Block/Block.swift, Stepic/Legacy/Model/Entities/Lesson/Lesson+CoreDataProperties.swift, Stepic/Legacy/Model/Entities/Unit/Unit+CoreDataProperties.swift, Stepic/Legacy/Model/Entities/Unit/Unit.swift, Stepic/Legacy/Model/PlainObjects/AssignmentPlainObject.swift, Stepic/Legacy/Model/PlainObjects/Block/BlockPlainObject.swift, Stepic/Legacy/Model/PlainObjects/Block/BlockType.swift, Stepic/Legacy/Model/PlainObjects/CoursePlainObject.swift, Stepic/Legacy/Model/PlainObjects/LessonPlainObject.swift, Stepic/Legacy/Model/PlainObjects/ProgressPlainObject.swift, Stepic/Legacy/Model/PlainObjects/SectionPlainObject.swift, Stepic/Legacy/Model/PlainObjects/UnitPlainObject.swift, Stepic/Sources/Frameworks/ContentProcessor/Processing/HTMLExtractor.swift, Stepic/Sources/Frameworks/Downloader/DownloadingService/DownloadingService.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/CourseInfoTabSyllabusDataFlow.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/CourseInfoTabSyllabusInteractor.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/CourseInfoTabSyllabusPresenter.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/Provider/SyllabusDownloadsService.swift, Stepic/Sources/Services/AppData/StorageUsageService.swift, StepicTests/Sources/Tests/Model/BlockTypeSpec.swift, StepicTests/Sources/Tests/Model/SubmissionTests.swift
**YouTrack task**: [#APPS-3024](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3024)
- Async `get` and `update` download state.
- Async syllabus presentation.
=> Optimize syllabus download state

Stepic.xcodeproj/project.pbxproj, Stepic/Legacy/AppDelegate.swift, Stepic/Legacy/Model/Notifications/PurchaseCourseLocalNotificationProvider.swift, Stepic/Legacy/Model/PlainObjects/CoursePlainObject.swift, Stepic/Legacy/Services/Notifications/LocalNotifications/LocalNotificationsService.swift, Stepic/Legacy/Services/Notifications/NotificationsService.swift, Stepic/Sources/Extensions/UserNotifications/UNNotificationTrigger+nextTriggerDate.swift, Stepic/Sources/Modules/CourseInfo/CourseInfoAssembly.swift, Stepic/Sources/Modules/CourseInfo/CourseInfoDataFlow.swift, Stepic/Sources/Modules/CourseInfo/CourseInfoInteractor.swift, Stepic/Sources/Modules/CourseInfo/CourseInfoViewController.swift, Stepic/Sources/Services/CoursePurchaseReminder.swift, Stepic/en.lproj/Localizable.strings, Stepic/ru.lproj/Localizable.strings
**YouTrack task**: [#APPS-3209](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3209)
- Reminds about course purchase if the user tapped buy button but didn't buy the course.
=> Course purchase remind notifications

Stepic.xcodeproj/project.pbxproj, Stepic/Sources/Helpers/FormatterHelper.swift, Stepic/Sources/Modules/Submissions/SubmissionsDataFlow.swift, Stepic/Sources/Modules/Submissions/SubmissionsPresenter.swift, Stepic/Sources/Modules/Submissions/SubmissionsViewController.swift, Stepic/Sources/Modules/Submissions/SubmissionsViewModel.swift, Stepic/Sources/Modules/Submissions/Views/Cell/SubmissionView.swift, Stepic/Sources/Modules/Submissions/Views/Cell/SubmissionsCellView.swift, Stepic/Sources/Modules/Submissions/Views/Cell/SubmissionsTableViewCell.swift, Stepic/Sources/Modules/Submissions/Views/SubmissionsTableViewDataSource.swift, Stepic/Theme/Typography.swift, Stepic/en.lproj/Localizable.strings, Stepic/ru.lproj/Localizable.strings
**YouTrack task**: [#APPS-3221](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3221)
- Updates submission cell appearance in the submissions list.
=> Update submission cell appearance

Stepic/Legacy/Controllers/AdaptiveSteps/CardsSteps/BaseCardsStepsViewController.swift, Stepic/Legacy/Controllers/AdaptiveSteps/CardsSteps/CardsStepsPresenter.swift, Stepic/Legacy/Controllers/AdaptiveSteps/CardsSteps/CardsStepsViewController.swift, Stepic/Legacy/Model/Network/SubmissionsFilterQuery.swift, Stepic/Legacy/Services/DeepLinks/DeepLinkRouter.swift, Stepic/Sources/Modules/Discussions/DiscussionsAssembly.swift, Stepic/Sources/Modules/Discussions/DiscussionsDataFlow.swift, Stepic/Sources/Modules/Discussions/DiscussionsInteractor.swift, Stepic/Sources/Modules/Discussions/DiscussionsPresenter.swift, Stepic/Sources/Modules/Discussions/DiscussionsViewController.swift, Stepic/Sources/Modules/Discussions/Views/DiscussionsView.swift, Stepic/Sources/Modules/Step/StepAssembly.swift, Stepic/Sources/Modules/Step/StepDataFlow.swift, Stepic/Sources/Modules/Step/StepInteractor.swift, Stepic/Sources/Modules/Step/StepPresenter.swift, Stepic/Sources/Modules/Step/StepProvider.swift, Stepic/Sources/Modules/Step/StepViewController.swift, Stepic/Sources/Modules/Submissions/SubmissionsDataFlow.swift, Stepic/Sources/Modules/Submissions/SubmissionsInteractor.swift, Stepic/Sources/Modules/Submissions/SubmissionsPresenter.swift, Stepic/Sources/Modules/Submissions/SubmissionsViewController.swift, Stepic/Sources/Services/Models/Network/LessonsNetworkService.swift, Stepic/Sources/Services/Models/Persistence/LessonsPersistenceService.swift, Stepic/en.lproj/Localizable.strings, Stepic/ru.lproj/Localizable.strings
**YouTrack task**: [#APPS-3179](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3179)
- Adds "Submissions" action to the discussions action sheet, that roots to the submissions with a prefilled search text.
=> Present student submissions from comments for teacher

Stepic.xcodeproj/project.pbxproj, Stepic/Legacy/Model/Entities/Lesson/Lesson+CoreDataProperties.swift, Stepic/Legacy/Model/Entities/Lesson/Lesson.swift, Stepic/Legacy/Model/Model.xcdatamodeld/.xccurrentversion, Stepic/Legacy/Model/Model.xcdatamodeld/Model_lesson_courses_units_array_v71.xcdatamodel/contents, Stepic/Legacy/Services/DeepLinks/DeepLinkRoutingService.swift, Stepic/Sources/Modules/Lesson/LessonAssembly.swift, Stepic/Sources/Modules/Lesson/LessonDataFlow.swift, Stepic/Sources/Modules/Lesson/LessonInteractor.swift, Stepic/Sources/Modules/Lesson/LessonPresenter.swift, Stepic/Sources/Modules/Lesson/LessonViewController.swift, Stepic/Sources/Modules/Step/InputOutput/StepOutputProtocol.swift, Stepic/Sources/Modules/Step/StepDataFlow.swift, Stepic/Sources/Modules/Step/StepInteractor.swift, Stepic/Sources/Modules/Step/StepPresenter.swift, Stepic/Sources/Modules/Step/StepViewController.swift, StepicTests/Sources/Tests/ModulesTests/NewStepViewControllerTests.swift
**YouTrack task**: [#APPS-3231](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3231)
- Parses lesson deep-link when requesting open URL from step view.
- Refreshes current lesson module if requested lesson in the same course, otherwise presents the new lesson module.
=> Fix lesson deep-link navigation in lesson module

Stepic/Sources/Extensions/UIKit/UIColor+Hex.swift, Stepic/Sources/Modules/Discussions/DiscussionsPresenter.swift, Stepic/Sources/Modules/Discussions/DiscussionsViewController.swift, Stepic/Sources/Modules/Discussions/Views/Cells/Discussion/DiscussionsBadgesView.swift, Stepic/Sources/Modules/Discussions/Views/Cells/Discussion/DiscussionsBottomControlsView.swift, Stepic/Sources/Modules/Discussions/Views/Cells/Discussion/DiscussionsCellView.swift, Stepic/Sources/Modules/Discussions/Views/Cells/Discussion/DiscussionsTableViewCell.swift, Stepic/Sources/Modules/Discussions/Views/Cells/Discussion/DiscussionsVotesView.swift, Stepic/Sources/Modules/Discussions/Views/TableViewDataSource/DiscussionsTableViewDataSource.swift, Stepic/Sources/Modules/Discussions/Views/TableViewDataSource/DiscussionsTableViewDataSourceDelegate.swift
**YouTrack task**: [#APPS-3226](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3226)
- Updates discussions appearance.
=> Update discussions appearance

Stepic.xcodeproj/project.pbxproj, Stepic/Legacy/Views/Skeleton/SkeletonView.swift, Stepic/Legacy/Views/Skeleton/Skeletonable+UICollectionView.swift, Stepic/Legacy/Views/Skeleton/Skeletonable+UITableView.swift, Stepic/Legacy/Views/Skeleton/Skeletonable+UIView.swift, Stepic/Legacy/Views/Skeleton/Skeletonable.swift, Stepic/Legacy/Views/Skeleton/Views/CourseInfo/CourseInfoHeaderSkeletonView.swift, Stepic/Legacy/Views/Skeleton/Views/CourseInfo/CourseInfoTabInfoSkeletonView.swift, Stepic/Legacy/Views/Skeleton/Views/CourseInfo/CourseInfoTabReviewsCellSkeletonView.swift, Stepic/Sources/Modules/CourseInfo/CourseInfoDataFlow.swift, Stepic/Sources/Modules/CourseInfo/CourseInfoInteractor.swift, Stepic/Sources/Modules/CourseInfo/CourseInfoPresenter.swift, Stepic/Sources/Modules/CourseInfo/CourseInfoViewController.swift, Stepic/Sources/Modules/CourseInfo/Views/CourseInfoHeaderView.swift, Stepic/Sources/Modules/CourseInfo/Views/CourseInfoView.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabInfo/CourseInfoTabInfoDataFlow.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabInfo/CourseInfoTabInfoInteractor.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabInfo/CourseInfoTabInfoPresenter.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabInfo/CourseInfoTabInfoViewController.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabInfo/Views/CourseInfoTabInfoView.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabReviews/Views/CourseInfoTabReviewsView.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/CourseInfoTabSyllabusViewController.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/Views/CourseInfoTabSyllabusView.swift, Stepic/Theme/ColorPalette.swift
**YouTrack task**: [#APPS-3229](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3229)
- Adds skeletons for course info header and tabs.
=> Add skeletons for course info

Stepic/Sources/Modules/Lesson/LessonInteractor.swift
**YouTrack task**: [#APPS-3206](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3206)
- Fixes video auto-played on next step navigation.
=> Fix autoplay on next step navigation

Stepic/Legacy/Controllers/VideoPlayer/StepikVideoPlayerViewController/StepikVideoPlayerViewController.swift
**YouTrack task**: [#APPS-3205](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3205)
- Fixes video player automatically playing after screen unlock when playback state was paused on entering background state.
=> Fix video player automatically playing after screen unlock

Stepic/Sources/Modules/CourseInfo/CourseInfoInteractor.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/CourseInfoTabSyllabusDataFlow.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/CourseInfoTabSyllabusInteractor.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/CourseInfoTabSyllabusPresenter.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/CourseInfoTabSyllabusViewController.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/Views/CourseInfoTabSyllabusView.swift
**YouTrack task**: [#APPS-3159](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3159)
- Adds error state placeholder.
- Presents error state if network request failed.
=> Syllabus error state placeholder

Stepic/Sources/Modules/Discussions/DiscussionsViewController.swift, Stepic/Sources/Modules/Discussions/Views/Cells/Discussion/DiscussionsCellView.swift, Stepic/Sources/Modules/Discussions/Views/Cells/Discussion/DiscussionsTableViewCell.swift, Stepic/Sources/Modules/Discussions/Views/TableViewDataSource/DiscussionsTableViewDataSource.swift, Stepic/Sources/Modules/Discussions/Views/TableViewDataSource/DiscussionsTableViewDataSourceDelegate.swift
**YouTrack task**: [#APPS-3257](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3257)
- Fixes crash.
- Provides better anchor for popover.
=> Fix discussions popover crash

.swiftlint.yml, Stepic.xcodeproj/project.pbxproj, StepicUITests/Sources/StepicUITests.swift, autocorrect.sh, lint.sh
- Adds `SwiftLint Script` to StepicUITests run phase.
- Updates `lint.sh` script to be able to run linter for a specific path.
- Adds `autocorrect.sh` that autocorrects violations and formats code for StepicUITests target.
=> Configure linter for UI Testing target

Stepic/Legacy/TransitionRouters/LastStepRouter.swift
**YouTrack task**: [#APPS-3256](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3256)
- Fixes continue learning when last step does not exist -> open first section and its first unit.
=> Fix continue learning when joined course for the first time

Stepic.xcodeproj/project.pbxproj, Stepic/Legacy/Model/Entities/Step/Step+CoreDataProperties.swift, Stepic/Legacy/Model/Entities/Step/Step.swift, Stepic/Legacy/Model/Model.xcdatamodeld/.xccurrentversion, Stepic/Legacy/Model/Model.xcdatamodeld/Model_step_needs_plan_v73.xcdatamodel/contents, Stepic/Sources/Model/CourseType.swift, Stepic/Sources/Modules/Quizzes/BaseQuiz/Views/QuizFeedbackView.swift, Stepic/Sources/Modules/Step/StepDataFlow.swift, Stepic/Sources/Modules/Step/StepPresenter.swift, Stepic/Sources/Modules/Step/StepView.swift, Stepic/Sources/Modules/Step/StepViewController.swift, Stepic/Sources/Modules/Step/StepViewModel.swift, Stepic/Sources/Modules/Step/Views/StepDisabledViews/StepStudentDisabledView.swift, Stepic/Sources/Modules/Step/Views/StepDisabledViews/StepTeacherDisabledView.swift, Stepic/en.lproj/Localizable.strings, Stepic/ru.lproj/Localizable.strings
**YouTrack task**: [#APPS-3253](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3253)
- Updates disabled step appearance for teachers.
=> Disabled step for teacher

Stepic/Legacy/Controllers/RegistrationSignIn/AuthSocial/SocialAuthViewController.swift, Stepic/Legacy/Model/Managers/WebControllerManager.swift, Stepic/Legacy/Model/Network/SocialSDKProviders/VKSocialSDKProvider.swift
**YouTrack task**: [#APPS-3250](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3250)
- Uses `SFSafariViewController` for VK authorization through a browser.
=> Fix VK authorization through Web

Stepic/Sources/Modules/CourseInfo/Views/CourseInfoHeaderView.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabReviews/Views/Cell/CourseInfoTabReviewsCellView.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/Views/Section/CourseInfoTabSyllabusSectionExamActionButton.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/Views/Section/CourseInfoTabSyllabusSectionView.swift, Stepic/Sources/Modules/NewProfileSubmodules/SocialProfiles/Views/NewProfileSocialProfilesItemView.swift
**YouTrack task**: [#APPS-3263](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3263)
- Fixes course info and social profiles.
=> Fix layout not fitting on small screen sizes

Stepic/Legacy/Model/Entities/Section/Section.swift, Stepic/Legacy/Model/PlainObjects/SectionPlainObject.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/CourseInfoTabSyllabusPresenter.swift
**YouTrack task**: [#APPS-3280](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3280)
- Fixes section exam state when closed.
=> Fix syllabus exam state when closed by dates

Podfile, Podfile.lock
**YouTrack task**: [#APPS-3111](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3111)
- Fixes presenting view controller no longer gets safe area updates once a PanModal has been presented on it.
=> Fix table quiz pan modal safe area updates

Stepic/Legacy/Analytics/Events/AmplitudeAnalyticsEvents.swift, Stepic/Sources/Modules/ExploreSubmodules/ContentLanguageSwitch/ContentLanguageSwitchAssembly.swift, Stepic/Sources/Modules/ExploreSubmodules/ContentLanguageSwitch/ContentLanguageSwitchInteractor.swift, Stepic/Sources/Modules/Settings/SettingsInteractor.swift
**YouTrack task**: [#APPS-3294](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3294)
- Sends `Content language changed` event with parameters `language` = (`ru`/`en`) and `source`=(`catalog`, `settings`).
=> Send analytics event on content language change

Stepic/Legacy/Analytics/Events/StepikAnalyticsEvents.swift, Stepic/Sources/Frameworks/Analytics/Analytics.swift, Stepic/Sources/Modules/CourseInfo/CourseInfoInteractor.swift
**YouTrack task**: [#APPS-3290](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3290)
- Sends event `{"name": "buy-course-pressed","timestamp": 1618562850.951,"data": {"course": 51112}}`
=> Send analytics event on buy course click to metrics API

Stepic/Sources/Modules/DebugMenu/DebugMenuViewController.swift
**YouTrack task**: [#APPS-3285](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3285)
- Adds deep links testing support.
=> Debug menu test deep links

Stepic/Sources/Modules/Quizzes/BaseQuiz/BaseQuizView.swift, Stepic/Sources/Views/NextStepButton.swift
**YouTrack task**: [#APPS-3283](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3283)
- Sets submit button style to outline when quiz status is correct, can retry and current step last in the lesson.
=> Quiz submit button with outline style when can retry last step

Stepic/Legacy/Analytics/Events/AmplitudeAnalyticsEvents.swift, Stepic/Sources/Modules/CourseInfo/CourseInfoInteractor.swift
**YouTrack task**: [#APPS-3341](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3341)
- Sends `User course action` event on user course action made.
=> User course action analytics event

Stepic/Legacy/Analytics/Events/AmplitudeAnalyticsEvents.swift, Stepic/Legacy/TransitionRouters/LastStepRouter.swift, Stepic/Sources/Modules/BaseExplore/BaseExploreDataFlow.swift, Stepic/Sources/Modules/BaseExplore/BaseExploreInteractor.swift, Stepic/Sources/Modules/BaseExplore/BaseExplorePresenter.swift, Stepic/Sources/Modules/BaseExplore/BaseExploreViewController.swift, Stepic/Sources/Modules/CourseInfo/CourseInfoDataFlow.swift, Stepic/Sources/Modules/CourseInfo/CourseInfoInteractor.swift, Stepic/Sources/Modules/CourseInfo/CourseInfoPresenter.swift, Stepic/Sources/Modules/CourseInfo/CourseInfoViewController.swift, Stepic/Sources/Modules/CourseList/InputOutput/CourseListOutputProtocol.swift, Stepic/Sources/Modules/CourseList/Interactor/CourseListInteractor.swift, Stepic/Sources/Modules/ExploreSubmodules/CatalogBlocks/CatalogBlocksInteractor.swift, Stepic/Sources/Modules/ExploreSubmodules/ContinueCourse/ContinueCourseInteractor.swift, Stepic/Sources/Modules/ExploreSubmodules/ContinueCourse/ContinueCourseOutputProtocol.swift, Stepic/Sources/Modules/ExploreSubmodules/CourseListsCollection/CourseListsCollectionInteractor.swift, Stepic/Sources/Modules/FullscreenCourseList/FullscreenCourseListDataFlow.swift, Stepic/Sources/Modules/FullscreenCourseList/FullscreenCourseListInteractor.swift, Stepic/Sources/Modules/FullscreenCourseList/FullscreenCourseListPresenter.swift, Stepic/Sources/Modules/FullscreenCourseList/FullscreenCourseListViewController.swift, Stepic/Sources/Modules/NewProfileSubmodules/CreatedCourses/NewProfileCreatedCoursesDataFlow.swift, Stepic/Sources/Modules/NewProfileSubmodules/CreatedCourses/NewProfileCreatedCoursesInteractor.swift, Stepic/Sources/Modules/NewProfileSubmodules/CreatedCourses/NewProfileCreatedCoursesPresenter.swift, Stepic/Sources/Modules/NewProfileSubmodules/CreatedCourses/NewProfileCreatedCoursesViewController.swift, Stepic/Sources/Services/ApplicationShortcutService.swift, Stepic/Sources/Services/Widget/WidgetRoutingService.swift
**YouTrack task**: [#APPS-3332](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3332)
- Updates `Continue course pressed` event.
=> Update continue course pressed analytics event

Stepic.xcodeproj/project.pbxproj, Stepic/Legacy/Model/Entities/Course/Course+CoreDataProperties.swift, Stepic/Legacy/Model/Entities/Course/Course.swift, Stepic/Legacy/Model/Entities/CourseBenefit/CourseBenefit+CoreDataProperties.swift, Stepic/Legacy/Model/Entities/CourseBenefit/CourseBenefit.swift, Stepic/Legacy/Model/Entities/CourseBenefitSummary/CourseBenefitSummary+CoreDataProperties.swift, Stepic/Legacy/Model/Entities/CourseBenefitSummary/CourseBenefitSummary.swift, Stepic/Legacy/Model/Model.xcdatamodeld/.xccurrentversion, Stepic/Legacy/Model/Model.xcdatamodeld/Model_course_benefits_v80.xcdatamodel/contents, Stepic/Legacy/Model/Network/Endpoints/CourseBenefitSummariesAPI.swift, Stepic/Legacy/Model/Network/Endpoints/CourseBenefitsAPI.swift, Stepic/Legacy/Model/Parser.swift, Stepic/Legacy/Model/PlainObjects/CourseBenefitPlainObject.swift, Stepic/Legacy/Model/PlainObjects/CourseBenefitSummaryPlainObject.swift, Stepic/Sources/Extensions/CoreData/NSManagedObjectContext+BatchDeleteRequest.swift, Stepic/Sources/Model/CourseBenefitStatus.swift, Stepic/Sources/Services/AppData/LogoutDataClearService.swift, Stepic/Sources/Services/Models/Network/CourseBenefitSummariesNetworkService.swift, Stepic/Sources/Services/Models/Network/CourseBenefitsNetworkService.swift, Stepic/Sources/Services/Models/Persistence/CourseBenefitSummariesPersistenceService.swift, Stepic/Sources/Services/Models/Persistence/CourseBenefitsPersistenceService.swift, StepicTests/Data/CourseBenefitSummaries/course-benefit-summaries.json, StepicTests/Sources/TestData.swift, StepicTests/Sources/Tests/Model/CourseBenefitSummaryTests.swift
**YouTrack task**: [#APPS-3335](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3335)
- Adds support for `/api/course-benefit-summaries` and `/api/course-benefits` APIs.
=> Course benefits APIs

Stepic/Legacy/Analytics/Events/AmplitudeAnalyticsEvents.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabReviews/CourseInfoTabReviewsInteractor.swift, Stepic/Sources/Modules/UserCoursesReviews/UserCoursesReviewsAssembly.swift, Stepic/Sources/Modules/UserCoursesReviews/UserCoursesReviewsInteractor.swift
**YouTrack task**: [#APPS-3351](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3351)
- Sends user courses reviews analytics events.
=> User courses reviews analytics

Stepic/Legacy/Analytics/Events/AmplitudeAnalyticsEvents.swift, Stepic/Legacy/Model/Entities/Progress/Progress.swift, Stepic/Sources/Modules/LessonPanModals/LessonFinishedStepsPanModal/LessonFinishedStepsPanModalAssembly.swift, Stepic/Sources/Modules/LessonPanModals/LessonFinishedStepsPanModal/LessonFinishedStepsPanModalDataFlow.swift, Stepic/Sources/Modules/LessonPanModals/LessonFinishedStepsPanModal/LessonFinishedStepsPanModalInteractor.swift, Stepic/Sources/Modules/LessonPanModals/LessonFinishedStepsPanModal/LessonFinishedStepsPanModalPresenter.swift, Stepic/Sources/Modules/LessonPanModals/LessonFinishedStepsPanModal/LessonFinishedStepsPanModalViewController.swift
**YouTrack task**: [#APPS-3360](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3360)
Adds events:
- Finished steps screen opened
- Finished steps share pressed
- Finished steps view certificate pressed
- Finished steps back to assignments pressed
- Finished steps find new course pressed
- Finished steps leave review pressed
=> Finished steps analytics

.swiftlint.yml, Stepic.xcodeproj/project.pbxproj, Stepic/Legacy/Model/Entities/Course/Course+CoreDataProperties.swift, Stepic/Legacy/Model/Model.xcdatamodeld/.xccurrentversion, Stepic/Legacy/Model/Model.xcdatamodeld/Model_course_iap_price_v81.xcdatamodel/contents, Stepic/Legacy/Model/RemoteConfig/RemoteConfig.swift, Stepic/Sources/Frameworks/InAppPurchases/IAPService.swift, Stepic/Sources/Helpers/FormatterHelper.swift, Stepic/Sources/Model/PromoCode.swift, Stepic/Sources/Modules/CourseInfo/CourseInfoDataFlow.swift, Stepic/Sources/Modules/CourseInfo/CourseInfoInteractor.swift, Stepic/Sources/Modules/CourseInfo/CourseInfoPresenter.swift, Stepic/Sources/Modules/CourseList/CourseListAssembly.swift, Stepic/Sources/Modules/CourseList/CourseListDataFlow.swift, Stepic/Sources/Modules/CourseList/CourseListPresenter.swift, Stepic/Sources/Modules/CourseList/CourseWidgetViewModel.swift, Stepic/Sources/Modules/CourseList/Interactor/CourseListInteractor.swift, Stepic/Sources/Modules/CourseList/Provider/CourseListProvider.swift, Stepic/Sources/Modules/CourseList/Views/CourseListCardStyle.swift, Stepic/Sources/Modules/CourseList/Views/Widget/CourseWidgetPriceView.swift, Stepic/Sources/Modules/CourseList/Views/Widget/CourseWidgetView.swift, Stepic/Sources/Modules/CourseList/Views/Widget/SmallCourseWidgetView.swift, Stepic/Sources/Services/WishlistService.swift, Stepic/Theme/ColorPalette.swift, Stepic/en.lproj/Localizable.strings, Stepic/ru.lproj/Localizable.strings
**YouTrack task**: [#APPS-2934](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2934)
- Displays course prices.
=> Display course prices in course lists

Stepic.xcodeproj/project.pbxproj, Stepic/Legacy/Model/Entities/Course/Course+CoreDataProperties.swift, Stepic/Legacy/Model/Entities/CourseBenefitByMonth/CourseBenefitByMonth+CoreDataProperties.swift, Stepic/Legacy/Model/Entities/CourseBenefitByMonth/CourseBenefitByMonth.swift, Stepic/Legacy/Model/Entities/User/User+CoreDataProperties.swift, Stepic/Legacy/Model/Model.xcdatamodeld/.xccurrentversion, Stepic/Legacy/Model/Model.xcdatamodeld/Model_course_benefit_by_month_v83.xcdatamodel/contents, Stepic/Legacy/Model/Network/Endpoints/CourseBenefitByMonthsAPI.swift, Stepic/Sources/Services/AppData/LogoutDataClearService.swift, Stepic/Sources/Services/Models/Network/CourseBenefitByMonthsNetworkService.swift, Stepic/Sources/Services/Models/Persistence/CourseBenefitByMonthsPersistenceService.swift, Stepic/Sources/Services/Models/Persistence/CourseBenefitSummariesPersistenceService.swift, Stepic/Sources/Services/Models/Persistence/CourseBenefitsPersistenceService.swift
**YouTrack task**: [#APPS-3363](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3363)
- Adds `/api/course-benefit-by-months`
- Persistence of the `CourseBenefitByMonth` model.
=> Add course benefit by month API

Stepic/Sources/Modules/Explore/ExploreDataFlow.swift, Stepic/Sources/Modules/Explore/ExploreInteractor.swift, Stepic/Sources/Modules/Explore/ExplorePresenter.swift, Stepic/Sources/Modules/Explore/ExploreViewController.swift
**YouTrack task**: [#APPS-3373](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3373)
- Displays filter button in explore search bar when search results are hidden.
=> Always display filter button in explore search bar

Stepic.xcodeproj/project.pbxproj, Stepic/Legacy/Model/Entities/Course/Course+CoreDataProperties.swift, Stepic/Legacy/Model/Entities/CourseBeneficiary/CourseBeneficiary+CoreDataProperties.swift, Stepic/Legacy/Model/Entities/CourseBeneficiary/CourseBeneficiary.swift, Stepic/Legacy/Model/Entities/CourseBenefit/CourseBenefit.swift, Stepic/Legacy/Model/Entities/User/User+CoreDataProperties.swift, Stepic/Legacy/Model/Model.xcdatamodeld/.xccurrentversion, Stepic/Legacy/Model/Model.xcdatamodeld/Model_course_beneficiaries_v85.xcdatamodel/contents, Stepic/Legacy/Model/Network/Endpoints/CourseBeneficiariesAPI.swift, Stepic/Sources/Modules/CourseRevenue/CourseRevenueAssembly.swift, Stepic/Sources/Modules/CourseRevenue/CourseRevenueInteractor.swift, Stepic/Sources/Modules/CourseRevenue/CourseRevenueProvider.swift, Stepic/Sources/Modules/CourseRevenueSubmodules/CourseBenefitDetail/CourseBenefitDetailPresenter.swift, Stepic/Sources/Services/AppData/LogoutDataClearService.swift, Stepic/Sources/Services/Models/Network/CourseBeneficiariesNetworkService.swift, Stepic/Sources/Services/Models/Persistence/CourseBeneficiariesPersistenceService.swift, Stepic/ru.lproj/Localizable.strings
**YouTrack task**: [#APPS-3393](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3393)
- Adds `api/course-beneficiaries`
- Uses `CourseBeneficiary.percent`
=> Fix course revenue beneficiary percent

Stepic.xcodeproj/project.pbxproj, Stepic/Legacy/Views/Skeleton/Views/StepQuizReviewSkeletonView.swift, Stepic/Sources/Extensions/CoreGraphics/CGSizeExtensions.swift, Stepic/Sources/Modules/StepQuizReview/InputOutput/StepQuizReviewInputProtocol.swift, Stepic/Sources/Modules/StepQuizReview/InputOutput/StepQuizReviewOutputProtocol.swift, Stepic/Sources/Modules/StepQuizReview/StepQuizReviewAssembly.swift, Stepic/Sources/Modules/StepQuizReview/StepQuizReviewDataFlow.swift, Stepic/Sources/Modules/StepQuizReview/StepQuizReviewInteractor.swift, Stepic/Sources/Modules/StepQuizReview/StepQuizReviewPresenter.swift, Stepic/Sources/Modules/StepQuizReview/StepQuizReviewProvider.swift, Stepic/Sources/Modules/StepQuizReview/StepQuizReviewView.swift, Stepic/Sources/Modules/StepQuizReview/StepQuizReviewViewController.swift, Stepic/Sources/Modules/StepQuizReview/Views/StatusView/StepQuizReviewStatusCircleView.swift, Stepic/Sources/Modules/StepQuizReview/Views/StatusView/StepQuizReviewStatusView.swift, Stepic/Sources/Modules/StepQuizReview/Views/StepQuizReviewMessageView.swift, Stepic/Sources/Modules/StepQuizReview/Views/StepQuizReviewStatusContainerView.swift, Stepic/Sources/Modules/StepQuizReview/Views/StepQuizReviewStatusesView.swift, Stepic/Theme/ColorPalette.swift, Stepic/en.lproj/Localizable.strings, Stepic/ru.lproj/Localizable.strings, StepicTests/Sources/Tests/ExtensionsTests/CGSizeExtensionsTests.swift
**YouTrack task**: [#APPS-3400](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3400)
- Adds `StepQuizReview` module.
- Adds necessary views for peer review.
=> Peer review container UI

Stepic.xcodeproj/project.pbxproj, Stepic/Legacy/Model/Entities/Step/Step+CoreDataProperties.swift, Stepic/Legacy/Model/Entities/Step/Step.swift, Stepic/Legacy/Model/Model.xcdatamodeld/.xccurrentversion, Stepic/Legacy/Model/Model.xcdatamodeld/Model_peer_review_step_session_v86.xcdatamodel/contents
- Adds `sessionID` to `Step` entity.
=> Peer review new model version

Stepic.xcodeproj/project.pbxproj, Stepic/Legacy/Helpers/CoreDataHelper.swift, Stepic/Legacy/Model/Entities/Announcement/Announcement+CoreDataProperties.swift, Stepic/Legacy/Model/Entities/Announcement/Announcement.swift, Stepic/Legacy/Model/Entities/Course/Course+CoreDataProperties.swift, Stepic/Legacy/Model/Entities/User/User+CoreDataProperties.swift, Stepic/Legacy/Model/JSONSerializable.swift, Stepic/Legacy/Model/Model.xcdatamodeld/.xccurrentversion, Stepic/Legacy/Model/Model.xcdatamodeld/Model_announcements_v88.xcdatamodel/contents, Stepic/Legacy/Model/Network/Endpoints/AnnouncementsAPI.swift, Stepic/Legacy/Model/Network/RequestMakers/RetrieveRequestMaker.swift, Stepic/Legacy/Model/PlainObjects/Announcements/AnnouncementPlainObject.swift, Stepic/Legacy/Model/PlainObjects/Announcements/AnnouncementStatus.swift, Stepic/Sources/Services/Models/Network/AnnouncementsNetworkService.swift, Stepic/Sources/Services/Models/Persistence/AnnouncementsPersistenceService.swift, Stepic/Sources/Services/Models/Repository/AnnouncementsRepository.swift
**YouTrack task**: [#APPS-3422](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3422)
- Adds `/announcements` API support.
=> Course announcements logic

Stepic/Sources/Modules/CourseList/CourseListDataFlow.swift, Stepic/Sources/Modules/CourseList/CourseListViewController.swift, Stepic/Sources/Modules/CourseList/Views/CourseListView.swift, Stepic/Sources/Modules/CourseList/Views/Layouts/VerticalCourseListFlowLayout.swift, Stepic/Sources/Modules/ExploreSubmodules/CourseListsCollection/Views/GradientCoursesPlaceholderView.swift, Stepic/Sources/Modules/FullscreenCourseList/FullscreenCourseListViewController.swift, Stepic/en.lproj/Localizable.strings, Stepic/ru.lproj/Localizable.strings
**YouTrack task**: [#APPS-3435](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3435)
- Adds dynamic height
- Removes under top bars
- Updates colors
=> Course list gradient header enhancements

Stepic.xcodeproj/xcshareddata/xcschemes/Stepic Production.xcscheme, Stepic/Legacy/Analytics/Events/AmplitudeAnalyticsEvents.swift, Stepic/Legacy/Analytics/Events/AnalyticsEvents.swift, Stepic/Legacy/Analytics/Events/NotificationAlertsAnalytics.swift, Stepic/Legacy/Controllers/Alerts/RateAppViewController/RateAppViewController.swift, Stepic/Legacy/Controllers/Certificates/CertificatesViewController.swift, Stepic/Legacy/Controllers/Courses/SearchResults/SearchResultsPresenter.swift, Stepic/Legacy/Controllers/Courses/SearchResults/SearchResultsViewController.swift, Stepic/Legacy/Controllers/Notifications/NotificationsPresenter.swift, Stepic/Legacy/Controllers/Quizzes/BaseQuiz/QuizPresenter.swift, Stepic/Legacy/Controllers/RegistrationSignIn/AuthEmail/EmailAuthViewController.swift, Stepic/Legacy/Controllers/RegistrationSignIn/Registration/RegistrationViewController.swift, Stepic/Legacy/Controllers/VideoPlayer/StepikVideoPlayerViewController/StepikVideoPlayerViewController.swift, Stepic/Sources/Frameworks/Analytics/Analytics.swift, Stepic/Sources/Frameworks/Analytics/AnalyticsEngine.swift, Stepic/Sources/Modules/CourseSearch/CourseSearchInteractor.swift
**YouTrack task**: [#APPS-3457](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3457)
- Clean up analytics
- Log Amplitude events to Firebase.
=> Clean up analytics

Stepic.xcodeproj/project.pbxproj, Stepic/Legacy/Model/Entities/UserCourse/UserCourse+CoreDataProperties.swift, Stepic/Legacy/Model/Entities/UserCourse/UserCourse.swift, Stepic/Legacy/Model/Model.xcdatamodeld/.xccurrentversion, Stepic/Legacy/Model/Model.xcdatamodeld/Model_user_course_can_be_reviewed_v90.xcdatamodel/contents, Stepic/Legacy/Model/Network/Endpoints/UserCoursesAPI.swift, Stepic/Sources/Modules/HomeSubmodules/UserCoursesReviewsWidget/UserCoursesReviewsWidgetAssembly.swift, Stepic/Sources/Modules/HomeSubmodules/UserCoursesReviewsWidget/UserCoursesReviewsWidgetInteractor.swift, Stepic/Sources/Modules/HomeSubmodules/UserCoursesReviewsWidget/UserCoursesReviewsWidgetProvider.swift, Stepic/Sources/Modules/UserCoursesReviews/UserCoursesReviewsAssembly.swift, Stepic/Sources/Modules/UserCoursesReviews/UserCoursesReviewsInteractor.swift, Stepic/Sources/Modules/UserCoursesReviews/UserCoursesReviewsProvider.swift, Stepic/Sources/Services/Models/Network/UserCoursesNetworkService.swift, Stepic/Sources/Services/Models/Persistence/UserCoursesPersistenceService.swift
**YouTrack task**: [#APPS-3449](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3449)
- Fetches possible courses for review from remote.
=> User courses reviews enhancements

Stepic/Legacy/Controllers/VideoPlayer/StepikVideoPlayerViewController/StepikVideoPlayerViewController.swift
**YouTrack task**: [#APPS-3324](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3324)
- Fixes an issue when video playback starts spontaneously when unlocking if the last playback speed was 2x.
=> Fix video player automatically plays after background

Stepic.xcodeproj/project.pbxproj, Stepic/Info-Develop.plist, Stepic/Info-Production.plist, Stepic/Info-Release.plist, Stepic/Legacy/Analytics/Events/AmplitudeAnalyticsEvents.swift, Stepic/Legacy/AppDelegate.swift, Stepic/Legacy/TransitionRouters/LastStepRouter.swift, Stepic/Sources/Modules/BaseExplore/BaseExploreViewController.swift, Stepic/Sources/Modules/ExploreSubmodules/ContinueCourse/ContinueCourseDataFlow.swift, Stepic/Sources/Modules/ExploreSubmodules/ContinueCourse/ContinueCourseInteractor.swift, Stepic/Sources/Modules/ExploreSubmodules/ContinueCourse/ContinueCoursePresenter.swift, Stepic/Sources/Modules/ExploreSubmodules/ContinueCourse/ContinueCourseView.swift, Stepic/Sources/Modules/ExploreSubmodules/ContinueCourse/ContinueCourseViewController.swift, Stepic/Sources/Services/ApplicationShortcuts/ApplicationShortcutService.swift, Stepic/Sources/Services/ApplicationShortcuts/LastCourseDataShortcutService.swift, Stepic/Sources/Services/SiriShortcuts/SiriShortcutsContinueUserActivityService.swift, Stepic/Sources/Services/SiriShortcuts/SiriShortcutsService.swift, Stepic/Sources/Services/StorageManagers/SiriShortcutsStorageManager.swift, Stepic/Sources/Views/ContinueLastStepView/ContinueActionButton.swift, Stepic/Sources/Views/ContinueLastStepView/ContinueLastStepView.swift, Stepic/Stepic.entitlements, Stepic/en.lproj/Localizable.strings, Stepic/ru.lproj/Localizable.strings
**YouTrack task**: [#APPS-2699](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-2699)
- Adds continue learning Siri shortcut.
=> Siri shortcuts

Stepic/Legacy/Model/Entities/Course/Course.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabInfo/CourseInfoTabInfoPresenter.swift, Stepic/Sources/Modules/CourseList/CourseListPresenter.swift, Stepic/Sources/Modules/LessonPanModals/LessonFinishedStepsPanModal/LessonFinishedStepsPanModalPresenter.swift
**YouTrack task**: [#APPS-3537](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3537)
- Fix course has certificate condition, use `Course.isWithCertificate` instead of `Course.hasCertificate`.
=> Fix course has certificate

Stepic/Legacy/Model/Entities/Section/Section.swift, Stepic/Legacy/Model/PlainObjects/SectionPlainObject.swift, Stepic/Legacy/TransitionRouters/LastStepRouter.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/CourseInfoTabSyllabusPresenter.swift, Stepic/Sources/Modules/Lesson/LessonInteractor.swift
**YouTrack task**: [#APPS-3528](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3528)
- Fixes `Section` reachability logic.
=> Fix Section isReachable

Stepic.xcodeproj/project.pbxproj, Stepic/Legacy/Model/Entities/CourseBenefit/CourseBenefit+CoreDataProperties.swift, Stepic/Legacy/Model/Entities/CourseBenefit/CourseBenefit.swift, Stepic/Legacy/Model/Model.xcdatamodeld/.xccurrentversion, Stepic/Legacy/Model/Model.xcdatamodeld/Model_course_revenue_fixes_v93.xcdatamodel/contents, Stepic/Legacy/Model/PlainObjects/CourseBenefitPlainObject.swift, Stepic/Sources/Helpers/FormatterHelper.swift, Stepic/Sources/Modules/CourseRevenue/CourseRevenuePresenter.swift, Stepic/Sources/Modules/CourseRevenue/Views/CourseRevenueDisclaimerView.swift, Stepic/Sources/Modules/CourseRevenue/Views/CourseRevenueHeaderView.swift, Stepic/Sources/Modules/CourseRevenue/Views/IncomeCard/CourseRevenueIncomeItemView.swift, Stepic/Sources/Modules/CourseRevenueSubmodules/CourseBenefitDetail/CourseBenefitDetailPresenter.swift, Stepic/Sources/Modules/CourseRevenueSubmodules/CourseBenefitDetail/CourseBenefitDetailViewModel.swift, Stepic/Sources/Modules/CourseRevenueSubmodules/CourseBenefitDetail/Views/CourseBenefitDetailItemView.swift, Stepic/Sources/Modules/CourseRevenueSubmodules/CourseBenefitDetail/Views/CourseBenefitDetailView.swift, Stepic/Sources/Modules/CourseRevenueSubmodules/CourseRevenueTabMonthly/CourseRevenueTabMonthlyPresenter.swift, Stepic/Sources/Modules/CourseRevenueSubmodules/CourseRevenueTabMonthly/CourseRevenueTabMonthlyViewModel.swift, Stepic/Sources/Modules/CourseRevenueSubmodules/CourseRevenueTabMonthly/Views/Cell/CourseRevenueTabMonthlyCellView.swift, Stepic/Sources/Modules/CourseRevenueSubmodules/CourseRevenueTabMonthly/Views/Cell/CourseRevenueTabMonthlyItemView.swift, Stepic/Sources/Modules/CourseRevenueSubmodules/CourseRevenueTabMonthly/Views/Cell/CourseRevenueTabMonthlyTotalView.swift, Stepic/Sources/Modules/CourseRevenueSubmodules/CourseRevenueTabPurchases/CourseRevenueTabPurchasesPresenter.swift, Stepic/Sources/Modules/CourseRevenueSubmodules/CourseRevenueTabPurchases/CourseRevenueTabPurchasesViewModel.swift, Stepic/Sources/Modules/CourseRevenueSubmodules/CourseRevenueTabPurchases/Views/Cell/CourseRevenueTabPurchasesCellView.swift, Stepic/en.lproj/Localizable.strings, Stepic/ru.lproj/Localizable.strings
**YouTrack task**: [#APPS-3494](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3494)
- Adds course revenue fixes
=> Course revenue fixes

Stepic/Legacy/Model/Entities/CourseBenefit/CourseBenefit+CoreDataProperties.swift, Stepic/Legacy/Model/Entities/CourseBenefit/CourseBenefit.swift, Stepic/Legacy/Model/PlainObjects/CourseBenefitPlainObject.swift, Stepic/Sources/Modules/CourseRevenue/Views/CourseRevenueHeaderView.swift, Stepic/Sources/Modules/CourseRevenueSubmodules/CourseBenefitDetail/CourseBenefitDetailInteractor.swift, Stepic/Sources/Modules/CourseRevenueSubmodules/CourseBenefitDetail/CourseBenefitDetailPresenter.swift, Stepic/Sources/Modules/CourseRevenueSubmodules/CourseBenefitDetail/CourseBenefitDetailViewModel.swift, Stepic/Sources/Modules/CourseRevenueSubmodules/CourseBenefitDetail/Views/CourseBenefitDetailView.swift, Stepic/Sources/Modules/CourseRevenueSubmodules/CourseRevenueTabPurchases/CourseRevenueTabPurchasesInteractor.swift, Stepic/Sources/Modules/CourseRevenueSubmodules/CourseRevenueTabPurchases/CourseRevenueTabPurchasesPresenter.swift, Stepic/Sources/Modules/CourseRevenueSubmodules/CourseRevenueTabPurchases/CourseRevenueTabPurchasesProvider.swift, Stepic/Sources/Modules/CourseRevenueSubmodules/CourseRevenueTabPurchases/CourseRevenueTabPurchasesViewModel.swift, Stepic/Sources/Modules/CourseRevenueSubmodules/CourseRevenueTabPurchases/Views/Cell/CourseRevenueTabPurchasesCellView.swift, Stepic/en.lproj/Localizable.strings, Stepic/ru.lproj/Localizable.strings
**YouTrack task**: [#APPS-3496](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3496)
- Displays manual course benefits.
=> Course revenue display manual course benefits

Stepic.xcodeproj/project.pbxproj, Stepic/Legacy/Analytics/Events/AmplitudeAnalyticsEvents.swift, Stepic/Legacy/Controllers/Profile/NotificationTimePickerViewController.swift, Stepic/Sources/Frameworks/Notifications/Local/ConcreteNotifications/RetentionLocalNotification.swift, Stepic/Sources/Frameworks/Notifications/Local/ConcreteNotifications/StreakLocalNotification.swift, Stepic/Sources/Frameworks/Notifications/Local/LocalNotificationsMigrator.swift, Stepic/Sources/Frameworks/Notifications/NotificationsService.swift, Stepic/Sources/Modules/NewProfileSubmodules/StreakNotifications/NewProfileStreakNotificationsAssembly.swift, Stepic/Sources/Modules/NewProfileSubmodules/StreakNotifications/NewProfileStreakNotificationsInteractor.swift, Stepic/Sources/Modules/NewProfileSubmodules/StreakNotifications/NewProfileStreakNotificationsProvider.swift, Stepic/Sources/Services/Models/Persistence/SubmissionsPersistenceService.swift
**YouTrack task**: [#APPS-3527](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3527)
- Adds local notifications analytics
=> Local notifications analytics

Stepic/Sources/Frameworks/InAppPurchases/IAPPaymentsService.swift, Stepic/Sources/Frameworks/InAppPurchases/IAPReceiptValidationService.swift, Stepic/Sources/Frameworks/InAppPurchases/IAPService.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoPurchaseModal/CourseInfoPurchaseModalInteractor.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoPurchaseModal/CourseInfoPurchaseModalPresenter.swift, Stepic/Sources/Services/Models/Network/CoursePaymentsNetworkService.swift
**YouTrack task**: [#APPS-3576](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3576)
- Forwards original payments errors.
- Updates analytics events.
=> IAP forward original errors

Stepic/Legacy/Model/Network/APIDefaults.swift, Stepic/Legacy/Model/Network/AuthAPI.swift, Stepic/Legacy/Model/Network/Endpoints/APIEndpoint.swift, Stepic/Legacy/Model/Network/Endpoints/CoursesAPI.swift, Stepic/Legacy/Model/Network/Endpoints/UnitsAPI.swift, Stepic/Legacy/Model/Network/StepikURLSessionConfiguration.swift, Stepic/Sources/Modules/CourseInfo/CourseInfoAssembly.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/CourseInfoTabSyllabusAssembly.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/CourseInfoTabSyllabusInteractor.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoTabSyllabus/Provider/CourseInfoTabSyllabusProvider.swift, Stepic/Sources/Modules/CourseList/CourseListAssembly.swift, Stepic/Sources/Modules/CourseList/Provider/CourseListTypes.swift
**YouTrack task**: [#APPS-3568](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3568)
Increases timeout interval for requests:
- Courses search
- Course syllabus
- My courses course list
- Created courses course list
=> Increase timeout interval for requests

Stepic.xcodeproj/project.pbxproj, Stepic/Sources/Modules/LessonPanModals/LessonFinishedDemoPanModal/LessonFinishedDemoPanModalDataFlow.swift, Stepic/Sources/Modules/LessonPanModals/LessonFinishedDemoPanModal/LessonFinishedDemoPanModalInteractor.swift, Stepic/Sources/Modules/LessonPanModals/LessonFinishedDemoPanModal/LessonFinishedDemoPanModalPresenter.swift, Stepic/Sources/Modules/LessonPanModals/LessonFinishedDemoPanModal/LessonFinishedDemoPanModalProvider.swift, Stepic/Sources/Modules/LessonPanModals/LessonFinishedDemoPanModal/LessonFinishedDemoPanModalView.swift, Stepic/Sources/Modules/LessonPanModals/LessonFinishedDemoPanModal/LessonFinishedDemoPanModalViewController.swift, Stepic/Sources/Modules/LessonPanModals/LessonFinishedDemoPanModal/LessonFinishedDemoPanModalViewModel.swift, Stepic/Sources/Services/Models/Repository/MobileTiersRepository.swift
**YouTrack task**: [#APPS-3560](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3560)
- Adds finished demo lesson modal fixes.
=> Finished demo lesson modal fixes

Stepic/Sources/Modules/CourseInfo/CourseInfoInteractor.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoPurchaseModal/Views/ActionButtons/CourseInfoPurchaseModalActionButtonsView.swift, Stepic/Sources/Modules/Lesson/InputOutput/LessonOutputProtocol.swift, Stepic/Sources/Modules/Lesson/LessonDataFlow.swift, Stepic/Sources/Modules/Lesson/LessonInteractor.swift, Stepic/Sources/Modules/Lesson/LessonViewController.swift, Stepic/Sources/Modules/LessonPanModals/LessonFinishedDemoPanModal/InputOutput/LessonFinishedDemoPanModalOutputProtocol.swift, Stepic/Sources/Modules/LessonPanModals/LessonFinishedDemoPanModal/LessonFinishedDemoPanModalAssembly.swift, Stepic/Sources/Modules/LessonPanModals/LessonFinishedDemoPanModal/LessonFinishedDemoPanModalDataFlow.swift, Stepic/Sources/Modules/LessonPanModals/LessonFinishedDemoPanModal/LessonFinishedDemoPanModalInteractor.swift, Stepic/Sources/Modules/LessonPanModals/LessonFinishedDemoPanModal/LessonFinishedDemoPanModalPresenter.swift, Stepic/Sources/Modules/LessonPanModals/LessonFinishedDemoPanModal/LessonFinishedDemoPanModalProvider.swift, Stepic/Sources/Modules/LessonPanModals/LessonFinishedDemoPanModal/LessonFinishedDemoPanModalView.swift, Stepic/Sources/Modules/LessonPanModals/LessonFinishedDemoPanModal/LessonFinishedDemoPanModalViewController.swift, Stepic/Sources/Modules/LessonPanModals/LessonFinishedDemoPanModal/LessonFinishedDemoPanModalViewModel.swift
**YouTrack task**: [#APPS-3530](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3530)
- Adds wishlist support to finished demo lesson modal.
=> Finished demo lesson modal add course to wishlist

Stepic.xcodeproj/project.pbxproj, Stepic/Info-Develop.plist, Stepic/Info-Production.plist, Stepic/Info-Release.plist, Stepic/Legacy/Model/RemoteConfig/RemoteConfig.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoPurchaseModal/CourseInfoPurchaseModalAssembly.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoPurchaseModal/CourseInfoPurchaseModalViewController.swift, Stepic/Sources/Modules/CourseInfoSubmodules/CourseInfoPurchaseModal/Views/CourseInfoPurchaseModalView.swift, StepicTests/Info-Develop.plist, StepicTests/Info-Production.plist, StepicTests/Info-Release.plist, StepicUITests/Info-Develop.plist, StepicUITests/Info-Production.plist, StepicUITests/Info-Release.plist, StepicWidget/Info-Develop.plist, StepicWidget/Info-Production.plist, StepicWidget/Info-Release.plist, StickerPackExtension/Info-Develop.plist, StickerPackExtension/Info-Production.plist, StickerPackExtension/Info-Release.plist
**YouTrack task**: [#APPS-3594](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3594)
- Adds `purchase_flow_ios_promocode_enabled` feature flag.
=> Hotfix 1.207

Stepic.xcodeproj/project.pbxproj, Stepic/Sources/Modules/CourseInfo/Views/CourseInfoHeaderTitleView.swift, Stepic/Sources/Modules/CourseInfo/Views/CourseInfoHeaderView.swift, Stepic/Sources/Modules/CourseInfo/Views/CourseInfoView.swift
**YouTrack task**: [#APPS-3564](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3564)
- Updates course info header view layout.
=> Update course info header view layout

Stepic/Sources/Services/UnitNavigationService.swift
**YouTrack task**: [#APPS-3565](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3565)
- Fixes next unit navigation when no section data.
=> Fix next unit navigation no section data

Stepic.xcodeproj/project.pbxproj, Stepic/Legacy/Model/Entities/Course/Course+CoreDataProperties.swift, Stepic/Legacy/Model/Entities/Course/Course.swift, Stepic/Legacy/Model/Model.xcdatamodeld/.xccurrentversion, Stepic/Legacy/Model/Model.xcdatamodeld/Model_course_update_purchase_button_behavior_v95.xcdatamodel/contents, Stepic/Sources/Helpers/FormatterHelper.swift, Stepic/Sources/Modules/CourseInfo/CourseInfoHeaderViewModel.swift, Stepic/Sources/Modules/CourseInfo/CourseInfoPresenter.swift, Stepic/Sources/Modules/CourseInfo/Views/CourseInfoHeaderView.swift, Stepic/en.lproj/Localizable.strings, Stepic/ru.lproj/Localizable.strings
**YouTrack task**: [#APPS-3609](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3609)
- Updates purchase button behavior.
=> Update purchase button behavior

Stepic.xcodeproj/project.pbxproj, Stepic/Legacy/Services/DeepLinks/DeepLinkRoute.swift, Stepic/Legacy/Services/DeepLinks/DeepLinkRoutingService.swift, StepicTests/Sources/Tests/DeepLinkRouteTests.swift
**YouTrack task**: [#APPS-3620](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3620)
- Parses `/course/*/info` deep links
- Navigates `courseInfo`
=> Deep link to course info

Stepic/Legacy/Controllers/Quizzes/CodeQuiz/CodeLanguages.swift
**YouTrack task**: [#APPS-3622](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3622)
Adds support for code languages:
1. `python3.10`
2. `haskell 8.8`
3. `java17`
4. `scala3`
5. `dart`
=> Fix unsupported code languages

Stepic/Sources/Views/PromoBannerView.swift
**YouTrack task**: [#APPS-3631](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3631)
- Fixes `PromoBannerView` does not receive touches.
=> Fix promo banner not clickable

Stepic/Legacy/Analytics/AnalyticsUserProperties.swift, Stepic/Legacy/AppDelegate.swift
**YouTrack task**: [#APPS-3634](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3634)
Sets analytics user properties:
1. `accessibility_font_scale`
2. `accessibility_screen_reader_enabled`
=> Analytics accessibility

Stepic/Sources/Modules/CourseInfo/CourseInfoDataFlow.swift, Stepic/Sources/Modules/CourseInfo/CourseInfoInteractor.swift, Stepic/Sources/Modules/CourseInfo/CourseInfoPresenter.swift, Stepic/Sources/Modules/CourseInfo/CourseInfoViewController.swift
**YouTrack task**: [#APPS-3541](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3541)
- Makes course share URL with course id only
=> APPS-3541: Fix course share URL

Stepic.xcodeproj/project.pbxproj, Stepic/Sources/Modules/CourseInfo/CourseInfoPresenter.swift, Stepic/Sources/Modules/CourseInfo/Views/CourseInfoHeaderView.swift, Stepic/Sources/Modules/CourseInfo/Views/CourseInfoPurchaseFeedbackView.swift, Stepic/en.lproj/Localizable.strings, Stepic/ru.lproj/Localizable.strings
**YouTrack task**: [#APPS-3680](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3680)
- Updates course info purchase feedback UI and related localizable strings.
=> APPS-3680: Course info update purchase feedback UI
